// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — allPass returns a predicate true when every predicate passes; anyPass true when any passes.\nexport function allPass<T>(preds: Array<(x: T) => boolean>): (x: T) => boolean {\n  return (x: T) => preds.every(p => p(x))\n}\nexport function anyPass<T>(preds: Array<(x: T) => boolean>): (x: T) => boolean {\n  return (x: T) => preds.some(p => p(x))\n}\n"

registerSkill({
  id: "all-any-pass",
  summary: "allPass returns a predicate true when every predicate passes; anyPass true when any passes.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\ballPass\\b|\\banyPass\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("predicate.*combin|combine.*predicate", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/allAnyPass.ts", content: IMPL }]
  },
})
