// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — take, drop, last, first, partition array helpers.\nexport function take<T>(arr: T[], n: number): T[] {\n  return arr.slice(0, Math.max(0, n))\n}\n\nexport function drop<T>(arr: T[], n: number): T[] {\n  return arr.slice(Math.max(0, n))\n}\n\nexport function last<T>(arr: T[]): T | undefined {\n  return arr[arr.length - 1]\n}\n\nexport function first<T>(arr: T[]): T | undefined {\n  return arr[0]\n}\n\nexport function partition<T>(arr: T[], pred: (item: T) => boolean): [T[], T[]] {\n  const yes: T[] = [], no: T[] = []\n  for (const item of arr) (pred(item) ? yes : no).push(item)\n  return [yes, no]\n}\n"

registerSkill({
  id: "array-utils",
  summary: "take, drop, last, first, partition array helpers.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btake\\b.*\\bdrop\\b|\\bdrop\\b.*\\btake\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bpartition\\b.*array|array.*\\bpartition\\b", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\btake.*first.*n|first.*n.*element", 'i'))) sc += 0.35
  if (s.has(new RegExp("\\blast\\b.*array.*element", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/arrayUtils.ts", content: IMPL }]
  },
})
