// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Myers diff algorithm for arrays: compute add/remove patches, apply patch.\nexport type DiffOp<T> = { op: 'keep' | 'add' | 'remove'; value: T }\n\nexport function diffArrays<T>(from: T[], to: T[], eq = (a: T, b: T) => a === b): DiffOp<T>[] {\n  const m = from.length, n = to.length\n  const dp: number[][] = Array.from({length: m+1}, () => new Array(n+1).fill(0))\n  for (let i = m-1; i >= 0; i--)\n    for (let j = n-1; j >= 0; j--)\n      dp[i][j] = eq(from[i], to[j]) ? dp[i+1][j+1]+1 : Math.max(dp[i+1][j], dp[i][j+1])\n  const ops: DiffOp<T>[] = []\n  let i = 0, j = 0\n  while (i < m || j < n) {\n    if (i < m && j < n && eq(from[i], to[j])) { ops.push({op:'keep',value:from[i]}); i++; j++ }\n    else if (j < n && (i >= m || dp[i][j+1] >= dp[i+1][j])) { ops.push({op:'add',value:to[j]}); j++ }\n    else { ops.push({op:'remove',value:from[i]}); i++ }\n  }\n  return ops\n}\n\nexport function applyPatch<T>(from: T[], patch: DiffOp<T>[]): T[] {\n  return patch.filter(op => op.op !== 'remove').map(op => op.value)\n}\n"

registerSkill({
  id: "array-diff",
  summary: "Myers diff algorithm for arrays: compute add/remove patches, apply patch.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdiff.*array|array.*diff", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bmyers.*diff|lcs.*diff", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bdiffArrays\\b|\\bapplyPatch\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bpatch.*array|compute.*changes.*array", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/arrayDiff.ts", content: IMPL }]
  },
})
