// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Bitwise utilities: setBit, clearBit, toggleBit, hasBit, countBits, isPowerOf2.\nexport function setBit(n: number, bit: number): number { return n | (1 << bit) }\nexport function clearBit(n: number, bit: number): number { return n & ~(1 << bit) }\nexport function toggleBit(n: number, bit: number): number { return n ^ (1 << bit) }\nexport function hasBit(n: number, bit: number): boolean { return (n & (1 << bit)) !== 0 }\nexport function countBits(n: number): number {\n  let count = 0, x = n >>> 0\n  while (x) { count += x & 1; x >>>= 1 }\n  return count\n}\nexport function isPowerOf2(n: number): boolean { return n > 0 && (n & (n - 1)) === 0 }\n"

registerSkill({
  id: "bit-utils",
  summary: "Bitwise utilities: setBit, clearBit, toggleBit, hasBit, countBits, isPowerOf2.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bbit.*manipulat|bitwise.*util", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsetBit\\b|\\bclearBit\\b|\\bhasBit\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bcountBits\\b|\\bpopcount\\b|\\bcount.*set.*bit", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bisPowerOf2\\b|\\bpower.*of.*2", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/bitUtils.ts", content: IMPL }]
  },
})
