// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Compute the axis-aligned bounding box of 2D points using boundingBox, returning [minX, minY, maxX, maxY]; an empty input yields [0,0,0,0].\nexport function boundingBox(points: [number, number][]): [number, number, number, number] {\n  if (points.length === 0) return [0, 0, 0, 0];\n  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;\n  for (const [x, y] of points) {\n    if (x < minX) minX = x;\n    if (y < minY) minY = y;\n    if (x > maxX) maxX = x;\n    if (y > maxY) maxY = y;\n  }\n  return [minX, minY, maxX, maxY];\n}\n\n"

registerSkill({
  id: "bounding-box-2d",
  summary: "Compute the axis-aligned bounding box of 2D points using boundingBox, returning [minX, minY, maxX, maxY]; an empty input yields [0,0,0,0].",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bboundingBox\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("bounding box", 'i'))) sc += 0.2
  if (s.has(new RegExp("axis-aligned", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bpoints?\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/boundingBox.ts", content: IMPL }]
  },
})
