// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — caesarCipher shifts letters by a number (wrapping within a-z/A-Z); non-letters are unchanged; negative shift decodes.\nexport function caesarCipher(s: string, shift: number): string {\n  return s.replace(/[a-zA-Z]/g, c => {\n    const base = c <= 'Z' ? 65 : 97\n    return String.fromCharCode(((c.charCodeAt(0) - base + ((shift % 26) + 26)) % 26) + base)\n  })\n}\n"

registerSkill({
  id: "caesar-cipher",
  summary: "caesarCipher shifts letters by a number (wrapping within a-z/A-Z); non-letters are unchanged; negative shift decodes.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcaesarCipher\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("caesar.*cipher|shift.*letter|letter.*shift", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/caesarCipher.ts", content: IMPL }]
  },
})
