// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Capitalize the first letter of each word (title case).\nexport function capitalize(str: string): string {\n  return str.replace(/\\b\\w/g, c => c.toUpperCase())\n}\n"

registerSkill({
  id: "capitalize",
  summary: "Capitalize the first letter of each word (title case).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcapitaliz", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\btitle[- ]?case\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bfirst.*letter.*upper|upper.*first.*letter", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/capitalize.ts", content: IMPL }]
  },
})
