// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — CircularBuffer is a fixed-capacity ring buffer that overwrites the oldest item when full; toArray returns oldest first.\nexport class CircularBuffer<T> {\n  private buf: T[] = []\n  private start = 0\n  constructor(private capacity: number) {}\n  push(item: T): void {\n    if (this.buf.length < this.capacity) this.buf.push(item)\n    else { this.buf[this.start] = item; this.start = (this.start + 1) % this.capacity }\n  }\n  size(): number { return this.buf.length }\n  isFull(): boolean { return this.buf.length === this.capacity }\n  toArray(): T[] {\n    const out: T[] = []\n    for (let i = 0; i < this.buf.length; i++) out.push(this.buf[(this.start + i) % this.buf.length])\n    return out\n  }\n}\n"

registerSkill({
  id: "circular-buffer",
  summary: "CircularBuffer is a fixed-capacity ring buffer that overwrites the oldest item when full; toArray returns oldest first.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bCircularBuffer\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("circular buffer|ring buffer", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/circularBuffer.ts", content: IMPL }]
  },
})
