// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — coinChangeMin returns the minimum number of coins to make an amount, or -1 if impossible, with unlimited coins.\nexport function coinChangeMin(coins: number[], amount: number): number {\n  const dp = new Array(amount + 1).fill(Infinity)\n  dp[0] = 0\n  for (let a = 1; a <= amount; a++)\n    for (const c of coins)\n      if (c <= a && dp[a - c] + 1 < dp[a]) dp[a] = dp[a - c] + 1\n  return dp[amount] === Infinity ? -1 : dp[amount]\n}\n"

registerSkill({
  id: "coin-change-min",
  summary: "coinChangeMin returns the minimum number of coins to make an amount, or -1 if impossible, with unlimited coins.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcoinChangeMin\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("coin change|minimum coins|fewest coins", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/coinChangeMin.ts", content: IMPL }]
  },
})
