// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — All k-combinations and permutations of an array.\nexport function combinations<T>(arr: T[], k: number): T[][] {\n  if (k === 0) return [[]]\n  if (k > arr.length) return []\n  const [first, ...rest] = arr\n  return [\n    ...combinations(rest, k - 1).map(c => [first, ...c]),\n    ...combinations(rest, k),\n  ]\n}\n\nexport function permutations<T>(arr: T[]): T[][] {\n  if (arr.length <= 1) return [arr]\n  return arr.flatMap((item, i) =>\n    permutations([...arr.slice(0, i), ...arr.slice(i + 1)]).map(p => [item, ...p])\n  )\n}\n\nexport function powerSet<T>(arr: T[]): T[][] {\n  return arr.reduce<T[][]>((acc, item) => [...acc, ...acc.map(s => [...s, item])], [[]])\n}\n"

registerSkill({
  id: "combinations",
  summary: "All k-combinations and permutations of an array.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcombination\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bpermutation\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bpowerSet\\b|\\bpower.*set", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bnChooseK\\b|\\bcombination.*array", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/combinations.ts", content: IMPL }]
  },
})
