// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Count array elements by a key function; tally occurrences.\nexport function countBy<T>(arr: T[], key: (item: T) => string | number): Record<string, number> {\n  const out: Record<string, number> = {}\n  for (const item of arr) {\n    const k = String(key(item))\n    out[k] = (out[k] ?? 0) + 1\n  }\n  return out\n}\n\nexport function frequencies<T>(arr: T[]): Map<T, number> {\n  const out = new Map<T, number>()\n  for (const item of arr) out.set(item, (out.get(item) ?? 0) + 1)\n  return out\n}\n"

registerSkill({
  id: "count-by",
  summary: "Count array elements by a key function; tally occurrences.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcountBy\\b|\\bcount.*by\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bfrequenc|\\btally\\b", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\boccurrence.*count|count.*occurrence", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/countBy.ts", content: IMPL }]
  },
})
