// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Count non-overlapping occurrences of a substring in a string.\nexport function countOccurrences(str: string, sub: string): number {\n  if (!sub) return 0\n  let count = 0, pos = 0\n  while ((pos = str.indexOf(sub, pos)) !== -1) { count++; pos += sub.length }\n  return count\n}\n"

registerSkill({
  id: "count-occurrences",
  summary: "Count non-overlapping occurrences of a substring in a string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcount.*occurrence|occurrence.*count", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bcountOccurrences\\b", 'i'))) sc += 0.3
  if (s.has(new RegExp("\\bcount.*substring|substring.*count", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/countOccurrences.ts", content: IMPL }]
  },
})
