// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Counter tallies item frequencies with add, count, total, and mostCommon (descending by count).\nexport class Counter<T> {\n  private m = new Map<T, number>()\n  add(item: T): void { this.m.set(item, (this.m.get(item) ?? 0) + 1) }\n  count(item: T): number { return this.m.get(item) ?? 0 }\n  total(): number { let t = 0; for (const v of this.m.values()) t += v; return t }\n  mostCommon(n: number): [T, number][] {\n    return [...this.m.entries()].sort((a, b) => b[1] - a[1]).slice(0, n)\n  }\n}\n"

registerSkill({
  id: "counter-frequency",
  summary: "Counter tallies item frequencies with add, count, total, and mostCommon (descending by count).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcounterFrequency\\b|\\bCounter\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("most.?common.*count|frequency.*counter", 'i'))) sc += 0.6
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/counterFrequency.ts", content: IMPL }]
  },
})
