// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — dateRangeDays returns an inclusive list of YYYY-MM-DD UTC date strings from date a to date b.\nexport function dateRangeDays(a: Date, b: Date): string[] {\n  const out: string[] = []\n  const cur = new Date(Date.UTC(a.getUTCFullYear(), a.getUTCMonth(), a.getUTCDate()))\n  const end = new Date(Date.UTC(b.getUTCFullYear(), b.getUTCMonth(), b.getUTCDate()))\n  while (cur <= end) { out.push(cur.toISOString().slice(0,10)); cur.setUTCDate(cur.getUTCDate()+1) }\n  return out\n}\n"

registerSkill({
  id: "date-range-days",
  summary: "dateRangeDays returns an inclusive list of YYYY-MM-DD UTC date strings from date a to date b.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdateRangeDays\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("date.*range.*list|list.*dates.*between", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/dateRangeDays.ts", content: IMPL }]
  },
})
