// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Digit sum computing the sum of the decimal digits of the absolute value of n via digitSum.\nexport function digitSum(n: number): number {\n  let m = Math.abs(Math.trunc(n));\n  let sum = 0;\n  while (m > 0) {\n    sum += m % 10;\n    m = Math.floor(m / 10);\n  }\n  return sum;\n}\n\n"

registerSkill({
  id: "digit-sum",
  summary: "Digit sum computing the sum of the decimal digits of the absolute value of n via digitSum.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdigitSum\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bdigit\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bdecimal\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bsum\\b", 'i'))) sc += 0.15
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/digitSum.ts", content: IMPL }]
  },
})
