// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — editDistanceLev returns the Levenshtein edit distance between two strings.\nexport function editDistanceLev(a: string, b: string): number {\n  const m = a.length, n = b.length\n  const dp = Array.from({ length: m + 1 }, (_, i) => Array.from({ length: n + 1 }, (_, j) => i === 0 ? j : j === 0 ? i : 0))\n  for (let i = 1; i <= m; i++)\n    for (let j = 1; j <= n; j++)\n      dp[i][j] = a[i - 1] === b[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])\n  return dp[m][n]\n}\n"

registerSkill({
  id: "edit-distance-lev",
  summary: "editDistanceLev returns the Levenshtein edit distance between two strings.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\beditDistanceLev\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("levenshtein|edit distance", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/editDistanceLev.ts", content: IMPL }]
  },
})
