// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Flatten a nested object to dot-separated keys; unflatten back.\nexport function flattenObject(\n  obj: Record<string, unknown>,\n  prefix = '',\n): Record<string, unknown> {\n  const out: Record<string, unknown> = {}\n  for (const [k, v] of Object.entries(obj)) {\n    const key = prefix ? `${prefix}.${k}` : k\n    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {\n      Object.assign(out, flattenObject(v as Record<string, unknown>, key))\n    } else {\n      out[key] = v\n    }\n  }\n  return out\n}\n\nexport function unflattenObject(obj: Record<string, unknown>): Record<string, unknown> {\n  const out: Record<string, unknown> = {}\n  for (const [k, v] of Object.entries(obj)) {\n    const parts = k.split('.')\n    let cur = out\n    for (let i = 0; i < parts.length - 1; i++) {\n      if (!cur[parts[i]] || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {}\n      cur = cur[parts[i]] as Record<string, unknown>\n    }\n    cur[parts[parts.length - 1]] = v\n  }\n  return out\n}\n"

registerSkill({
  id: "flatten-object",
  summary: "Flatten a nested object to dot-separated keys; unflatten back.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bflatten.*object|flat.*object\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bdot.*notation|dot.*separated.*key", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bunflatten.*object", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/flattenObject.ts", content: IMPL }]
  },
})
