// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — fnv1aHash computes the 32-bit FNV-1a hash of a string as an unsigned integer.\nexport function fnv1aHash(str: string): number {\n  let h = 2166136261\n  for (const ch of Buffer.from(str, 'utf8')) { h ^= ch; h = Math.imul(h, 16777619) >>> 0 }\n  return h\n}\n"

registerSkill({
  id: "fnv1a-hash",
  summary: "fnv1aHash computes the 32-bit FNV-1a hash of a string as an unsigned integer.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bfnv1aHash\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("fnv.?1a|fowler.*noll.*vo", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/fnv1aHash.ts", content: IMPL }]
  },
})
