// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — curry, partial, memoize, identity, constant, noop, flip.\nexport function curry<T extends unknown[], R>(fn: (...args: T) => R): (...args: unknown[]) => unknown {\n  return function curried(...args: unknown[]): unknown {\n    if (args.length >= fn.length) return (fn as (...a: unknown[]) => R)(...args)\n    return (...more: unknown[]) => curried(...args, ...more)\n  }\n}\n\nexport function partial<T extends unknown[], R>(fn: (...args: T) => R, ...pre: unknown[]): (...args: unknown[]) => R {\n  return (...args: unknown[]) => (fn as (...a: unknown[]) => R)(...pre, ...args)\n}\n\nexport function identity<T>(x: T): T { return x }\nexport function constant<T>(x: T): () => T { return () => x }\nexport function noop(): void {}\nexport function flip<A, B, C>(fn: (a: A, b: B) => C): (b: B, a: A) => C {\n  return (b, a) => fn(a, b)\n}\n"

registerSkill({
  id: "fp-utils",
  summary: "curry, partial, memoize, identity, constant, noop, flip.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcurry\\b.*function|function.*\\bcurry\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bpartial.*application|partial.*function", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bcurry.*partial|functional.*programming.*util", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bflip\\b.*argument|argument.*\\bflip\\b", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/fpUtils.ts", content: IMPL }]
  },
})
