// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — gridBfsSteps returns the minimum 4-directional steps between two grid cells where 1 is a wall and 0 is open, or -1 if unreachable.\nexport function gridBfsSteps(grid, sr, sc, tr, tc) {\n  const R = grid.length, C = grid[0]?.length ?? 0\n  if (grid[sr][sc] === 1 || grid[tr][tc] === 1) return -1\n  const dist = Array.from({ length: R }, () => new Array(C).fill(-1))\n  dist[sr][sc] = 0\n  const queue = [[sr, sc]]\n  const dirs = [[1,0],[-1,0],[0,1],[0,-1]]\n  while (queue.length) {\n    const [r, c] = queue.shift()\n    if (r === tr && c === tc) return dist[r][c]\n    for (const [dr, dc] of dirs) {\n      const nr = r+dr, nc = c+dc\n      if (nr>=0 && nr<R && nc>=0 && nc<C && grid[nr][nc]===0 && dist[nr][nc]===-1) {\n        dist[nr][nc] = dist[r][c]+1; queue.push([nr, nc])\n      }\n    }\n  }\n  return dist[tr][tc]\n}\n"

registerSkill({
  id: "grid-bfs-steps",
  summary: "gridBfsSteps returns the minimum 4-directional steps between two grid cells where 1 is a wall and 0 is open, or -1 if unreachable.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bgridBfsSteps\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("grid.*bfs|shortest.*grid|maze.*path", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/gridBfsSteps.ts", content: IMPL }]
  },
})
