// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — hasCycleUndirected reports whether an undirected graph contains a cycle.\nexport function hasCycleUndirected(n, edges) {\n  const parent = Array.from({ length: n }, (_, i) => i)\n  const find = (x) => { while (parent[x] !== x) { parent[x] = parent[parent[x]]; x = parent[x] } return x }\n  for (const [u, v] of edges) {\n    const ru = find(u), rv = find(v)\n    if (ru === rv) return true\n    parent[ru] = rv\n  }\n  return false\n}\n"

registerSkill({
  id: "has-cycle-undirected",
  summary: "hasCycleUndirected reports whether an undirected graph contains a cycle.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bhasCycleUndirected\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("cycle.*undirected|undirected.*cycle", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/hasCycleUndirected.ts", content: IMPL }]
  },
})
