// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Encode a string to hex; decode hex back to a string.\nexport function hexEncode(str: string): string {\n  return Buffer.from(str, 'utf8').toString('hex')\n}\n\nexport function hexDecode(hex: string): string {\n  return Buffer.from(hex, 'hex').toString('utf8')\n}\n"

registerSkill({
  id: "hex-encode",
  summary: "Encode a string to hex; decode hex back to a string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bhex.*encod|encod.*hex", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bhexEncode\\b|\\bhexDecode\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bhexadecimal.*string|string.*hexadecimal", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/hexEncode.ts", content: IMPL }]
  },
})
