// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — humanizeRelativeTime produces phrases like \"in 3 days\" or \"2 hours ago\" from two Dates using the largest unit.\nexport function humanizeRelativeTime(from: Date, to: Date): string {\n  const diff = to.getTime() - from.getTime()\n  const abs = Math.abs(diff)\n  const units: [string, number][] = [['year',365*24*3600*1000],['month',30*24*3600*1000],['day',24*3600*1000],['hour',3600*1000],['minute',60*1000],['second',1000]]\n  for (const [unit, factor] of units) {\n    const n = Math.floor(abs / factor)\n    if (n >= 1) {\n      const label = n === 1 ? unit : unit + 's'\n      return diff >= 0 ? 'in ' + n + ' ' + label : n + ' ' + label + ' ago'\n    }\n  }\n  return 'just now'\n}\n"

registerSkill({
  id: "humanize-relative-time",
  summary: "humanizeRelativeTime produces phrases like \"in 3 days\" or \"2 hours ago\" from two Dates using the largest unit.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bhumanizeRelativeTime\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("relative.*time|time.*ago|humanize.*time", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/humanizeRelativeTime.ts", content: IMPL }]
  },
})
