// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Parse INI/config file format to a nested object; stringify back.\nexport type INIData = Record<string, string | Record<string, string>>\n\nexport function parseINI(text: string): INIData {\n  const out: INIData = {}\n  let section = ''\n  for (const raw of text.split('\\n')) {\n    const line = raw.trim()\n    if (!line || line.startsWith(';') || line.startsWith('#')) continue\n    const sMatch = line.match(/^\\[([^\\]]+)\\]$/)\n    if (sMatch) { section = sMatch[1]; out[section] = out[section] as Record<string, string> ?? {}; continue }\n    const eq = line.indexOf('=')\n    if (eq === -1) continue\n    const key = line.slice(0, eq).trim()\n    const val = line.slice(eq + 1).trim()\n    if (section) (out[section] as Record<string, string>)[key] = val\n    else out[key] = val\n  }\n  return out\n}\n\nexport function stringifyINI(data: INIData): string {\n  const lines: string[] = []\n  const global: [string, string][] = []\n  const sections: [string, Record<string, string>][] = []\n  for (const [k, v] of Object.entries(data)) {\n    if (typeof v === 'string') global.push([k, v])\n    else sections.push([k, v])\n  }\n  for (const [k, v] of global) lines.push(`${k}=${v}`)\n  for (const [sec, kvs] of sections) {\n    if (lines.length) lines.push('')\n    lines.push(`[${sec}]`)\n    for (const [k, v] of Object.entries(kvs)) lines.push(`${k}=${v}`)\n  }\n  return lines.join('\\n')\n}\n"

registerSkill({
  id: "ini-parse",
  summary: "Parse INI/config file format to a nested object; stringify back.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bini\\b.*pars|pars.*\\bini\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bconfig.*file.*pars|pars.*config.*file", 'i'))) sc += 0.35
  if (s.has(new RegExp("\\bparseINI\\b|\\bstringifyINI\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/iniParse.ts", content: IMPL }]
  },
})
