// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — IntervalSet maintains merged numeric intervals with add (merging overlaps), contains, and list (sorted).\nexport class IntervalSet {\n  private iv: [number, number][] = []\n  add(s: number, e: number): void {\n    if (s > e) { const t = s; s = e; e = t }\n    this.iv.push([s, e]); this.iv.sort((a, b) => a[0] - b[0])\n    const m: [number, number][] = []\n    for (const [a, b] of this.iv) {\n      if (m.length && a <= m[m.length - 1][1]) m[m.length - 1][1] = Math.max(m[m.length - 1][1], b)\n      else m.push([a, b])\n    }\n    this.iv = m\n  }\n  contains(x: number): boolean { return this.iv.some(([a, b]) => x >= a && x <= b) }\n  list(): [number, number][] { return this.iv.map(([a, b]) => [a, b]) }\n}\n"

registerSkill({
  id: "interval-set",
  summary: "IntervalSet maintains merged numeric intervals with add (merging overlaps), contains, and list (sorted).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bIntervalSet\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("interval.*merg|merg.*interval", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/intervalSet.ts", content: IMPL }]
  },
})
