// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Integer square root computing the floor of the square root of n exactly without floating point error via integerSqrt.\nexport function integerSqrt(n: number): number {\n  if (n < 0) return 0;\n  if (n < 2) return n;\n  let x = Math.floor(Math.sqrt(n));\n  while (x * x > n) x--;\n  while ((x + 1) * (x + 1) <= n) x++;\n  return x;\n}\n\n"

registerSkill({
  id: "integer-sqrt",
  summary: "Integer square root computing the floor of the square root of n exactly without floating point error via integerSqrt.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bintegerSqrt\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bsquare root\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\binteger\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bfloor\\b", 'i'))) sc += 0.15
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/integerSqrt.ts", content: IMPL }]
  },
})
