// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Swap keys and values of a string-keyed object.\nexport function invert(obj: Record<string, string>): Record<string, string> {\n  const out: Record<string, string> = {}\n  for (const [k, v] of Object.entries(obj)) out[v] = k\n  return out\n}\n"

registerSkill({
  id: "invert",
  summary: "Swap keys and values of a string-keyed object.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\binvert\\b.*object|object.*\\binvert\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bswap.*keys.*values|keys.*values.*swap|flip.*object", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\binvert\\b", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/invert.ts", content: IMPL }]
  },
})
