// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isBipartiteGraph reports whether an undirected graph is 2-colorable (bipartite).\nexport function isBipartiteGraph(n, edges) {\n  const adj = Array.from({ length: n }, () => [])\n  for (const [u, v] of edges) { adj[u].push(v); adj[v].push(u) }\n  const color = new Array(n).fill(-1)\n  for (let s = 0; s < n; s++) {\n    if (color[s] !== -1) continue\n    const queue = [s]; color[s] = 0\n    while (queue.length) {\n      const u = queue.shift()\n      for (const v of adj[u]) {\n        if (color[v] === -1) { color[v] = 1 - color[u]; queue.push(v) }\n        else if (color[v] === color[u]) return false\n      }\n    }\n  }\n  return true\n}\n"

registerSkill({
  id: "is-bipartite-graph",
  summary: "isBipartiteGraph reports whether an undirected graph is 2-colorable (bipartite).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisBipartiteGraph\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("bipartite|2.?colorable", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isBipartiteGraph.ts", content: IMPL }]
  },
})
