// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isCreditCardType identifies the credit card brand visa mastercard amex or discover by prefix and length, ignoring spaces.\nexport function isCreditCardType(s: string): string {\n  const d = s.replace(/\\s+/g, '');\n  if (d.length === 0 || !/^\\d+$/.test(d)) return 'unknown';\n  if ((d.length === 13 || d.length === 16 || d.length === 19) && /^4/.test(d)) return 'visa';\n  if (d.length === 15 && /^3[47]/.test(d)) return 'amex';\n  if (d.length === 16) {\n    const p2 = parseInt(d.slice(0, 2), 10);\n    const p4 = parseInt(d.slice(0, 4), 10);\n    if (p2 >= 51 && p2 <= 55) return 'mastercard';\n    if (p4 >= 2221 && p4 <= 2720) return 'mastercard';\n  }\n  if (d.length === 16 || d.length === 19) {\n    if (/^6011/.test(d)) return 'discover';\n    if (/^65/.test(d)) return 'discover';\n    const p3 = parseInt(d.slice(0, 3), 10);\n    if (p3 >= 644 && p3 <= 649) return 'discover';\n  }\n  return 'unknown';\n}\n\n"

registerSkill({
  id: "is-credit-card-type",
  summary: "isCreditCardType identifies the credit card brand visa mastercard amex or discover by prefix and length, ignoring spaces.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisCreditCardType\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bcredit card\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bbrand\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bprefix\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isCreditCardType.ts", content: IMPL }]
  },
})
