// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Validate an email address format.\nexport function isEmail(str: string): boolean {\n  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(str)\n}\n"

registerSkill({
  id: "is-email",
  summary: "Validate an email address format.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bvalidate.*email|email.*validat", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bisEmail\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bemail.*format|email.*check", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isEmail.ts", content: IMPL }]
  },
})
