// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isISBN validates whether a string is a valid ISBN-10 or ISBN-13 book number, ignoring hyphens and spaces.\nexport function isISBN(s: string): boolean {\n  const c = s.replace(/[\\s-]/g, '');\n  if (/^\\d{9}[\\dX]$/.test(c)) {\n    let sum = 0;\n    for (let i = 0; i < 9; i++) sum += (10 - i) * (c.charCodeAt(i) - 48);\n    sum += c[9] === 'X' ? 10 : c.charCodeAt(9) - 48;\n    return sum % 11 === 0;\n  }\n  if (/^\\d{13}$/.test(c)) {\n    let sum = 0;\n    for (let i = 0; i < 13; i++) sum += (i % 2 === 0 ? 1 : 3) * (c.charCodeAt(i) - 48);\n    return sum % 10 === 0;\n  }\n  return false;\n}\n\n"

registerSkill({
  id: "is-isbn",
  summary: "isISBN validates whether a string is a valid ISBN-10 or ISBN-13 book number, ignoring hyphens and spaces.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisISBN\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bISBN\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bbook\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bvalid\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isISBN.ts", content: IMPL }]
  },
})
