// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isMacAddress validates a 6-octet MAC address using consistent colon or hyphen separators between hex pairs.\nexport function isMacAddress(s: string): boolean {\n  return /^([0-9a-f]{2}:){5}[0-9a-f]{2}$/i.test(s) || /^([0-9a-f]{2}-){5}[0-9a-f]{2}$/i.test(s);\n}\n\n"

registerSkill({
  id: "is-mac-address",
  summary: "isMacAddress validates a 6-octet MAC address using consistent colon or hyphen separators between hex pairs.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisMacAddress\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bMAC address\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\boctet\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bhex\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isMacAddress.ts", content: IMPL }]
  },
})
