// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Check whether a string is a palindrome (ignoring case and non-alphanumeric).\nexport function isPalindrome(str: string): boolean {\n  const clean = str.toLowerCase().replace(/[^a-z0-9]/g, '')\n  return clean === clean.split('').reverse().join('')\n}\n"

registerSkill({
  id: "is-palindrome",
  summary: "Check whether a string is a palindrome (ignoring case and non-alphanumeric).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpalindrome\\b", 'i'))) sc += 0.8
  if (s.has(new RegExp("\\bisPalindrome\\b", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isPalindrome.ts", content: IMPL }]
  },
})
