// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isUUIDv4Strict validates a string as a strict RFC 4122 version 4 UUID with correct version and variant nibbles.\nexport function isUUIDv4Strict(s: string): boolean {\n  return /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s);\n}\n\n"

registerSkill({
  id: "is-uuid-v4-strict",
  summary: "isUUIDv4Strict validates a string as a strict RFC 4122 version 4 UUID with correct version and variant nibbles.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisUUIDv4Strict\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bUUID\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bversion 4\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bvariant\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isUUIDv4Strict.ts", content: IMPL }]
  },
})
