// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — knapsack01 returns the maximum value for the 0/1 knapsack problem given weights, values, and a capacity.\nexport function knapsack01(weights: number[], values: number[], capacity: number): number {\n  const dp = new Array(capacity + 1).fill(0)\n  for (let i = 0; i < weights.length; i++)\n    for (let c = capacity; c >= weights[i]; c--)\n      dp[c] = Math.max(dp[c], dp[c - weights[i]] + values[i])\n  return dp[capacity]\n}\n"

registerSkill({
  id: "knapsack-01",
  summary: "knapsack01 returns the maximum value for the 0/1 knapsack problem given weights, values, and a capacity.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bknapsack01\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("knapsack", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/knapsack01.ts", content: IMPL }]
  },
})
