// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — kruskalMstWeight returns the total weight of the minimum spanning forest using Kruskal.\nexport function kruskalMstWeight(n, edges) {\n  const sorted = [...edges].sort((a, b) => a[2] - b[2])\n  const parent = Array.from({ length: n }, (_, i) => i)\n  const find = (x) => { while (parent[x] !== x) { parent[x] = parent[parent[x]]; x = parent[x] } return x }\n  let total = 0\n  for (const [u, v, w] of sorted) {\n    const ru = find(u), rv = find(v)\n    if (ru !== rv) { parent[ru] = rv; total += w }\n  }\n  return total\n}\n"

registerSkill({
  id: "kruskal-mst-weight",
  summary: "kruskalMstWeight returns the total weight of the minimum spanning forest using Kruskal.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bkruskalMstWeight\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("kruskal|minimum spanning", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/kruskalMstWeight.ts", content: IMPL }]
  },
})
