// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — longestCommonPrefixStrs returns the longest common prefix shared by an array of strings.\nexport function longestCommonPrefixStrs(strs: string[]): string {\n  if (!strs.length) return ''\n  let prefix = strs[0]\n  for (let i = 1; i < strs.length; i++) {\n    while (!strs[i].startsWith(prefix)) {\n      prefix = prefix.slice(0, -1)\n      if (!prefix) return ''\n    }\n  }\n  return prefix\n}\n"

registerSkill({
  id: "longest-common-prefix-strs",
  summary: "longestCommonPrefixStrs returns the longest common prefix shared by an array of strings.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\blongestCommonPrefixStrs\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("longest common prefix", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/longestCommonPrefixStrs.ts", content: IMPL }]
  },
})
