// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Simple LRU cache with get, set, and max capacity eviction.\nexport class LRUCache<K, V> {\n  private map = new Map<K, V>()\n\n  constructor(private capacity: number) {}\n\n  get(key: K): V | undefined {\n    if (!this.map.has(key)) return undefined\n    const val = this.map.get(key)!\n    this.map.delete(key)\n    this.map.set(key, val)\n    return val\n  }\n\n  set(key: K, value: V): void {\n    if (this.map.has(key)) this.map.delete(key)\n    else if (this.map.size >= this.capacity) {\n      this.map.delete(this.map.keys().next().value!)\n    }\n    this.map.set(key, value)\n  }\n\n  has(key: K): boolean { return this.map.has(key) }\n  size(): number { return this.map.size }\n  clear(): void { this.map.clear() }\n}\n"

registerSkill({
  id: "lru-cache-simple",
  summary: "Simple LRU cache with get, set, and max capacity eviction.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\blru\\b.*cache|cache.*\\blru\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bLRUCache\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bleast.*recently.*used", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bevict.*oldest|capacity.*cache", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/lruCacheSimple.ts", content: IMPL }]
  },
})
