// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Measure sync and async execution time in milliseconds.\nexport function measureTime<T>(fn: () => T): { result: T; ms: number } {\n  const start = performance.now()\n  const result = fn()\n  return { result, ms: performance.now() - start }\n}\n\nexport async function measureTimeAsync<T>(fn: () => Promise<T>): Promise<{ result: T; ms: number }> {\n  const start = performance.now()\n  const result = await fn()\n  return { result, ms: performance.now() - start }\n}\n"

registerSkill({
  id: "measure-time",
  summary: "Measure sync and async execution time in milliseconds.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmeasure.*time|time.*execut", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bmeasureTime\\b|\\bbenchmark\\b.*function", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bexecution.*time|elapsed.*time", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/measureTime.ts", content: IMPL }]
  },
})
