// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Modular multiplicative inverse of a modulo m in range zero to m or null when none exists via modInverse.\nfunction egcd(a: number, b: number): [number, number, number] {\n  let oldR = a, r = b;\n  let oldS = 1, s = 0;\n  let oldT = 0, t = 1;\n  while (r !== 0) {\n    const q = Math.floor(oldR / r);\n    [oldR, r] = [r, oldR - q * r];\n    [oldS, s] = [s, oldS - q * s];\n    [oldT, t] = [t, oldT - q * t];\n  }\n  if (oldR < 0) return [-oldR, -oldS, -oldT];\n  return [oldR, oldS, oldT];\n}\n\nexport function modInverse(a: number, m: number): number | null {\n  if (m <= 0) return null;\n  const [g, x] = egcd(((a % m) + m) % m, m);\n  if (g !== 1) return null;\n  return ((x % m) + m) % m;\n}\n\n"

registerSkill({
  id: "mod-inverse",
  summary: "Modular multiplicative inverse of a modulo m in range zero to m or null when none exists via modInverse.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmodInverse\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bmodular\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\binverse\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bmodulo\\b", 'i'))) sc += 0.15
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/modInverse.ts", content: IMPL }]
  },
})
