// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — MultiMap: map one key to multiple values, with add, get, delete, has.\nexport class MultiMap<K, V> {\n  private map = new Map<K, V[]>()\n\n  add(key: K, value: V): this { const arr = this.map.get(key) ?? []; arr.push(value); this.map.set(key, arr); return this }\n  get(key: K): V[] { return this.map.get(key) ?? [] }\n  has(key: K): boolean { return this.map.has(key) }\n  delete(key: K): boolean { return this.map.delete(key) }\n  deleteEntry(key: K, value: V): boolean {\n    const arr = this.map.get(key); if (!arr) return false\n    const i = arr.indexOf(value); if (i < 0) return false\n    arr.splice(i, 1); if (!arr.length) this.map.delete(key); return true\n  }\n  keys(): K[] { return [...this.map.keys()] }\n  size(): number { return this.map.size }\n  totalSize(): number { return [...this.map.values()].reduce((n, a) => n + a.length, 0) }\n  clear(): void { this.map.clear() }\n  toObject(): Record<string, V[]> {\n    const out: Record<string, V[]> = {}\n    for (const [k, v] of this.map) out[String(k)] = v\n    return out\n  }\n}\n"

registerSkill({
  id: "multimap",
  summary: "MultiMap: map one key to multiple values, with add, get, delete, has.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmultimap\\b|\\bMultiMap\\b", 'i'))) sc += 0.75
  if (s.has(new RegExp("\\bone.*key.*multiple.*value|map.*multiple.*value", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bgroup.*map|map.*array.*value", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/multimap.ts", content: IMPL }]
  },
})
