// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — negate returns the logical complement of a predicate function.\nexport function negate<A extends any[]>(pred: (...args: A) => boolean): (...args: A) => boolean {\n  return (...args: A) => !pred(...args)\n}\n"

registerSkill({
  id: "negate-predicate",
  summary: "negate returns the logical complement of a predicate function.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bnegate\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("complement.*predicate|negate.*function", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/negatePredicate.ts", content: IMPL }]
  },
})
