// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Compute added, removed, and changed keys between two plain objects.\nexport interface DiffResult {\n  added: Record<string, unknown>\n  removed: Record<string, unknown>\n  changed: Record<string, { from: unknown; to: unknown }>\n}\n\nexport function objectDiff(from: Record<string, unknown>, to: Record<string, unknown>): DiffResult {\n  const added: Record<string, unknown> = {}\n  const removed: Record<string, unknown> = {}\n  const changed: Record<string, { from: unknown; to: unknown }> = {}\n  const eq = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b)\n  for (const k of Object.keys(to)) {\n    if (!(k in from)) added[k] = to[k]\n    else if (!eq(from[k], to[k])) changed[k] = { from: from[k], to: to[k] }\n  }\n  for (const k of Object.keys(from)) { if (!(k in to)) removed[k] = from[k] }\n  return { added, removed, changed }\n}\n"

registerSkill({
  id: "object-diff",
  summary: "Compute added, removed, and changed keys between two plain objects.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bobject.*diff|diff.*object", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bobjectDiff\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bcompare.*object|object.*compare.*change", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/objectDiff.ts", content: IMPL }]
  },
})
