// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — get, set, has, unset by dot-notation path on nested objects.\nfunction parsePath(path: string): string[] {\n  return path.split('.').flatMap(p => p.replace(/\\[(\\d+)\\]/g, '.$1').split('.')).filter(Boolean)\n}\n\nexport function getPath(obj: unknown, path: string, defaultVal?: unknown): unknown {\n  const keys = parsePath(path)\n  let cur: unknown = obj\n  for (const k of keys) {\n    if (cur === null || cur === undefined || typeof cur !== 'object') return defaultVal\n    cur = (cur as Record<string, unknown>)[k]\n  }\n  return cur === undefined ? defaultVal : cur\n}\n\nexport function setPath(obj: Record<string, unknown>, path: string, value: unknown): void {\n  const keys = parsePath(path)\n  let cur = obj as Record<string, unknown>\n  for (let i = 0; i < keys.length - 1; i++) {\n    const k = keys[i]\n    if (cur[k] === null || cur[k] === undefined || typeof cur[k] !== 'object') {\n      cur[k] = isNaN(Number(keys[i + 1])) ? {} : []\n    }\n    cur = cur[k] as Record<string, unknown>\n  }\n  cur[keys[keys.length - 1]] = value\n}\n\nexport function hasPath(obj: unknown, path: string): boolean {\n  const keys = parsePath(path)\n  let cur: unknown = obj\n  for (const k of keys) {\n    if (cur === null || cur === undefined || typeof cur !== 'object') return false\n    if (!Object.prototype.hasOwnProperty.call(cur, k)) return false\n    cur = (cur as Record<string, unknown>)[k]\n  }\n  return true\n}\n\nexport function unsetPath(obj: Record<string, unknown>, path: string): void {\n  const keys = parsePath(path)\n  let cur = obj as Record<string, unknown>\n  for (let i = 0; i < keys.length - 1; i++) {\n    cur = (cur[keys[i]] ?? {}) as Record<string, unknown>\n  }\n  delete cur[keys[keys.length - 1]]\n}\n"

registerSkill({
  id: "object-path",
  summary: "get, set, has, unset by dot-notation path on nested objects.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bget.*nested|nested.*path|dot.*notation.*object", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bgetPath\\b|\\bsetPath\\b|\\bhasPath\\b", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\blodash.*get|_\\.get|object.*path.*access", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bpath.*object.*access|dot.*path.*value", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/objectPath.ts", content: IMPL }]
  },
})
