// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Observable value with subscribe, next, complete; basic reactive state.\nexport interface Observer<T> { next: (val: T) => void; error?: (err: unknown) => void; complete?: () => void }\nexport interface Subscription { unsubscribe(): void }\n\nexport class Observable<T> {\n  constructor(private _subscribe: (obs: Observer<T>) => void | (() => void)) {}\n\n  subscribe(observer: Observer<T> | ((val: T) => void)): Subscription {\n    const obs: Observer<T> = typeof observer === 'function' ? { next: observer } : observer\n    let cleanup: void | (() => void)\n    let done = false\n    cleanup = this._subscribe({\n      next: v => { if (!done) obs.next(v) },\n      error: e => { if (!done) { done = true; obs.error?.(e) } },\n      complete: () => { if (!done) { done = true; obs.complete?.() } },\n    })\n    return { unsubscribe: () => { done = true; (cleanup as (() => void)| void)?.() } }\n  }\n\n  static of<T>(...values: T[]): Observable<T> {\n    return new Observable(obs => { values.forEach(v => obs.next(v)); obs.complete?.() })\n  }\n\n  map<U>(fn: (v: T) => U): Observable<U> {\n    return new Observable(obs => this.subscribe({ next: v => obs.next(fn(v)), error: obs.error, complete: obs.complete }))\n  }\n\n  filter(fn: (v: T) => boolean): Observable<T> {\n    return new Observable(obs => this.subscribe({ next: v => fn(v) && obs.next(v), error: obs.error, complete: obs.complete }))\n  }\n}\n\nexport class Subject<T> extends Observable<T> {\n  private observers: Observer<T>[] = []\n\n  constructor() {\n    super(obs => { this.observers.push(obs) })\n  }\n\n  next(value: T): void { this.observers.forEach(o => o.next(value)) }\n  complete(): void { this.observers.forEach(o => o.complete?.()) }\n  error(err: unknown): void { this.observers.forEach(o => o.error?.(err)) }\n}\n"

registerSkill({
  id: "observable",
  summary: "Observable value with subscribe, next, complete; basic reactive state.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bobservable\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bSubject\\b.*observable|reactive.*state", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bsubscribe\\b.*\\bnext\\b|observer.*pattern.*reactive", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/observable.ts", content: IMPL }]
  },
})
