// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Option is a Maybe type with static some and none, plus map, getOrElse, isSome, and isNone.\nexport class Option<T> {\n  private constructor(private val: T | null, private present: boolean) {}\n  static some<T>(v: T): Option<T> { return new Option(v, true) }\n  static none<T>(): Option<T> { return new Option<T>(null, false) }\n  map<U>(fn: (v: T) => U): Option<U> { return this.present ? Option.some(fn(this.val as T)) : Option.none<U>() }\n  getOrElse(def: T): T { return this.present ? (this.val as T) : def }\n  isSome(): boolean { return this.present }\n  isNone(): boolean { return !this.present }\n}\n"

registerSkill({
  id: "option-monad",
  summary: "Option is a Maybe type with static some and none, plus map, getOrElse, isSome, and isNone.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bOption\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("maybe.*type|option.*monad|some.*none", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/optionMonad.ts", content: IMPL }]
  },
})
