// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — ordinalWord returns \"first\" through \"tenth\" for 1-10 and the ordinal suffix form like \"11th\" or \"21st\" for other integers.\nconst WORDS = ['','first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth']\nexport function ordinalWord(n: number): string {\n  if (n >= 1 && n <= 10) return WORDS[n]\n  const abs = Math.abs(n), mod10 = abs % 10, mod100 = abs % 100\n  const suffix = mod100 >= 11 && mod100 <= 13 ? 'th' : mod10 === 1 ? 'st' : mod10 === 2 ? 'nd' : mod10 === 3 ? 'rd' : 'th'\n  return n + suffix\n}\n"

registerSkill({
  id: "ordinal-word",
  summary: "ordinalWord returns \"first\" through \"tenth\" for 1-10 and the ordinal suffix form like \"11th\" or \"21st\" for other integers.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bordinalWord\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("ordinal.*word|number.*word.*first", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/ordinalWord.ts", content: IMPL }]
  },
})
