// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — padColumns pads each column to its maximum width and joins cells with a single space per row.\nexport function padColumns(rows: string[][]): string[] {\n  if (!rows.length) return []\n  const cols = rows[0].length\n  const widths = Array.from({length: cols}, (_,c) => Math.max(...rows.map(r=>(r[c]??'').length)))\n  return rows.map(r => r.map((cell,c) => cell.padEnd(widths[c])).join(' ').trimEnd())\n}\n"

registerSkill({
  id: "pad-columns",
  summary: "padColumns pads each column to its maximum width and joins cells with a single space per row.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpadColumns\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("pad.*column|column.*align", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/padColumns.ts", content: IMPL }]
  },
})
