// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — safeParseInt, safeParseFloat, toFixed, toPrecision with fallback.\nexport function safeParseInt(s: string, fallback = 0, radix = 10): number {\n  const n = parseInt(s, radix)\n  return isNaN(n) ? fallback : n\n}\n\nexport function safeParseFloat(s: string, fallback = 0): number {\n  const n = parseFloat(s)\n  return isNaN(n) ? fallback : n\n}\n\nexport function toFixed(n: number, decimals: number): number {\n  return parseFloat(n.toFixed(decimals))\n}\n\nexport function inRange(n: number, min: number, max: number, inclusive = true): boolean {\n  return inclusive ? n >= min && n <= max : n > min && n < max\n}\n"

registerSkill({
  id: "parse-number",
  summary: "safeParseInt, safeParseFloat, toFixed, toPrecision with fallback.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsafeParseInt\\b|\\bsafe.*parse.*int", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsafeParseFloat\\b|\\bsafe.*parse.*float", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bparse.*number.*safe|safe.*number.*parse", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\binRange\\b|\\bnumber.*range.*check", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/parseNumber.ts", content: IMPL }]
  },
})
