// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — parseQueryParams parses a URL query string (optional leading ?) into URL-decoded key-value pairs.\nexport function parseQueryParams(qs) {\n  const out = {}\n  const clean = qs.startsWith('?') ? qs.slice(1) : qs\n  if (!clean) return out\n  for (const part of clean.split('&')) {\n    const eq = part.indexOf('=')\n    if (eq < 0) continue\n    const k = decodeURIComponent(part.slice(0,eq))\n    const v = decodeURIComponent(part.slice(eq+1))\n    out[k] = v\n  }\n  return out\n}\n"

registerSkill({
  id: "parse-query-params",
  summary: "parseQueryParams parses a URL query string (optional leading ?) into URL-decoded key-value pairs.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bparseQueryParams\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("URL-decoded.*key.?value|query.?string.*URL-decoded", 'i'))) sc += 0.7
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/parseQueryParams.ts", content: IMPL }]
  },
})
