// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — percentEncode applies RFC3986 percent encoding to a string and percentDecode reverses it; they roundtrip.\nexport function percentEncode(s: string): string {\n  return encodeURIComponent(s).replace(/[!'()*]/g, c => '%' + c.charCodeAt(0).toString(16).toUpperCase())\n}\nexport function percentDecode(s: string): string {\n  return decodeURIComponent(s)\n}\n"

registerSkill({
  id: "percent-encode",
  summary: "percentEncode applies RFC3986 percent encoding to a string and percentDecode reverses it; they roundtrip.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpercentEncode\\b|\\bpercentDecode\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("percent.*encod|url.*encod", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/percentEncode.ts", content: IMPL }]
  },
})
