// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Calculate percentage, percentage change, and percentage of total.\nexport function percent(value: number, total: number): number {\n  if (total === 0) return 0\n  return (value / total) * 100\n}\n\nexport function percentChange(from: number, to: number): number {\n  if (from === 0) return to === 0 ? 0 : Infinity\n  return ((to - from) / Math.abs(from)) * 100\n}\n\nexport function percentOf(pct: number, total: number): number {\n  return (pct / 100) * total\n}\n"

registerSkill({
  id: "percent",
  summary: "Calculate percentage, percentage change, and percentage of total.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpercent\\b|\\bpercentage\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bpercentChange\\b|\\bpercentOf\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bpercent.*change|change.*percent", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/percent.ts", content: IMPL }]
  },
})
