// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Prime factorization returning prime factors with multiplicity in ascending order via primeFactorize.\nexport function primeFactorize(n: number): number[] {\n  if (n < 2) return [];\n  const factors: number[] = [];\n  let m = n;\n  for (let d = 2; d * d <= m; d++) {\n    while (m % d === 0) {\n      factors.push(d);\n      m = Math.floor(m / d);\n    }\n  }\n  if (m > 1) factors.push(m);\n  return factors;\n}\n\n"

registerSkill({
  id: "prime-factorize",
  summary: "Prime factorization returning prime factors with multiplicity in ascending order via primeFactorize.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bprimeFactorize\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bprime\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bfactor", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bmultiplicity\\b", 'i'))) sc += 0.2
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/primeFactorize.ts", content: IMPL }]
  },
})
