// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — primMstWeight returns the MST weight via Prim starting from node 0.\nexport function primMstWeight(n, edges) {\n  const adj = Array.from({ length: n }, () => [])\n  for (const [u, v, w] of edges) { adj[u].push([v, w]); adj[v].push([u, w]) }\n  const inMST = new Array(n).fill(false)\n  const key = new Array(n).fill(Infinity); key[0] = 0\n  let total = 0\n  for (let iter = 0; iter < n; iter++) {\n    let u = -1\n    for (let i = 0; i < n; i++) if (!inMST[i] && (u < 0 || key[i] < key[u])) u = i\n    if (u < 0 || key[u] === Infinity) break\n    inMST[u] = true; total += key[u]\n    for (const [v, w] of adj[u]) if (!inMST[v] && w < key[v]) key[v] = w\n  }\n  return total\n}\n"

registerSkill({
  id: "prim-mst-weight",
  summary: "primMstWeight returns the MST weight via Prim starting from node 0.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bprimMstWeight\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("prim'?s.*algorithm|prim.*spanning", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/primMstWeight.ts", content: IMPL }]
  },
})
