// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — withTimeout, pMap (parallel map), pFilter, pReduce.\nexport function withTimeout<T>(promise: Promise<T>, ms: number, message = 'Timeout'): Promise<T> {\n  return Promise.race([\n    promise,\n    new Promise<never>((_, reject) => setTimeout(() => reject(new Error(message)), ms)),\n  ])\n}\n\nexport async function pMap<T, U>(\n  arr: T[],\n  fn: (item: T, index: number) => Promise<U>,\n  concurrency = Infinity,\n): Promise<U[]> {\n  const results: U[] = new Array(arr.length)\n  let idx = 0\n  const worker = async () => {\n    while (idx < arr.length) {\n      const i = idx++\n      results[i] = await fn(arr[i], i)\n    }\n  }\n  const workers = Array.from({ length: Math.min(concurrency, arr.length || 1) }, worker)\n  await Promise.all(workers)\n  return results\n}\n\nexport async function pFilter<T>(\n  arr: T[],\n  fn: (item: T, index: number) => Promise<boolean>,\n): Promise<T[]> {\n  const flags = await pMap(arr, fn)\n  return arr.filter((_, i) => flags[i])\n}\n"

registerSkill({
  id: "promise-utils",
  summary: "withTimeout, pMap (parallel map), pFilter, pReduce.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bwithTimeout\\b|\\bpromise.*timeout|timeout.*promise", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bpMap\\b|\\bparallel.*map|map.*async.*concurrent", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bpFilter\\b|\\bpromise.*util", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/promiseUtils.ts", content: IMPL }]
  },
})
