// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Parse and stringify URL query strings.\nexport function parseQueryString(qs: string): Record<string, string> {\n  const out: Record<string, string> = {}\n  const str = qs.startsWith('?') ? qs.slice(1) : qs\n  if (!str) return out\n  for (const part of str.split('&')) {\n    const eq = part.indexOf('=')\n    if (eq === -1) { out[decodeURIComponent(part)] = ''; continue }\n    out[decodeURIComponent(part.slice(0, eq))] = decodeURIComponent(part.slice(eq + 1))\n  }\n  return out\n}\n\nexport function stringifyQueryString(params: Record<string, string>): string {\n  return Object.entries(params)\n    .map(([k, v]) => v === '' ? encodeURIComponent(k) : `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)\n    .join('&')\n}\n"

registerSkill({
  id: "query-string",
  summary: "Parse and stringify URL query strings.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bquery.*string|querystring\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bparse.*query|stringify.*query", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\burl.*param|search.*param", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/queryString.ts", content: IMPL }]
  },
})
