// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — ROT13 substitution cipher — encode and decode (same operation).\nexport function rot13(str: string): string {\n  return str.replace(/[a-zA-Z]/g, c => {\n    const base = c <= 'Z' ? 65 : 97\n    return String.fromCharCode(((c.charCodeAt(0) - base + 13) % 26) + base)\n  })\n}\n"

registerSkill({
  id: "rot13",
  summary: "ROT13 substitution cipher — encode and decode (same operation).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brot13\\b|\\brot-13\\b", 'i'))) sc += 0.85
  if (s.has(new RegExp("\\bcaesar.*cipher|substitution.*cipher", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/rot13.ts", content: IMPL }]
  },
})
