// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Rotate a 2D point around a center by an angle in degrees counterclockwise using rotatePointDeg, rounding each coordinate to 6 decimals.\nexport function rotatePointDeg(x: number, y: number, cx: number, cy: number, deg: number): [number, number] {\n  const rad = (deg * Math.PI) / 180;\n  const cos = Math.cos(rad);\n  const sin = Math.sin(rad);\n  const dx = x - cx;\n  const dy = y - cy;\n  const nx = cx + dx * cos - dy * sin;\n  const ny = cy + dx * sin + dy * cos;\n  const round = (v: number) => Math.round(v * 1e6) / 1e6;\n  return [round(nx), round(ny)];\n}\n\n"

registerSkill({
  id: "rotate-point-degrees",
  summary: "Rotate a 2D point around a center by an angle in degrees counterclockwise using rotatePointDeg, rounding each coordinate to 6 decimals.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brotatePointDeg\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\brotate\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("degrees", 'i'))) sc += 0.15
  if (s.has(new RegExp("counterclockwise", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/rotatePointDeg.ts", content: IMPL }]
  },
})
