// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — runLengthEncode and runLengthDecode perform run-length encoding of a string, like aaabb to 3a2b; decode reverses it.\nexport function runLengthEncode(s: string): string {\n  let out = '', i = 0\n  while (i < s.length) {\n    let j = i\n    while (j < s.length && s[j] === s[i]) j++\n    out += (j - i) + s[i]\n    i = j\n  }\n  return out\n}\n\nexport function runLengthDecode(s: string): string {\n  let out = ''\n  const re = /(\\d+)(\\D)/g\n  let m: RegExpExecArray | null\n  while ((m = re.exec(s)) !== null) out += m[2].repeat(Number(m[1]))\n  return out\n}\n"

registerSkill({
  id: "run-length-coding",
  summary: "runLengthEncode and runLengthDecode perform run-length encoding of a string, like aaabb to 3a2b; decode reverses it.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brunLengthEncode\\b|\\brunLengthDecode\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("run.?length", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/runLengthCoding.ts", content: IMPL }]
  },
})
