// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Linear search, interpolation search, exponential search for sorted arrays.\nexport function linearSearch<T>(arr: T[], target: T): number {\n  for (let i = 0; i < arr.length; i++) if (arr[i] === target) return i\n  return -1\n}\n\nexport function interpolationSearch(arr: number[], target: number): number {\n  let lo = 0, hi = arr.length - 1\n  while (lo <= hi && target >= arr[lo] && target <= arr[hi]) {\n    if (lo === hi) return arr[lo] === target ? lo : -1\n    const pos = lo + Math.floor((target - arr[lo]) * (hi - lo) / (arr[hi] - arr[lo]))\n    if (arr[pos] === target) return pos\n    if (arr[pos] < target) lo = pos + 1; else hi = pos - 1\n  }\n  return -1\n}\n\nexport function exponentialSearch(arr: number[], target: number): number {\n  if (!arr.length) return -1\n  if (arr[0] === target) return 0\n  let i = 1\n  while (i < arr.length && arr[i] <= target) i *= 2\n  let lo = i >> 1, hi = Math.min(i, arr.length - 1)\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1\n    if (arr[mid] === target) return mid\n    if (arr[mid] < target) lo = mid + 1; else hi = mid - 1\n  }\n  return -1\n}\n"

registerSkill({
  id: "search-utils",
  summary: "Linear search, interpolation search, exponential search for sorted arrays.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\blinear.*search|search.*linear", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\binterpolation.*search", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bexponential.*search", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsearch.*algorithm.*sorted", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/searchUtils.ts", content: IMPL }]
  },
})
