// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — semverSatisfies reports whether a version string fulfills a constraint expressed with exact, caret, tilde, or >= operators.\nfunction parseVer(v: string): [number, number, number] | null {\n  const m = /^(\\d+)\\.(\\d+)\\.(\\d+)$/.exec(v.trim());\n  if (!m) return null;\n  return [Number(m[1]), Number(m[2]), Number(m[3])];\n}\n\nfunction cmp(a: [number, number, number], b: [number, number, number]): number {\n  for (let i = 0; i < 3; i++) {\n    if (a[i] !== b[i]) return a[i] < b[i] ? -1 : 1;\n  }\n  return 0;\n}\n\nexport function semverSatisfies(version: string, range: string): boolean {\n  const v = parseVer(version);\n  if (!v) return false;\n  const r = range.trim();\n  if (r.startsWith('^')) {\n    const b = parseVer(r.slice(1));\n    if (!b) return false;\n    if (cmp(v, b) < 0) return false;\n    if (b[0] > 0) return v[0] === b[0];\n    if (b[1] > 0) return v[0] === 0 && v[1] === b[1];\n    return v[0] === 0 && v[1] === 0 && v[2] === b[2];\n  }\n  if (r.startsWith('~')) {\n    const b = parseVer(r.slice(1));\n    if (!b) return false;\n    if (cmp(v, b) < 0) return false;\n    return v[0] === b[0] && v[1] === b[1];\n  }\n  if (r.startsWith('>=')) {\n    const b = parseVer(r.slice(2));\n    if (!b) return false;\n    return cmp(v, b) >= 0;\n  }\n  const b = parseVer(r);\n  if (!b) return false;\n  return cmp(v, b) === 0;\n}\n\n"

registerSkill({
  id: "semver-satisfies",
  summary: "semverSatisfies reports whether a version string fulfills a constraint expressed with exact, caret, tilde, or >= operators.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsemverSatisfies\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsatisf", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bconstraint\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bversion\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/semverSatisfies.ts", content: IMPL }]
  },
})
