// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Fisher-Yates shuffle and random sample from an array.\nexport function shuffle<T>(arr: T[], rng: () => number = Math.random): T[] {\n  const out = [...arr]\n  for (let i = out.length - 1; i > 0; i--) {\n    const j = Math.floor(rng() * (i + 1));\n    [out[i], out[j]] = [out[j], out[i]]\n  }\n  return out\n}\n\nexport function sample<T>(arr: T[], rng: () => number = Math.random): T | undefined {\n  if (!arr.length) return undefined\n  return arr[Math.floor(rng() * arr.length)]\n}\n"

registerSkill({
  id: "shuffle",
  summary: "Fisher-Yates shuffle and random sample from an array.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bshuffle\\b.*array|array.*\\bshuffle\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bfisher.*yates\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bsample\\b.*array|random.*element", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/shuffle.ts", content: IMPL }]
  },
})
