// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Reactive signal: computed values, effects, and automatic dependency tracking.\ntype Cleanup = () => void\n\nlet currentEffect: (() => void) | null = null\n\nexport class Signal<T> {\n  private _value: T\n  private subscribers = new Set<() => void>()\n\n  constructor(initial: T) { this._value = initial }\n\n  get(): T {\n    if (currentEffect) this.subscribers.add(currentEffect)\n    return this._value\n  }\n\n  set(val: T): void {\n    if (val === this._value) return\n    this._value = val\n    for (const sub of [...this.subscribers]) sub()\n  }\n\n  update(fn: (v: T) => T): void { this.set(fn(this._value)) }\n}\n\nexport function signal<T>(initial: T): Signal<T> { return new Signal(initial) }\n\nexport function computed<T>(fn: () => T): { get(): T } {\n  const s = new Signal(fn())\n  effect(() => s.set(fn()))\n  return { get: () => s.get() }\n}\n\nexport function effect(fn: () => void): Cleanup {\n  const run = () => { currentEffect = run; fn(); currentEffect = null }\n  run()\n  return () => { /* cleanup: signal subscribers are weak */ }\n}\n"

registerSkill({
  id: "signal",
  summary: "Reactive signal: computed values, effects, and automatic dependency tracking.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsignal\\b.*reactive|reactive.*\\bsignal\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bcomputed\\b.*signal|\\beffect\\b.*signal", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsignal\\(|\\bcomputed\\(|\\beffect\\(", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/signal.ts", content: IMPL }]
  },
})
