// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Async sleep for N milliseconds; setTimeout-based delay.\nexport function sleep(ms: number): Promise<void> {\n  return new Promise(resolve => setTimeout(resolve, ms))\n}\n"

registerSkill({
  id: "sleep",
  summary: "Async sleep for N milliseconds; setTimeout-based delay.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsleep\\b.*ms|async.*sleep", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bdelay\\b.*promise|promise.*delay", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bwait.*millisecond|setTimeout.*promise", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/sleep.ts", content: IMPL }]
  },
})
