// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Sliding window, windowed iteration, rolling average over an array.\nexport function windows<T>(arr: T[], size: number): T[][] {\n  if (size <= 0 || size > arr.length) return []\n  return arr.slice(0, arr.length - size + 1).map((_, i) => arr.slice(i, i + size))\n}\n\nexport function rollingAverage(arr: number[], size: number): number[] {\n  return windows(arr, size).map(w => w.reduce((a, b) => a + b, 0) / size)\n}\n\nexport function maxWindow(arr: number[], size: number): number[] {\n  return windows(arr, size).map(w => Math.max(...w))\n}\n"

registerSkill({
  id: "sliding-window",
  summary: "Sliding window, windowed iteration, rolling average over an array.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsliding.*window|window.*slide", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\brolling.*average|rolling.*mean", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bwindows\\b.*array|\\bwindowed\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bwindow.*size.*array", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/slidingWindow.ts", content: IMPL }]
  },
})
