// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — sortedInsert inserts a value into a sorted ascending array via binary search, returning a new sorted array.\nexport function sortedInsert(arr: number[], val: number): number[] {\n  let lo = 0, hi = arr.length\n  while (lo < hi) { const mid = (lo + hi) >> 1; arr[mid] < val ? lo = mid + 1 : hi = mid }\n  return [...arr.slice(0, lo), val, ...arr.slice(lo)]\n}\n"

registerSkill({
  id: "sorted-insert",
  summary: "sortedInsert inserts a value into a sorted ascending array via binary search, returning a new sorted array.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsortedInsert\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("insert.*sorted.*ascending|binary.*insert.*sorted", 'i'))) sc += 0.6
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/sortedInsertNum.ts", content: IMPL }]
  },
})
