// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — stripAnsiCodes removes ANSI escape color and style codes from a string.\nexport function stripAnsiCodes(s) {\n  return s.replace(/\\x1B\\[[0-9;]*[mGKHFA-Z]/g, '')\n}\n"

registerSkill({
  id: "strip-ansi-codes",
  summary: "stripAnsiCodes removes ANSI escape color and style codes from a string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bstripAnsiCodes\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("strip.*ansi|remove.*ansi|ansi.*escape", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/stripAnsiCodes.ts", content: IMPL }]
  },
})
