// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Fuzzy string match score and Levenshtein edit distance.\nexport function editDistance(a: string, b: string): number {\n  const m = a.length, n = b.length\n  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>\n    Array.from({ length: n + 1 }, (_, j) => i === 0 ? j : j === 0 ? i : 0))\n  for (let i = 1; i <= m; i++)\n    for (let j = 1; j <= n; j++)\n      dp[i][j] = a[i-1] === b[j-1] ? dp[i-1][j-1]\n        : 1 + Math.min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n  return dp[m][n]\n}\n\nexport function fuzzyScore(pattern: string, text: string): number {\n  if (!pattern) return 1\n  if (!text) return 0\n  const p = pattern.toLowerCase(), t = text.toLowerCase()\n  let score = 0, pi = 0, consecutive = 0\n  for (let ti = 0; ti < t.length && pi < p.length; ti++) {\n    if (t[ti] === p[pi]) {\n      score += 1 + consecutive\n      consecutive++\n      pi++\n    } else consecutive = 0\n  }\n  return pi === p.length ? score / (text.length + pattern.length) : 0\n}\n"

registerSkill({
  id: "string-search",
  summary: "Fuzzy string match score and Levenshtein edit distance.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bedit.*distance|levenshtein\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bfuzzy.*match|fuzzy.*search|fuzzy.*score", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bfuzzyScore\\b|\\beditDistance\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/stringSearch.ts", content: IMPL }]
  },
})
