// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Sum, min, max, sort array by a key function.\nexport function sumBy<T>(arr: T[], key: (item: T) => number): number {\n  return arr.reduce((acc, item) => acc + key(item), 0)\n}\n\nexport function minBy<T>(arr: T[], key: (item: T) => number): T | undefined {\n  if (!arr.length) return undefined\n  return arr.reduce((min, item) => key(item) < key(min) ? item : min)\n}\n\nexport function maxBy<T>(arr: T[], key: (item: T) => number): T | undefined {\n  if (!arr.length) return undefined\n  return arr.reduce((max, item) => key(item) > key(max) ? item : max)\n}\n\nexport function sortBy<T>(arr: T[], key: (item: T) => number | string): T[] {\n  return [...arr].sort((a, b) => {\n    const ka = key(a), kb = key(b)\n    return ka < kb ? -1 : ka > kb ? 1 : 0\n  })\n}\n"

registerSkill({
  id: "sum-by",
  summary: "Sum, min, max, sort array by a key function.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsumBy\\b|\\bsum.*by\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bminBy\\b|\\bmaxBy\\b", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\bsortBy\\b|\\bsort.*by.*key", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/sumBy.ts", content: IMPL }]
  },
})
