// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Format an array of objects as an ASCII table string.\nexport function formatTable(rows: Record<string, unknown>[], columns?: string[]): string {\n  if (!rows.length) return ''\n  const cols = columns ?? Object.keys(rows[0])\n  const widths = cols.map(c => Math.max(c.length, ...rows.map(r => String(r[c] ?? '').length)))\n  const pad = (s: string, w: number) => s.padEnd(w)\n  const sep = '+' + widths.map(w => '-'.repeat(w + 2)).join('+') + '+'\n  const row = (cells: string[]) => '|' + cells.map((c, i) => ' ' + pad(c, widths[i]) + ' ').join('|') + '|'\n  return [\n    sep,\n    row(cols),\n    sep,\n    ...rows.map(r => row(cols.map(c => String(r[c] ?? '')))),\n    sep,\n  ].join('\\n')\n}\n"

registerSkill({
  id: "table-format",
  summary: "Format an array of objects as an ASCII table string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btable.*format|format.*table|ascii.*table", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bformatTable\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\barray.*object.*table|tabular.*format", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/tableFormat.ts", content: IMPL }]
  },
})
