// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Prefix trie: insert words, search exact, startsWith prefix.\ninterface TrieNode { children: Map<string, TrieNode>; end: boolean }\n\nexport class Trie {\n  private root: TrieNode = { children: new Map(), end: false }\n\n  insert(word: string): void {\n    let node = this.root\n    for (const ch of word) {\n      if (!node.children.has(ch)) node.children.set(ch, { children: new Map(), end: false })\n      node = node.children.get(ch)!\n    }\n    node.end = true\n  }\n\n  search(word: string): boolean {\n    let node = this.root\n    for (const ch of word) {\n      if (!node.children.has(ch)) return false\n      node = node.children.get(ch)!\n    }\n    return node.end\n  }\n\n  startsWith(prefix: string): boolean {\n    let node = this.root\n    for (const ch of prefix) {\n      if (!node.children.has(ch)) return false\n      node = node.children.get(ch)!\n    }\n    return true\n  }\n\n  words(prefix = ''): string[] {\n    let node = this.root\n    for (const ch of prefix) {\n      if (!node.children.has(ch)) return []\n      node = node.children.get(ch)!\n    }\n    const out: string[] = []\n    const dfs = (n: TrieNode, s: string) => {\n      if (n.end) out.push(s)\n      for (const [ch, child] of n.children) dfs(child, s + ch)\n    }\n    dfs(node, prefix)\n    return out\n  }\n}\n"

registerSkill({
  id: "trie-simple",
  summary: "Prefix trie: insert words, search exact, startsWith prefix.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btrie\\b.*(?:insert|search|prefix)", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bprefix.*tree|prefix.*search", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bTrie\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bautocomplete\\b", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/trieSimple.ts", content: IMPL }]
  },
})
