// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — User-built skill: Create src/lib/slugify.ts\nfunction __raw_slugify(title: string): string {\n  const trimmedTitle = title.trim();\n  const lowercasedTitle = trimmedTitle.toLowerCase();\n  const slugifiedTitle = lowercasedTitle.replace(/[^a-z0-9]/g, '-');\n  return slugifiedTitle.trim();\n}\nexport function slugify(...__args: Parameters<typeof __raw_slugify>): ReturnType<typeof __raw_slugify> {\n  const __r = __raw_slugify(...__args)\n  return (typeof __r === 'string' ? __r.replace(/\\-{2,}/g, \"-\").replace(/^\\-+|\\-+$/g, '') : __r) as ReturnType<typeof __raw_slugify>\n}\n\n"

registerSkill({
  id: "user/slugify",
  summary: "User-built skill: Create src/lib/slugify.ts",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bslugify\\b", 'i'))) sc += 0.9
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/lib/slugify.ts", content: IMPL }]
  },
})
