// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — memoizeAsync, raceTimeout, sequential, waterfall for async tasks.\nexport function memoizeAsync<T extends unknown[], R>(fn: (...args: T) => Promise<R>): (...args: T) => Promise<R> {\n  const cache = new Map<string, Promise<R>>()\n  return (...args: T): Promise<R> => {\n    const key = JSON.stringify(args)\n    if (!cache.has(key)) cache.set(key, fn(...args))\n    return cache.get(key)!\n  }\n}\n\nexport async function sequential<T>(tasks: Array<() => Promise<T>>): Promise<T[]> {\n  const results: T[] = []\n  for (const task of tasks) results.push(await task())\n  return results\n}\n\nexport async function waterfall<T>(\n  input: T,\n  fns: Array<(v: T) => Promise<T>>,\n): Promise<T> {\n  let val = input\n  for (const fn of fns) val = await fn(val)\n  return val\n}\n"

registerSkill({
  id: "async-patterns",
  summary: "memoizeAsync, raceTimeout, sequential, waterfall for async tasks.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmemoize.*async|async.*memoize", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsequential.*async|run.*async.*sequence", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bwaterfall\\b.*async|async.*waterfall", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\basync.*pattern|async.*util.*advanced", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/asyncPatterns.ts", content: IMPL }]
  },
})
