// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — bellmanFordDistances returns shortest distances allowing negative edges, or null when a negative cycle is reachable from the source.\nexport function bellmanFordDistances(n, edges, src) {\n  const dist = new Array(n).fill(Infinity); dist[src] = 0\n  for (let i = 0; i < n - 1; i++)\n    for (const [u, v, w] of edges)\n      if (dist[u] !== Infinity && dist[u] + w < dist[v]) dist[v] = dist[u] + w\n  for (const [u, v, w] of edges)\n    if (dist[u] !== Infinity && dist[u] + w < dist[v]) return null\n  return dist\n}\n"

registerSkill({
  id: "bellman-ford-distances",
  summary: "bellmanFordDistances returns shortest distances allowing negative edges, or null when a negative cycle is reachable from the source.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bbellmanFordDistances\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("bellman.?ford|negative.*cycle", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/bellmanFordDistances.ts", content: IMPL }]
  },
})
