// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — bfsHopCounts returns the shortest hop count from a source in an unweighted graph given adjacency lists; unreachable is -1.\nexport function bfsHopCounts(n, adj, src) {\n  const dist = new Array(n).fill(-1); dist[src] = 0\n  const queue = [src]\n  while (queue.length) {\n    const u = queue.shift()\n    for (const v of adj[u]) if (dist[v] === -1) { dist[v] = dist[u] + 1; queue.push(v) }\n  }\n  return dist\n}\n"

registerSkill({
  id: "bfs-hop-counts",
  summary: "bfsHopCounts returns the shortest hop count from a source in an unweighted graph given adjacency lists; unreachable is -1.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bbfsHopCounts\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("shortest.?hop|hop.?count.*unweighted|adjacency.*hop", 'i'))) sc += 0.6
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/bfsHopCounts.ts", content: IMPL }]
  },
})
