// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Bidirectional map: look up by key or by value in O(1).\nexport class BiMap<K, V> {\n  private fwd = new Map<K, V>()\n  private rev = new Map<V, K>()\n\n  set(key: K, value: V): this {\n    if (this.fwd.has(key)) this.rev.delete(this.fwd.get(key)!)\n    if (this.rev.has(value)) this.fwd.delete(this.rev.get(value)!)\n    this.fwd.set(key, value); this.rev.set(value, key); return this\n  }\n\n  getByKey(key: K): V | undefined { return this.fwd.get(key) }\n  getByValue(value: V): K | undefined { return this.rev.get(value) }\n  hasKey(key: K): boolean { return this.fwd.has(key) }\n  hasValue(value: V): boolean { return this.rev.has(value) }\n  deleteByKey(key: K): boolean {\n    if (!this.fwd.has(key)) return false\n    this.rev.delete(this.fwd.get(key)!); this.fwd.delete(key); return true\n  }\n  size(): number { return this.fwd.size }\n  clear(): void { this.fwd.clear(); this.rev.clear() }\n}\n"

registerSkill({
  id: "bimap",
  summary: "Bidirectional map: look up by key or by value in O(1).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bbimap\\b|\\bBiMap\\b|\\bbidirectional.*map", 'i'))) sc += 0.75
  if (s.has(new RegExp("\\binverse.*map|reverse.*lookup.*map", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bmap.*both.*direction|two.*way.*map", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/bimap.ts", content: IMPL }]
  },
})
