// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Binary search a sorted array; return index or -1.\nexport function binarySearch(arr: number[], target: number): number {\n  let lo = 0, hi = arr.length - 1\n  while (lo <= hi) {\n    const mid = (lo + hi) >>> 1\n    if (arr[mid] === target) return mid\n    else if (arr[mid] < target) lo = mid + 1\n    else hi = mid - 1\n  }\n  return -1\n}\n\nexport function lowerBound(arr: number[], target: number): number {\n  let lo = 0, hi = arr.length\n  while (lo < hi) { const mid = (lo + hi) >>> 1; arr[mid] < target ? lo = mid + 1 : hi = mid }\n  return lo\n}\n\nexport function upperBound(arr: number[], target: number): number {\n  let lo = 0, hi = arr.length\n  while (lo < hi) { const mid = (lo + hi) >>> 1; arr[mid] <= target ? lo = mid + 1 : hi = mid }\n  return lo\n}\n"

registerSkill({
  id: "binary-search",
  summary: "Binary search a sorted array; return index or -1.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bbinary.*search\\b", 'i'))) sc += 0.75
  if (s.has(new RegExp("\\bbinarySearch\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bsorted.*array.*search|search.*sorted.*array", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/binarySearch.ts", content: IMPL }]
  },
})
