// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Binomial coefficient n choose k computed exactly for small n returning zero when k is negative or exceeds n via binomialCoeff.\nexport function binomialCoeff(n: number, k: number): number {\n  if (k < 0 || k > n) return 0;\n  let kk = k;\n  if (kk > n - kk) kk = n - kk;\n  let result = 1;\n  for (let i = 0; i < kk; i++) {\n    result = (result * (n - i)) / (i + 1);\n  }\n  return Math.round(result);\n}\n\n"

registerSkill({
  id: "binomial-coeff",
  summary: "Binomial coefficient n choose k computed exactly for small n returning zero when k is negative or exceeds n via binomialCoeff.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bbinomialCoeff\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bbinomial\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bcoefficient\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bchoose\\b", 'i'))) sc += 0.2
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/binomialCoeff.ts", content: IMPL }]
  },
})
