// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Cache-aside pattern: fetch from cache or load and store.\nexport class CacheAside<K, V> {\n  private store = new Map<K, V>()\n\n  constructor(private loader: (key: K) => Promise<V>) {}\n\n  async get(key: K): Promise<V> {\n    if (this.store.has(key)) return this.store.get(key)!\n    const value = await this.loader(key)\n    this.store.set(key, value)\n    return value\n  }\n\n  set(key: K, value: V): void { this.store.set(key, value) }\n  has(key: K): boolean { return this.store.has(key) }\n  delete(key: K): boolean { return this.store.delete(key) }\n  clear(): void { this.store.clear() }\n  size(): number { return this.store.size }\n}\n"

registerSkill({
  id: "cache-aside",
  summary: "Cache-aside pattern: fetch from cache or load and store.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcache.?aside|read.?through.*cache", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bCacheAside\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bcache.*miss.*load|load.*cache.*miss", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/cacheAside.ts", content: IMPL }]
  },
})
