// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Convert a string to camelCase.\nexport function camelCase(str: string): string {\n  return str\n    .replace(/[-_\\s]+(.)/g, (_, c) => c.toUpperCase())\n    .replace(/^[A-Z]/, c => c.toLowerCase())\n}\n"

registerSkill({
  id: "camel-case",
  summary: "Convert a string to camelCase.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcamel[- ]?case\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bcamelCase\\b", 'i'))) sc += 0.3
  if (s.has(new RegExp("\\bto[- ]?camel\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/camelCase.ts", content: IMPL }]
  },
})
