// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Convert between hex, RGB, and HSL color formats.\nexport interface RGB { r: number; g: number; b: number }\nexport interface HSL { h: number; s: number; l: number }\n\nexport function hexToRgb(hex: string): RGB | null {\n  const m = hex.replace('#', '').match(/^([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i)\n  if (!m) return null\n  return { r: parseInt(m[1], 16), g: parseInt(m[2], 16), b: parseInt(m[3], 16) }\n}\n\nexport function rgbToHex({ r, g, b }: RGB): string {\n  return '#' + [r, g, b].map(v => Math.max(0, Math.min(255, v)).toString(16).padStart(2, '0')).join('')\n}\n\nexport function rgbToHsl({ r, g, b }: RGB): HSL {\n  const rn = r/255, gn = g/255, bn = b/255\n  const max = Math.max(rn, gn, bn), min = Math.min(rn, gn, bn)\n  const l = (max + min) / 2\n  if (max === min) return { h: 0, s: 0, l: Math.round(l * 100) }\n  const d = max - min\n  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min)\n  let h = 0\n  if (max === rn) h = (gn - bn) / d + (gn < bn ? 6 : 0)\n  else if (max === gn) h = (bn - rn) / d + 2\n  else h = (rn - gn) / d + 4\n  return { h: Math.round(h * 60), s: Math.round(s * 100), l: Math.round(l * 100) }\n}\n\nexport function hslToRgb({ h, s, l }: HSL): RGB {\n  const sn = s / 100, ln = l / 100\n  const c = (1 - Math.abs(2 * ln - 1)) * sn\n  const x = c * (1 - Math.abs((h / 60) % 2 - 1))\n  const m = ln - c / 2\n  let [rn, gn, bn] = [0, 0, 0]\n  if (h < 60) [rn, gn, bn] = [c, x, 0]\n  else if (h < 120) [rn, gn, bn] = [x, c, 0]\n  else if (h < 180) [rn, gn, bn] = [0, c, x]\n  else if (h < 240) [rn, gn, bn] = [0, x, c]\n  else if (h < 300) [rn, gn, bn] = [x, 0, c]\n  else [rn, gn, bn] = [c, 0, x]\n  return { r: Math.round((rn+m)*255), g: Math.round((gn+m)*255), b: Math.round((bn+m)*255) }\n}\n"

registerSkill({
  id: "color-utils",
  summary: "Convert between hex, RGB, and HSL color formats.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bhex.*rgb|rgb.*hex", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bhsl.*rgb|rgb.*hsl", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bcolor.*convert|convert.*color", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bhexToRgb\\b|\\brgbToHex\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/colorUtils.ts", content: IMPL }]
  },
})
