// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — composeFns composes functions right-to-left and pipeFns left-to-right; empty input yields identity.\nexport function composeFns(...fns: Array<(x: any) => any>): (x: any) => any {\n  return (x: any) => fns.reduceRight((v, f) => f(v), x)\n}\nexport function pipeFns(...fns: Array<(x: any) => any>): (x: any) => any {\n  return (x: any) => fns.reduce((v, f) => f(v), x)\n}\n"

registerSkill({
  id: "compose-pipe",
  summary: "composeFns composes functions right-to-left and pipeFns left-to-right; empty input yields identity.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcomposeFns\\b|\\bpipeFns\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("compose.*function|pipe.*function", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/composePipe.ts", content: IMPL }]
  },
})
