// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Remove all falsy values from an array.\nexport function compact<T>(arr: Array<T | null | undefined | false | 0 | ''>): T[] {\n  return arr.filter(Boolean) as T[]\n}\n"

registerSkill({
  id: "compact",
  summary: "Remove all falsy values from an array.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcompact\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bremove.*falsy|falsy.*remov", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bfilter.*null.*undefined|null.*undefined.*filter", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/compact.ts", content: IMPL }]
  },
})
