// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Compute the area of the convex hull of 2D points using convexHullArea, building the hull with the Andrew monotone chain algorithm then applying the shoelace formula; fewer than 3 points yields 0.\ntype Pt = [number, number];\nfunction cross(o: Pt, a: Pt, b: Pt): number {\n  return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);\n}\nexport function convexHullArea(points: [number, number][]): number {\n  const n = points.length;\n  if (n < 3) return 0;\n  const pts = points.slice().sort((a, b) => a[0] - b[0] || a[1] - b[1]);\n  const lower: Pt[] = [];\n  for (const p of pts) {\n    while (lower.length >= 2 && cross(lower[lower.length - 2], lower[lower.length - 1], p) <= 0) lower.pop();\n    lower.push(p);\n  }\n  const upper: Pt[] = [];\n  for (let i = n - 1; i >= 0; i--) {\n    const p = pts[i];\n    while (upper.length >= 2 && cross(upper[upper.length - 2], upper[upper.length - 1], p) <= 0) upper.pop();\n    upper.push(p);\n  }\n  const hull = lower.slice(0, -1).concat(upper.slice(0, -1));\n  if (hull.length < 3) return 0;\n  let sum = 0;\n  for (let i = 0; i < hull.length; i++) {\n    const [x1, y1] = hull[i];\n    const [x2, y2] = hull[(i + 1) % hull.length];\n    sum += x1 * y2 - x2 * y1;\n  }\n  return Math.abs(sum) / 2;\n}\n\n"

registerSkill({
  id: "convex-hull-area",
  summary: "Compute the area of the convex hull of 2D points using convexHullArea, building the hull with the Andrew monotone chain algorithm then applying the shoelace formula; fewer than 3 points yields 0.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bconvexHullArea\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("convex hull", 'i'))) sc += 0.2
  if (s.has(new RegExp("monotone chain", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\barea\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/convexHullArea.ts", content: IMPL }]
  },
})
