// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Parse HTTP Cookie header to a Record; serialize a cookie value.\nexport function parseCookies(header: string): Record<string, string> {\n  const out: Record<string, string> = {}\n  for (const part of header.split(';')) {\n    const eq = part.indexOf('=')\n    if (eq === -1) continue\n    const key = decodeURIComponent(part.slice(0, eq).trim())\n    const val = decodeURIComponent(part.slice(eq + 1).trim())\n    out[key] = val\n  }\n  return out\n}\n\nexport function serializeCookie(\n  name: string, value: string,\n  opts: { maxAge?: number; path?: string; httpOnly?: boolean; secure?: boolean } = {}\n): string {\n  let str = `${encodeURIComponent(name)}=${encodeURIComponent(value)}`\n  if (opts.maxAge !== undefined) str += `; Max-Age=${opts.maxAge}`\n  if (opts.path) str += `; Path=${opts.path}`\n  if (opts.httpOnly) str += '; HttpOnly'\n  if (opts.secure) str += '; Secure'\n  return str\n}\n"

registerSkill({
  id: "cookie-parse",
  summary: "Parse HTTP Cookie header to a Record; serialize a cookie value.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcookie.*pars|pars.*cookie", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bhttp.*cookie|cookie.*header", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bparseCookies\\b|\\bserializeCookie\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/cookieParse.ts", content: IMPL }]
  },
})
