// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — countPathsDag returns the number of distinct paths from a source to a target in a DAG.\nexport function countPathsDag(n, edges, src, tgt) {\n  const adj = Array.from({ length: n }, () => [])\n  for (const [u, v] of edges) adj[u].push(v)\n  const memo = new Map()\n  const dfs = (u) => {\n    if (u === tgt) return 1\n    if (memo.has(u)) return memo.get(u)\n    let cnt = 0\n    for (const v of adj[u]) cnt += dfs(v)\n    memo.set(u, cnt); return cnt\n  }\n  return dfs(src)\n}\n"

registerSkill({
  id: "count-paths-dag",
  summary: "countPathsDag returns the number of distinct paths from a source to a target in a DAG.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcountPathsDag\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("count.*paths.*dag|number.*paths.*directed", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/countPathsDag.ts", content: IMPL }]
  },
})
