// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — MD5, SHA-1, SHA-256 hashes of a string via Node crypto.\nimport { createHash } from 'crypto'\n\nexport function md5(str: string): string { return createHash('md5').update(str).digest('hex') }\nexport function sha1(str: string): string { return createHash('sha1').update(str).digest('hex') }\nexport function sha256(str: string): string { return createHash('sha256').update(str).digest('hex') }\n"

registerSkill({
  id: "crypto-hash",
  summary: "MD5, SHA-1, SHA-256 hashes of a string via Node crypto.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsha256\\b|\\bsha-256\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bmd5\\b.*hash|hash.*\\bmd5\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bcrypto.*hash|hash.*string", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bmd5\\b|\\bsha1\\b|\\bsha256\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/cryptoHash.ts", content: IMPL }]
  },
})
