// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Parse CSV text to rows; stringify rows back to CSV.\nexport function parseCSV(text: string, sep = ','): string[][] {\n  return text.split('\\n').filter(l => l.trim()).map(line => {\n    const cells: string[] = []\n    let cur = '', inQ = false\n    for (let i = 0; i < line.length; i++) {\n      const c = line[i]\n      if (c === '\"') {\n        if (inQ && line[i + 1] === '\"') { cur += '\"'; i++ }\n        else inQ = !inQ\n      } else if (c === sep && !inQ) { cells.push(cur); cur = '' }\n      else cur += c\n    }\n    cells.push(cur)\n    return cells\n  })\n}\n\nexport function stringifyCSV(rows: string[][], sep = ','): string {\n  return rows.map(row =>\n    row.map(cell => {\n      const needsQuote = cell.includes(sep) || cell.includes('\"') || cell.includes('\\n')\n      return needsQuote ? `\"${cell.replace(/\"/g, '\"\"')}\"` : cell\n    }).join(sep)\n  ).join('\\n')\n}\n"

registerSkill({
  id: "csv-parse",
  summary: "Parse CSV text to rows; stringify rows back to CSV.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcsv\\b.*pars|pars.*\\bcsv\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bparseCSV\\b|\\bstringifyCSV\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bcomma.*separated|comma.*delimit", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/csvParse.ts", content: IMPL }]
  },
})
