// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — addDays, diffDays, isLeapYear, daysInMonth, startOfDay, endOfDay.\nexport function addDays(date: Date, days: number): Date {\n  const d = new Date(date)\n  d.setUTCDate(d.getUTCDate() + days)\n  return d\n}\n\nexport function diffDays(a: Date, b: Date): number {\n  return Math.round((b.getTime() - a.getTime()) / 86400000)\n}\n\nexport function isLeapYear(year: number): boolean {\n  return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0\n}\n\nexport function daysInMonth(year: number, month: number): number {\n  return new Date(Date.UTC(year, month, 0)).getUTCDate()\n}\n\nexport function startOfDay(date: Date): Date {\n  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()))\n}\n\nexport function endOfDay(date: Date): Date {\n  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), 23, 59, 59, 999))\n}\n"

registerSkill({
  id: "date-utils",
  summary: "addDays, diffDays, isLeapYear, daysInMonth, startOfDay, endOfDay.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\baddDays\\b|\\badd.*days\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bdiffDays\\b|\\bdiff.*days\\b|\\bdays.*between", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bisLeapYear\\b|\\bleap.*year", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bdaysInMonth\\b|\\bdays.*month", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\baddDays.*diffDays|date.*arithmetic", 'i'))) sc += 0.6
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/dateUtils.ts", content: IMPL }]
  },
})
