// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Format a Date with tokens YYYY MM DD HH mm ss.\nexport function formatDate(date: Date, pattern: string): string {\n  const p = (n: number, len = 2) => String(n).padStart(len, '0')\n  return pattern\n    .replace('YYYY', p(date.getUTCFullYear(), 4))\n    .replace('MM', p(date.getUTCMonth() + 1))\n    .replace('DD', p(date.getUTCDate()))\n    .replace('HH', p(date.getUTCHours()))\n    .replace('mm', p(date.getUTCMinutes()))\n    .replace('ss', p(date.getUTCSeconds()))\n}\n\nexport function parseDate(str: string): Date {\n  return new Date(str)\n}\n"

registerSkill({
  id: "date-format",
  summary: "Format a Date with tokens YYYY MM DD HH mm ss.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bformat.*date|date.*format", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bformatDate\\b|\\bparseDate\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bdate.*string|YYYY.*MM.*DD", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/dateFormat.ts", content: IMPL }]
  },
})
