// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Deep merge two plain objects (right overwrites left, arrays replaced).\nexport function deepMerge<T extends Record<string, unknown>>(\n  target: T,\n  ...sources: Partial<T>[]\n): T {\n  const out = { ...target } as T\n  for (const src of sources) {\n    for (const [k, v] of Object.entries(src)) {\n      if (v !== null && typeof v === 'object' && !Array.isArray(v) &&\n          out[k as keyof T] !== null && typeof out[k as keyof T] === 'object' &&\n          !Array.isArray(out[k as keyof T])) {\n        (out as Record<string, unknown>)[k] = deepMerge(\n          out[k as keyof T] as Record<string, unknown>,\n          v as Record<string, unknown>\n        )\n      } else {\n        (out as Record<string, unknown>)[k] = v\n      }\n    }\n  }\n  return out\n}\n"

registerSkill({
  id: "deep-merge",
  summary: "Deep merge two plain objects (right overwrites left, arrays replaced).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdeep.*merge|merge.*deep", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bdeepMerge\\b", 'i'))) sc += 0.35
  if (s.has(new RegExp("\\brecursive.*merge|merge.*nested.*object", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/deepMerge.ts", content: IMPL }]
  },
})
