// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — degreeSequence returns the undirected degree of each node in a graph, sorted descending.\nexport function degreeSequence(n, edges) {\n  const deg = new Array(n).fill(0)\n  for (const [u, v] of edges) { deg[u]++; if (u !== v) deg[v]++ }\n  return deg.sort((a, b) => b - a)\n}\n"

registerSkill({
  id: "degree-sequence",
  summary: "degreeSequence returns the undirected degree of each node in a graph, sorted descending.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdegreeSequence\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("degree.*sequence|degree.*graph", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/degreeSequence.ts", content: IMPL }]
  },
})
