// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Deque is a double-ended queue with pushFront, pushBack, popFront, popBack, size, and toArray.\nexport class Deque<T> {\n  private items: T[] = []\n  pushFront(item: T): void { this.items.unshift(item) }\n  pushBack(item: T): void { this.items.push(item) }\n  popFront(): T | undefined { return this.items.shift() }\n  popBack(): T | undefined { return this.items.pop() }\n  size(): number { return this.items.length }\n  toArray(): T[] { return [...this.items] }\n}\n"

registerSkill({
  id: "deque-structure",
  summary: "Deque is a double-ended queue with pushFront, pushBack, popFront, popBack, size, and toArray.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bDeque\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("double.?ended queue|deque", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/dequeStructure.ts", content: IMPL }]
  },
})
