// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — dijkstraDistances returns single-source shortest distances over a directed weighted graph; unreachable nodes are Infinity.\nexport function dijkstraDistances(n, edges, src) {\n  const adj = Array.from({ length: n }, () => [])\n  for (const [u, v, w] of edges) adj[u].push([v, w])\n  const dist = new Array(n).fill(Infinity); dist[src] = 0\n  const visited = new Array(n).fill(false)\n  for (let iter = 0; iter < n; iter++) {\n    let u = -1, best = Infinity\n    for (let i = 0; i < n; i++) if (!visited[i] && dist[i] < best) { best = dist[i]; u = i }\n    if (u < 0) break\n    visited[u] = true\n    for (const [v, w] of adj[u]) if (dist[u] + w < dist[v]) dist[v] = dist[u] + w\n  }\n  return dist\n}\n"

registerSkill({
  id: "dijkstra-distances",
  summary: "dijkstraDistances returns single-source shortest distances over a directed weighted graph; unreachable nodes are Infinity.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdijkstraDistances\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("dijkstra|shortest path.*weighted", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/dijkstraDistances.ts", content: IMPL }]
  },
})
