// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Parse .env file format to a Record<string, string>.\nexport function parseDotenv(text: string): Record<string, string> {\n  const out: Record<string, string> = {}\n  for (const raw of text.split('\\n')) {\n    const line = raw.trim()\n    if (!line || line.startsWith('#')) continue\n    const eq = line.indexOf('=')\n    if (eq === -1) continue\n    const key = line.slice(0, eq).trim()\n    let val = line.slice(eq + 1).trim()\n    if ((val.startsWith('\"') && val.endsWith('\"')) ||\n        (val.startsWith(\"'\") && val.endsWith(\"'\"))) {\n      val = val.slice(1, -1)\n    }\n    out[key] = val\n  }\n  return out\n}\n\nexport function stringifyDotenv(env: Record<string, string>): string {\n  return Object.entries(env)\n    .map(([k, v]) => v.includes(' ') || v.includes('\"') || v.includes(\"'\")\n      ? `${k}=\"${v.replace(/\"/g, '\\\\\"')}\"`\n      : `${k}=${v}`)\n    .join('\\n')\n}\n"

registerSkill({
  id: "dotenv-parse",
  summary: "Parse .env file format to a Record<string, string>.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdotenv\\b|\\b\\.env\\b", 'i'))) sc += 0.75
  if (s.has(new RegExp("\\benv.*file.*pars|pars.*env.*file", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bparseDotenv\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/dotenvParse.ts", content: IMPL }]
  },
})
