// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Doubly linked list with push, pop, unshift, shift, insert, remove.\ninterface Node<T> { value: T; prev: Node<T> | null; next: Node<T> | null }\n\nexport class DoublyLinkedList<T> {\n  private head: Node<T> | null = null\n  private tail: Node<T> | null = null\n  private _size = 0\n\n  push(value: T): void {\n    const node: Node<T> = { value, prev: this.tail, next: null }\n    if (this.tail) this.tail.next = node; else this.head = node\n    this.tail = node; this._size++\n  }\n\n  pop(): T | undefined {\n    if (!this.tail) return undefined\n    const val = this.tail.value\n    this.tail = this.tail.prev\n    if (this.tail) this.tail.next = null; else this.head = null\n    this._size--; return val\n  }\n\n  unshift(value: T): void {\n    const node: Node<T> = { value, prev: null, next: this.head }\n    if (this.head) this.head.prev = node; else this.tail = node\n    this.head = node; this._size++\n  }\n\n  shift(): T | undefined {\n    if (!this.head) return undefined\n    const val = this.head.value\n    this.head = this.head.next\n    if (this.head) this.head.prev = null; else this.tail = null\n    this._size--; return val\n  }\n\n  size(): number { return this._size }\n  isEmpty(): boolean { return this._size === 0 }\n\n  toArray(): T[] {\n    const out: T[] = []\n    let cur = this.head\n    while (cur) { out.push(cur.value); cur = cur.next }\n    return out\n  }\n\n  toArrayReverse(): T[] {\n    const out: T[] = []\n    let cur = this.tail\n    while (cur) { out.push(cur.value); cur = cur.prev }\n    return out\n  }\n}\n"

registerSkill({
  id: "doubly-linked-list",
  summary: "Doubly linked list with push, pop, unshift, shift, insert, remove.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bdoubly.*linked|linked.*list.*doubly", 'i'))) sc += 0.75
  if (s.has(new RegExp("\\bDoublyLinkedList\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\blinked.*list.*prev|previous.*node.*linked", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/doublyLinkedList.ts", content: IMPL }]
  },
})
