// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — createError, serializeError, wrapError, isNetworkError, retryable.\nexport interface AppError extends Error {\n  code: string\n  statusCode?: number\n  cause?: unknown\n}\n\nexport function createError(message: string, code: string, statusCode?: number, cause?: unknown): AppError {\n  const err = new Error(message) as AppError\n  err.code = code; err.statusCode = statusCode; err.cause = cause\n  return err\n}\n\nexport function serializeError(err: unknown): Record<string, unknown> {\n  if (err instanceof Error) {\n    return { message: err.message, name: err.name, stack: err.stack, ...(err as AppError).code ? { code: (err as AppError).code } : {} }\n  }\n  return { message: String(err) }\n}\n\nexport function wrapError(err: unknown, message: string, code = 'WRAPPED'): AppError {\n  return createError(message, code, undefined, err)\n}\n\nexport function isNetworkError(err: unknown): boolean {\n  if (!(err instanceof Error)) return false\n  return /ECONNREFUSED|ECONNRESET|ETIMEDOUT|ENOTFOUND|network|fetch/i.test(err.message)\n}\n"

registerSkill({
  id: "error-utils",
  summary: "createError, serializeError, wrapError, isNetworkError, retryable.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bcreateError\\b|\\bcreate.*error.*util", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bserializeError\\b|\\bserialize.*error", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bwrapError\\b|\\bwrap.*error|error.*wrap", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\berror.*util|error.*helper.*util", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/errorUtils.ts", content: IMPL }]
  },
})
