// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Simple typed event emitter: on, off, emit, once.\ntype Listener = (...args: unknown[]) => void\n\nexport class EventEmitter {\n  private listeners = new Map<string, Set<Listener>>()\n\n  on(event: string, fn: Listener): this {\n    if (!this.listeners.has(event)) this.listeners.set(event, new Set())\n    this.listeners.get(event)!.add(fn)\n    return this\n  }\n\n  off(event: string, fn: Listener): this {\n    this.listeners.get(event)?.delete(fn)\n    return this\n  }\n\n  emit(event: string, ...args: unknown[]): boolean {\n    const fns = this.listeners.get(event)\n    if (!fns?.size) return false\n    for (const fn of fns) fn(...args)\n    return true\n  }\n\n  once(event: string, fn: Listener): this {\n    const wrapper: Listener = (...args) => { this.off(event, wrapper); fn(...args) }\n    return this.on(event, wrapper)\n  }\n\n  removeAllListeners(event?: string): this {\n    if (event) this.listeners.delete(event)\n    else this.listeners.clear()\n    return this\n  }\n\n  listenerCount(event: string): number {\n    return this.listeners.get(event)?.size ?? 0\n  }\n}\n"

registerSkill({
  id: "event-emitter-simple",
  summary: "Simple typed event emitter: on, off, emit, once.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bevent.*emitter|emitter.*event", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bEventEmitter\\b", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\bon\\b.*\\bemit\\b|\\bemit\\b.*\\bon\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bpublish.*subscribe|pub.*sub", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/eventEmitterSimple.ts", content: IMPL }]
  },
})
