// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Extended Euclidean algorithm returning g x y where a times x plus b times y equals the gcd g via extendedGcd.\nexport function extendedGcd(a: number, b: number): [number, number, number] {\n  let oldR = a, r = b;\n  let oldS = 1, s = 0;\n  let oldT = 0, t = 1;\n  while (r !== 0) {\n    const q = Math.floor(oldR / r);\n    [oldR, r] = [r, oldR - q * r];\n    [oldS, s] = [s, oldS - q * s];\n    [oldT, t] = [t, oldT - q * t];\n  }\n  if (oldR < 0) return [-oldR, -oldS, -oldT];\n  return [oldR, oldS, oldT];\n}\n\n"

registerSkill({
  id: "extended-gcd",
  summary: "Extended Euclidean algorithm returning g x y where a times x plus b times y equals the gcd g via extendedGcd.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bextendedGcd\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bEuclidean\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bgcd\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bBezout|coefficient", 'i'))) sc += 0.15
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/extendedGcd.ts", content: IMPL }]
  },
})
