// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Flatten a nested array one level deep (or deeply with depth param).\nexport function flatten<T>(arr: Array<T | T[]>, depth = 1): T[] {\n  if (depth <= 0) return arr as T[]\n  const out: T[] = []\n  for (const item of arr) {\n    if (Array.isArray(item) && depth > 0) out.push(...flatten(item, depth - 1))\n    else out.push(item as T)\n  }\n  return out\n}\n"

registerSkill({
  id: "flatten",
  summary: "Flatten a nested array one level deep (or deeply with depth param).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bflatten\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bflatMap\\b|\\bflat\\b.*array", 'i'))) sc += 0.25
  if (s.has(new RegExp("\\bnested.*array.*flat|flat.*nested.*array", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/flatten.ts", content: IMPL }]
  },
})
