// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — formatCurrency formats a number as currency with a symbol, two decimal places, and thousand separators; negatives use \"-$x\" form.\nexport function formatCurrency(amount: number, symbol: string): string {\n  const abs = Math.abs(amount)\n  const [int, dec] = abs.toFixed(2).split('.')\n  const intFmt = int.replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',')\n  const formatted = symbol + intFmt + '.' + dec\n  return amount < 0 ? '-' + formatted : formatted\n}\n"

registerSkill({
  id: "format-currency",
  summary: "formatCurrency formats a number as currency with a symbol, two decimal places, and thousand separators; negatives use \"-$x\" form.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bformatCurrency\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("currency.*symbol.*thousand|negatives.*-\\$", 'i'))) sc += 0.6
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/formatCurrency.ts", content: IMPL }]
  },
})
