// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — formatDuration humanizes milliseconds to \"1h 30m\" style using up to two largest non-zero units; 0ms returns \"0s\".\nexport function formatDuration(ms: number): string {\n  if (ms === 0) return '0s'\n  const units: [string, number][] = [['d',86400000],['h',3600000],['m',60000],['s',1000]]\n  const parts: string[] = []\n  let rem = ms\n  for (const [label, factor] of units) {\n    const v = Math.floor(rem / factor)\n    if (v) { parts.push(v + label); rem -= v * factor }\n    if (parts.length === 2) break\n  }\n  return parts.join(' ') || '<1s'\n}\n"

registerSkill({
  id: "format-duration",
  summary: "formatDuration humanizes milliseconds to \"1h 30m\" style using up to two largest non-zero units; 0ms returns \"0s\".",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bformatDuration\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("format.*duration|humanize.*ms|duration.*human", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/formatDuration.ts", content: IMPL }]
  },
})
