// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — globMatch checks whether a string matches a glob pattern where * matches any characters and ? matches one.\nexport function globMatch(glob, str) {\n  const re = glob.replace(/[.+^${}()|[\\]\\\\]/g, '\\\\$&').replace(/\\*/g,'[\\\\s\\\\S]*').replace(/\\?/g,'.')\n  return new RegExp('^' + re + '$').test(str)\n}\n"

registerSkill({
  id: "glob-match",
  summary: "globMatch checks whether a string matches a glob pattern where * matches any characters and ? matches one.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bglobMatch\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("glob.*pattern|wildcard.*match", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/globMatch.ts", content: IMPL }]
  },
})
