// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Adjacency list graph with BFS, DFS, shortest path, and connected components.\nexport class Graph<T> {\n  private adj = new Map<T, Set<T>>()\n\n  addVertex(v: T): void { if (!this.adj.has(v)) this.adj.set(v, new Set()) }\n  addEdge(u: T, v: T, directed = false): void {\n    this.addVertex(u); this.addVertex(v)\n    this.adj.get(u)!.add(v)\n    if (!directed) this.adj.get(v)!.add(u)\n  }\n  neighbors(v: T): T[] { return [...(this.adj.get(v) ?? [])] }\n  vertices(): T[] { return [...this.adj.keys()] }\n  hasEdge(u: T, v: T): boolean { return this.adj.get(u)?.has(v) ?? false }\n\n  bfs(start: T): T[] {\n    const visited = new Set<T>(), queue = [start], out: T[] = []\n    visited.add(start)\n    while (queue.length) {\n      const v = queue.shift()!; out.push(v)\n      for (const n of this.adj.get(v) ?? []) if (!visited.has(n)) { visited.add(n); queue.push(n) }\n    }\n    return out\n  }\n\n  dfs(start: T): T[] {\n    const visited = new Set<T>(), out: T[] = []\n    const go = (v: T) => { visited.add(v); out.push(v); for (const n of this.adj.get(v) ?? []) if (!visited.has(n)) go(n) }\n    go(start); return out\n  }\n\n  shortestPath(start: T, end: T): T[] | null {\n    const prev = new Map<T, T>(), visited = new Set<T>([start]), queue = [start]\n    while (queue.length) {\n      const v = queue.shift()!\n      if (v === end) { const path: T[] = []; let c: T | undefined = end; while (c !== undefined) { path.unshift(c); c = prev.get(c) }; return path }\n      for (const n of this.adj.get(v) ?? []) if (!visited.has(n)) { visited.add(n); prev.set(n, v); queue.push(n) }\n    }\n    return null\n  }\n}\n"

registerSkill({
  id: "graph-simple",
  summary: "Adjacency list graph with BFS, DFS, shortest path, and connected components.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bgraph\\b.*(?:bfs|dfs|shortest|adjacen)", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bbreadth.*first|depth.*first.*search", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bshortest.*path.*graph|graph.*path.*find", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bGraph\\b.*class|adjacency.*list", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/graphSimple.ts", content: IMPL }]
  },
})
