// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — grayEncode converts a binary number to Gray code and grayDecode converts it back; they are inverses.\nexport function grayEncode(n: number): number {\n  return (n ^ (n >>> 1)) >>> 0\n}\n\nexport function grayDecode(g: number): number {\n  let n = g\n  while (g > 0) { g = g >>> 1; n ^= g }\n  return n >>> 0\n}\n"

registerSkill({
  id: "gray-code",
  summary: "grayEncode converts a binary number to Gray code and grayDecode converts it back; they are inverses.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bgrayEncode\\b|\\bgrayDecode\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("gray code", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/grayCode.ts", content: IMPL }]
  },
})
