// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — hammingDistance returns the number of differing bits between two non-negative integers.\nexport function hammingDistance(a: number, b: number): number {\n  let x = (a ^ b) >>> 0, c = 0\n  while (x) { c += x & 1; x >>>= 1 }\n  return c\n}\n"

registerSkill({
  id: "hamming-distance",
  summary: "hammingDistance returns the number of differing bits between two non-negative integers.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bhammingDistance\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("hamming distance|differing bits|bit difference", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/hammingDistance.ts", content: IMPL }]
  },
})
