// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — humanizeList formats an array of strings as \"a\", \"a and b\", or \"a, b and c\"; empty array returns empty string.\nexport function humanizeList(items: string[]): string {\n  if (!items.length) return ''\n  if (items.length === 1) return items[0]\n  if (items.length === 2) return items[0] + ' and ' + items[1]\n  return items.slice(0,-1).join(', ') + ' and ' + items[items.length-1]\n}\n"

registerSkill({
  id: "humanize-list",
  summary: "humanizeList formats an array of strings as \"a\", \"a and b\", or \"a, b and c\"; empty array returns empty string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bhumanizeList\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("humanize.*list|list.*human.*readable", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/humanizeList.ts", content: IMPL }]
  },
})
