// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — setIntervalAsync, clearIntervalAsync, and a StopWatch class.\nexport class Stopwatch {\n  private startTime: number | null = null\n  private elapsed = 0\n  private laps: number[] = []\n\n  start(): this {\n    if (this.startTime === null) this.startTime = Date.now()\n    return this\n  }\n\n  stop(): number {\n    if (this.startTime !== null) {\n      this.elapsed += Date.now() - this.startTime\n      this.startTime = null\n    }\n    return this.elapsed\n  }\n\n  lap(): number {\n    const t = this.elapsedMs()\n    this.laps.push(t)\n    return t\n  }\n\n  reset(): this { this.startTime = null; this.elapsed = 0; this.laps = []; return this }\n\n  elapsedMs(): number {\n    return this.startTime !== null ? this.elapsed + (Date.now() - this.startTime) : this.elapsed\n  }\n\n  isRunning(): boolean { return this.startTime !== null }\n  getLaps(): number[] { return [...this.laps] }\n}\n"

registerSkill({
  id: "interval-timer",
  summary: "setIntervalAsync, clearIntervalAsync, and a StopWatch class.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bstopwatch\\b|\\bStopwatch\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\belapsed.*time.*class|timer.*class", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bstart.*stop.*elapsed|lap.*timer", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/intervalTimer.ts", content: IMPL }]
  },
})
