// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isE164Phone validates a phone number in E.164 format: a plus sign followed by 1 to 15 digits with no leading zero.\nexport function isE164Phone(s: string): boolean {\n  return /^\\+[1-9]\\d{0,14}$/.test(s);\n}\n\n"

registerSkill({
  id: "is-e164-phone",
  summary: "isE164Phone validates a phone number in E.164 format: a plus sign followed by 1 to 15 digits with no leading zero.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisE164Phone\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bE\\.164\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bphone\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bdigits\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isE164Phone.ts", content: IMPL }]
  },
})
