// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isEAN13 validates a 13-digit EAN-13 barcode by verifying its modulo-10 checksum digit, ignoring spaces and hyphens.\nexport function isEAN13(s: string): boolean {\n  const c = s.replace(/[\\s-]/g, '');\n  if (!/^\\d{13}$/.test(c)) return false;\n  let sum = 0;\n  for (let i = 0; i < 12; i++) sum += (i % 2 === 0 ? 1 : 3) * (c.charCodeAt(i) - 48);\n  const check = (10 - (sum % 10)) % 10;\n  return check === c.charCodeAt(12) - 48;\n}\n\n"

registerSkill({
  id: "is-ean13",
  summary: "isEAN13 validates a 13-digit EAN-13 barcode by verifying its modulo-10 checksum digit, ignoring spaces and hyphens.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisEAN13\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bEAN-13\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bbarcode\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bchecksum\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isEAN13.ts", content: IMPL }]
  },
})
