// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isoWeekNumber returns the ISO-8601 week number (1 to 53) for a Date using UTC.\nexport function isoWeekNumber(date: Date): number {\n  const d = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()))\n  d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7))\n  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1))\n  return Math.ceil((((d.getTime() - yearStart.getTime()) / 86400000) + 1) / 7)\n}\n"

registerSkill({
  id: "iso-week-number",
  summary: "isoWeekNumber returns the ISO-8601 week number (1 to 53) for a Date using UTC.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisoWeekNumber\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("iso.*week|week.*number.*iso", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isoWeekNumber.ts", content: IMPL }]
  },
})
