// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Validate a UUID v4 string.\nexport function isUUID(str: string): boolean {\n  return /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(str)\n}\n"

registerSkill({
  id: "is-uuid",
  summary: "Validate a UUID v4 string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bvalidate.*uuid|uuid.*validat", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bisUUID\\b|\\buuid.*check\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\buuid.*format\\b", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/isUUID.ts", content: IMPL }]
  },
})
