// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — kmpSearchIndex returns the first index where a pattern occurs in text using the Knuth-Morris-Pratt algorithm, or -1.\nexport function kmpSearchIndex(text: string, pattern: string): number {\n  if (pattern === '') return 0\n  const lps = new Array(pattern.length).fill(0)\n  for (let i = 1, len = 0; i < pattern.length;) {\n    if (pattern[i] === pattern[len]) lps[i++] = ++len\n    else if (len) len = lps[len - 1]\n    else lps[i++] = 0\n  }\n  for (let i = 0, j = 0; i < text.length;) {\n    if (text[i] === pattern[j]) { i++; j++; if (j === pattern.length) return i - j }\n    else if (j) j = lps[j - 1]\n    else i++\n  }\n  return -1\n}\n"

registerSkill({
  id: "kmp-search-index",
  summary: "kmpSearchIndex returns the first index where a pattern occurs in text using the Knuth-Morris-Pratt algorithm, or -1.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bkmpSearchIndex\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("knuth.?morris.?pratt|\\bkmp\\b|substring search", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/kmpSearchIndex.ts", content: IMPL }]
  },
})
