// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — LFUCache evicts the least-frequently-used entry (ties broken least-recently-used) when capacity is exceeded.\nexport class LFUCache<K, V> {\n  private vals = new Map<K, V>(); private freq = new Map<K, number>(); private order = new Map<K, number>(); private tick = 0\n  constructor(private cap: number) {}\n  get(k: K): V | undefined {\n    if (!this.vals.has(k)) return undefined\n    this.freq.set(k, (this.freq.get(k) ?? 0) + 1); this.order.set(k, this.tick++)\n    return this.vals.get(k)\n  }\n  put(k: K, v: V): void {\n    if (this.cap <= 0) return\n    if (this.vals.has(k)) { this.vals.set(k, v); this.freq.set(k, (this.freq.get(k) ?? 0) + 1); this.order.set(k, this.tick++); return }\n    if (this.vals.size >= this.cap) {\n      let evict: K | undefined, bf = Infinity, bo = Infinity\n      for (const key of this.vals.keys()) { const f = this.freq.get(key) ?? 0, o = this.order.get(key) ?? 0; if (f < bf || (f === bf && o < bo)) { bf = f; bo = o; evict = key } }\n      if (evict !== undefined) { this.vals.delete(evict); this.freq.delete(evict); this.order.delete(evict) }\n    }\n    this.vals.set(k, v); this.freq.set(k, 1); this.order.set(k, this.tick++)\n  }\n}\n"

registerSkill({
  id: "lfu-cache",
  summary: "LFUCache evicts the least-frequently-used entry (ties broken least-recently-used) when capacity is exceeded.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bLFUCache\\b|\\blfuCache\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("least.?frequently.?used|\\bLFU\\b", 'i'))) sc += 0.7
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/lfuCache.ts", content: IMPL }]
  },
})
