// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — luhnCheck validates a numeric string against the Luhn checksum algorithm, ignoring spaces and requiring digits only.\nexport function luhnCheck(num: string): boolean {\n  const d = num.replace(/\\s+/g, '');\n  if (d.length === 0 || !/^\\d+$/.test(d)) return false;\n  let sum = 0;\n  let alt = false;\n  for (let i = d.length - 1; i >= 0; i--) {\n    let n = d.charCodeAt(i) - 48;\n    if (alt) {\n      n *= 2;\n      if (n > 9) n -= 9;\n    }\n    sum += n;\n    alt = !alt;\n  }\n  return sum % 10 === 0;\n}\n\n"

registerSkill({
  id: "luhn-check",
  summary: "luhnCheck validates a numeric string against the Luhn checksum algorithm, ignoring spaces and requiring digits only.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bluhnCheck\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bLuhn\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bchecksum\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\bdigits\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/luhnCheck.ts", content: IMPL }]
  },
})
