// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — maskString replaces all but the last visible characters with asterisks.\nexport function maskString(s: string, visible: number): string {\n  if (visible >= s.length) return s\n  return '*'.repeat(s.length - visible) + s.slice(s.length - visible)\n}\n"

registerSkill({
  id: "mask-string",
  summary: "maskString replaces all but the last visible characters with asterisks.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmaskString\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("mask.*string|redact.*string", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/maskString.ts", content: IMPL }]
  },
})
