// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — maxSubArraySum returns the maximum contiguous subarray sum (Kadane), handling all-negative arrays.\nexport function maxSubArraySum(arr: number[]): number {\n  if (!arr.length) return 0\n  let best = arr[0], cur = arr[0]\n  for (let i = 1; i < arr.length; i++) {\n    cur = Math.max(arr[i], cur + arr[i])\n    best = Math.max(best, cur)\n  }\n  return best\n}\n"

registerSkill({
  id: "max-subarray-sum",
  summary: "maxSubArraySum returns the maximum contiguous subarray sum (Kadane), handling all-negative arrays.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmaxSubArraySum\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("maximum.*subarray|kadane|contiguous.*sum", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/maxSubArraySum.ts", content: IMPL }]
  },
})
