// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — memoizeUnary memoizes a single-argument function, caching results in a Map keyed by the argument.\nexport function memoizeUnary<A, R>(fn: (x: A) => R): (x: A) => R {\n  const cache = new Map<A, R>()\n  return (x: A): R => {\n    if (cache.has(x)) return cache.get(x) as R\n    const r = fn(x); cache.set(x, r); return r\n  }\n}\n"

registerSkill({
  id: "memoize-unary",
  summary: "memoizeUnary memoizes a single-argument function, caching results in a Map keyed by the argument.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmemoizeUnary\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("memoize.*function|cache.*function result", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/memoizeUnary.ts", content: IMPL }]
  },
})
