// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Min-heap with insert, extractMin, peek, and heapify.\nexport class MinHeap<T> {\n  private data: Array<{ value: T; priority: number }> = []\n\n  private up(i: number): void {\n    while (i > 0) {\n      const p = (i - 1) >> 1\n      if (this.data[p].priority <= this.data[i].priority) break\n      ;[this.data[p], this.data[i]] = [this.data[i], this.data[p]]\n      i = p\n    }\n  }\n\n  private down(i: number): void {\n    const n = this.data.length\n    while (true) {\n      let min = i\n      const l = 2 * i + 1, r = 2 * i + 2\n      if (l < n && this.data[l].priority < this.data[min].priority) min = l\n      if (r < n && this.data[r].priority < this.data[min].priority) min = r\n      if (min === i) break\n      ;[this.data[min], this.data[i]] = [this.data[i], this.data[min]]\n      i = min\n    }\n  }\n\n  insert(value: T, priority: number): void {\n    this.data.push({ value, priority })\n    this.up(this.data.length - 1)\n  }\n\n  extractMin(): { value: T; priority: number } | null {\n    if (!this.data.length) return null\n    const min = this.data[0]\n    const last = this.data.pop()!\n    if (this.data.length) { this.data[0] = last; this.down(0) }\n    return min\n  }\n\n  peek(): { value: T; priority: number } | null { return this.data[0] ?? null }\n  size(): number { return this.data.length }\n  isEmpty(): boolean { return !this.data.length }\n}\n"

registerSkill({
  id: "min-heap",
  summary: "Min-heap with insert, extractMin, peek, and heapify.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmin[- ]?heap\\b", 'i'))) sc += 0.75
  if (s.has(new RegExp("\\bMinHeap\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bpriority.*queue.*min|min.*priority.*queue", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bheap.*extract.*min|extractMin", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/minHeap.ts", content: IMPL }]
  },
})
