// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Modular exponentiation computing base raised to exp modulo mod via fast exponentiation in modPow.\nexport function modPow(base: number, exp: number, mod: number): number {\n  if (mod === 1) return 0;\n  let result = 1;\n  let b = ((base % mod) + mod) % mod;\n  let e = exp;\n  while (e > 0) {\n    if (e & 1) result = (result * b) % mod;\n    b = (b * b) % mod;\n    e = Math.floor(e / 2);\n  }\n  return result;\n}\n\n"

registerSkill({
  id: "mod-pow",
  summary: "Modular exponentiation computing base raised to exp modulo mod via fast exponentiation in modPow.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmodPow\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bmodular\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bexponentiation\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bmodulo\\b", 'i'))) sc += 0.2
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/modPow.ts", content: IMPL }]
  },
})
