// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — mulberry32 returns a deterministic PRNG function seeded with a 32-bit integer, yielding values in [0,1).\nexport function mulberry32(seed) {\n  return function() {\n    seed |= 0; seed = seed + 0x6D2B79F5 | 0\n    let t = Math.imul(seed ^ seed >>> 15, 1 | seed)\n    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t\n    return ((t ^ t >>> 14) >>> 0) / 4294967296\n  }\n}\n"

registerSkill({
  id: "mulberry32-prng",
  summary: "mulberry32 returns a deterministic PRNG function seeded with a 32-bit integer, yielding values in [0,1).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bmulberry32\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("deterministic.*prng.*seed|seeded.*prng.*function", 'i'))) sc += 0.7
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/mulberry32Prng.ts", content: IMPL }]
  },
})
