// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Convert numbers to English words and back.\nconst ONES = ['','one','two','three','four','five','six','seven','eight','nine',\n  'ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen']\nconst TENS = ['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety']\n\nexport function numberToWords(n: number): string {\n  if (n === 0) return 'zero'\n  if (n < 0) return 'negative ' + numberToWords(-n)\n  if (n < 20) return ONES[n]\n  if (n < 100) return TENS[Math.floor(n/10)] + (n%10 ? '-' + ONES[n%10] : '')\n  if (n < 1000) return ONES[Math.floor(n/100)] + ' hundred' + (n%100 ? ' ' + numberToWords(n%100) : '')\n  if (n < 1000000) return numberToWords(Math.floor(n/1000)) + ' thousand' + (n%1000 ? ' ' + numberToWords(n%1000) : '')\n  if (n < 1000000000) return numberToWords(Math.floor(n/1000000)) + ' million' + (n%1000000 ? ' ' + numberToWords(n%1000000) : '')\n  return String(n)\n}\n\nexport function wordsToNumber(words: string): number {\n  const w = words.toLowerCase().trim()\n  if (w === 'zero') return 0\n  let n = 0, current = 0\n  for (const word of w.replace(/-/g,' ').split(' ')) {\n    const ones = ONES.indexOf(word)\n    const tens = TENS.indexOf(word)\n    if (ones > 0) current += ones\n    else if (tens > 0) current += tens * 10\n    else if (word === 'hundred') current *= 100\n    else if (word === 'thousand') { n += current * 1000; current = 0 }\n    else if (word === 'million') { n += current * 1000000; current = 0 }\n  }\n  return n + current\n}\n"

registerSkill({
  id: "number-words",
  summary: "Convert numbers to English words and back.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bnumber.*words?|words?.*number", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bnumberToWords\\b|\\bwordsToNumber\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\binteger.*english|english.*number", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bspell.*number|number.*spell", 'i'))) sc += 0.55
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/numberWords.ts", content: IMPL }]
  },
})
