// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — gcd, lcm, isPrime, factorial, fibonacci.\nexport function gcd(a: number, b: number): number {\n  a = Math.abs(a); b = Math.abs(b)\n  while (b) { [a, b] = [b, a % b] }\n  return a\n}\n\nexport function lcm(a: number, b: number): number {\n  return a === 0 || b === 0 ? 0 : Math.abs(a * b) / gcd(a, b)\n}\n\nexport function isPrime(n: number): boolean {\n  if (n < 2) return false\n  if (n < 4) return true\n  if (n % 2 === 0 || n % 3 === 0) return false\n  for (let i = 5; i * i <= n; i += 6) if (n % i === 0 || n % (i + 2) === 0) return false\n  return true\n}\n\nexport function factorial(n: number): number {\n  if (n < 0) throw new Error('negative factorial')\n  return n <= 1 ? 1 : n * factorial(n - 1)\n}\n\nexport function fibonacci(n: number): number {\n  if (n < 0) throw new Error('negative fibonacci')\n  if (n <= 1) return n\n  let a = 0, b = 1\n  for (let i = 2; i <= n; i++) [a, b] = [b, a + b]\n  return b\n}\n"

registerSkill({
  id: "number-theory",
  summary: "gcd, lcm, isPrime, factorial, fibonacci.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bgcd\\b|greatest.*common.*divisor", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\blcm\\b|least.*common.*multiple", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bisPrime\\b|prime.*number.*check", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bfactorial\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bfibonacci\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bgcd.*lcm|factorial.*fibonacci", 'i'))) sc += 0.55
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/numberTheory.ts", content: IMPL }]
  },
})
