// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — parseAcceptHeader parses an HTTP Accept header and returns media types sorted by q-value descending.\nexport function parseAcceptHeader(h) {\n  return h.split(',').map(s => {\n    const [type, ...params] = s.trim().split(';').map(x=>x.trim())\n    const qp = params.find(p=>p.startsWith('q='))\n    const q = qp ? parseFloat(qp.slice(2)) : 1\n    return { type, q }\n  }).sort((a,b)=>b.q-a.q).map(x=>x.type)\n}\n"

registerSkill({
  id: "parse-accept-header",
  summary: "parseAcceptHeader parses an HTTP Accept header and returns media types sorted by q-value descending.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bparseAcceptHeader\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("accept.*header|http.*accept.*parse", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/parseAcceptHeader.ts", content: IMPL }]
  },
})
