// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — parseRangeSpec expands a range specification like \"1-3,5,7-8\" into a sorted deduplicated array of numbers.\nexport function parseRangeSpec(spec) {\n  const out = new Set()\n  for (const part of spec.split(',').map(s=>s.trim()).filter(Boolean)) {\n    const dash = part.indexOf('-')\n    if (dash > 0) {\n      const lo = parseInt(part.slice(0,dash)), hi = parseInt(part.slice(dash+1))\n      if (!isNaN(lo) && !isNaN(hi)) for (let i=lo;i<=hi;i++) out.add(i)\n    } else { const n = parseInt(part); if (!isNaN(n)) out.add(n) }\n  }\n  return [...out].sort((a,b)=>a-b)\n}\n"

registerSkill({
  id: "parse-range-spec",
  summary: "parseRangeSpec expands a range specification like \"1-3,5,7-8\" into a sorted deduplicated array of numbers.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bparseRangeSpec\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("expand.*range.*spec|range.*1.3.*5", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/parseRangeSpec.ts", content: IMPL }]
  },
})
