// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — parseSemverParts splits a semver string and compareSemver compares two versions returning -1, 0, or 1.\nexport function parseSemverParts(v) {\n  const m = v.replace(/^v/,'').match(/^(\\d+)\\.(\\d+)\\.(\\d+)(?:-([\\w.]+))?$/)\n  if (!m) return null\n  return { major: +m[1], minor: +m[2], patch: +m[3], prerelease: m[4] ?? '' }\n}\nexport function compareSemver(a, b) {\n  const pa = parseSemverParts(a), pb = parseSemverParts(b)\n  if (!pa || !pb) throw new Error('invalid semver')\n  for (const k of ['major','minor','patch']) {\n    if (pa[k] < pb[k]) return -1\n    if (pa[k] > pb[k]) return 1\n  }\n  if (!pa.prerelease && pb.prerelease) return 1\n  if (pa.prerelease && !pb.prerelease) return -1\n  return pa.prerelease < pb.prerelease ? -1 : pa.prerelease > pb.prerelease ? 1 : 0\n}\n"

registerSkill({
  id: "parse-semver-parts",
  summary: "parseSemverParts splits a semver string and compareSemver compares two versions returning -1, 0, or 1.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bparseSemverParts\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("\\bcompareSemver\\b", 'i'))) sc += 0.7
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/parseSemverParts.ts", content: IMPL }]
  },
})
