// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — percentileValue returns the p-th percentile (0 to 100) of a numeric array using linear interpolation between closest ranks on a sorted copy.\nexport function percentileValue(arr: number[], p: number): number {\n  const n = arr.length;\n  if (n === 0) return NaN;\n  const s = [...arr].sort((a, b) => a - b);\n  if (n === 1) return s[0];\n  const rank = (p / 100) * (n - 1);\n  const lo = Math.floor(rank);\n  const hi = Math.ceil(rank);\n  if (lo === hi) return s[lo];\n  const frac = rank - lo;\n  return s[lo] + frac * (s[hi] - s[lo]);\n}\n\n"

registerSkill({
  id: "percentile-value-interp",
  summary: "percentileValue returns the p-th percentile (0 to 100) of a numeric array using linear interpolation between closest ranks on a sorted copy.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpercentileValue\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("percentile", 'i'))) sc += 0.2
  if (s.has(new RegExp("linear interpolation", 'i'))) sc += 0.15
  if (s.has(new RegExp("sorted copy", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/percentileValueInterp.ts", content: IMPL }]
  },
})
