// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Test whether a 2D point lies inside a polygon using ray casting with pointInPolygon; uses the half-open crossing rule so points exactly on certain edges may return true.\nexport function pointInPolygon(px: number, py: number, polygon: [number, number][]): boolean {\n  let inside = false;\n  const n = polygon.length;\n  for (let i = 0, j = n - 1; i < n; j = i++) {\n    const [xi, yi] = polygon[i];\n    const [xj, yj] = polygon[j];\n    const intersect = ((yi > py) !== (yj > py)) && (px < ((xj - xi) * (py - yi)) / (yj - yi) + xi);\n    if (intersect) inside = !inside;\n  }\n  return inside;\n}\n\n"

registerSkill({
  id: "point-in-polygon-raycast",
  summary: "Test whether a 2D point lies inside a polygon using ray casting with pointInPolygon; uses the half-open crossing rule so points exactly on certain edges may return true.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpointInPolygon\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("ray cast", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bpolygon\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("\\binside\\b", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/pointInPolygon.ts", content: IMPL }]
  },
})
