// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — quarterOf returns the calendar quarter (1 to 4) of a Date using UTC month.\nexport function quarterOf(date: Date): number { return Math.ceil((date.getUTCMonth() + 1) / 3) }\n"

registerSkill({
  id: "quarter-of",
  summary: "quarterOf returns the calendar quarter (1 to 4) of a Date using UTC month.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bquarterOf\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("calendar quarter|quarter.*date", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/quarterOf.ts", content: IMPL }]
  },
})
