// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — rabinKarpAll returns all start indices where a pattern occurs in text (overlaps allowed) using Rabin-Karp hashing.\nexport function rabinKarpAll(text: string, pattern: string): number[] {\n  const res: number[] = []\n  const n = text.length, m = pattern.length\n  if (m === 0 || m > n) return res\n  const B = 256, MOD = 1000000007\n  let ph = 0, th = 0, pow = 1\n  for (let i = 0; i < m; i++) {\n    ph = (ph * B + pattern.charCodeAt(i)) % MOD\n    th = (th * B + text.charCodeAt(i)) % MOD\n    if (i) pow = (pow * B) % MOD\n  }\n  for (let i = 0; i + m <= n; i++) {\n    if (ph === th && text.substr(i, m) === pattern) res.push(i)\n    if (i + m < n) {\n      let rm = th - (text.charCodeAt(i) * pow) % MOD\n      rm = ((rm % MOD) + MOD) % MOD\n      th = (rm * B + text.charCodeAt(i + m)) % MOD\n    }\n  }\n  return res\n}\n"

registerSkill({
  id: "rabin-karp-all",
  summary: "rabinKarpAll returns all start indices where a pattern occurs in text (overlaps allowed) using Rabin-Karp hashing.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brabinKarpAll\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("rabin.?karp|all.*occurrence|all match.*indices", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/rabinKarpAll.ts", content: IMPL }]
  },
})
