// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Generate a random integer between min and max (inclusive).\nexport function randomInt(min: number, max: number, rng: () => number = Math.random): number {\n  return Math.floor(rng() * (max - min + 1)) + min\n}\n"

registerSkill({
  id: "random-int",
  summary: "Generate a random integer between min and max (inclusive).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brandom.*int|random.*integer", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\brandomInt\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\brandom.*number.*between|random.*between.*min.*max", 'i'))) sc += 0.5
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/randomInt.ts", content: IMPL }]
  },
})
