// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — randomStringFrom builds a string of a given length by drawing from an alphabet using an injected rng.\nexport function randomStringFrom(length, alphabet, rng) {\n  let out = ''\n  for (let i = 0; i < length; i++) out += alphabet[Math.floor(rng() * alphabet.length)]\n  return out\n}\n"

registerSkill({
  id: "random-string-from",
  summary: "randomStringFrom builds a string of a given length by drawing from an alphabet using an injected rng.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brandomStringFrom\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("random.*string.*alphabet|string.*from.*alphabet", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/randomStringFrom.ts", content: IMPL }]
  },
})
