// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Generate an array of numbers from start to end (exclusive), with optional step.\nexport function range(start: number, end?: number, step = 1): number[] {\n  if (end === undefined) { end = start; start = 0 }\n  const out: number[] = []\n  if (step > 0) for (let i = start; i < end; i += step) out.push(i)\n  else if (step < 0) for (let i = start; i > end; i += step) out.push(i)\n  return out\n}\n"

registerSkill({
  id: "range",
  summary: "Generate an array of numbers from start to end (exclusive), with optional step.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brange\\b.*number|number.*\\brange\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\brange\\(", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bsequence.*number|number.*sequence", 'i'))) sc += 0.2
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/range.ts", content: IMPL }]
  },
})
