// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — reservoirSampleSeeded picks k elements from an array via reservoir sampling using a seeded PRNG.\nexport function reservoirSampleSeeded(arr, k, seed) {\n  let s = seed | 0\n  const rng = () => { s = s + 0x6D2B79F5 | 0; let t = Math.imul(s ^ s >>> 15, 1 | s); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296 }\n  const res = arr.slice(0, k)\n  for (let i = k; i < arr.length; i++) { const j = Math.floor(rng() * (i + 1)); if (j < k) res[j] = arr[i] }\n  return res\n}\n"

registerSkill({
  id: "reservoir-sample-seeded",
  summary: "reservoirSampleSeeded picks k elements from an array via reservoir sampling using a seeded PRNG.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\breservoirSampleSeeded\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("reservoir.*sample|sample.*reservoir", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/reservoirSampleSeeded.ts", content: IMPL }]
  },
})
