// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — ResultBox is an Ok/Err result type with static ok and err, plus map, mapErr, unwrapOr, and isOk.\nexport class ResultBox<T, E> {\n  private constructor(private value: T | null, private error: E | null, private okFlag: boolean) {}\n  static ok<T, E = unknown>(v: T): ResultBox<T, E> { return new ResultBox<T, E>(v, null, true) }\n  static err<E, T = unknown>(e: E): ResultBox<T, E> { return new ResultBox<T, E>(null, e, false) }\n  map<U>(fn: (v: T) => U): ResultBox<U, E> { return this.okFlag ? ResultBox.ok<U, E>(fn(this.value as T)) : ResultBox.err<E, U>(this.error as E) }\n  mapErr<F>(fn: (e: E) => F): ResultBox<T, F> { return this.okFlag ? ResultBox.ok<T, F>(this.value as T) : ResultBox.err<F, T>(fn(this.error as E)) }\n  unwrapOr(def: T): T { return this.okFlag ? (this.value as T) : def }\n  isOk(): boolean { return this.okFlag }\n}\n"

registerSkill({
  id: "result-box",
  summary: "ResultBox is an Ok/Err result type with static ok and err, plus map, mapErr, unwrapOr, and isOk.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bResultBox\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("\\bmapErr\\b|\\bunwrapOr\\b|\\bisOk\\b", 'i'))) sc += 0.7
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/resultBox.ts", content: IMPL }]
  },
})
