// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Retry an async callback with exponential backoff (N max attempts).\nexport interface RetryOpts {\n  attempts?: number\n  delayMs?: number\n  backoff?: number\n  onRetry?: (err: unknown, attempt: number) => void\n}\n\nexport async function retry<T>(fn: () => Promise<T>, opts: RetryOpts = {}): Promise<T> {\n  const { attempts = 3, delayMs = 100, backoff = 2, onRetry } = opts\n  let lastErr: unknown\n  for (let i = 0; i < attempts; i++) {\n    try { return await fn() } catch (err) {\n      lastErr = err\n      if (i < attempts - 1) {\n        onRetry?.(err, i + 1)\n        await new Promise(r => setTimeout(r, delayMs * backoff ** i))\n      }\n    }\n  }\n  throw lastErr\n}\n"

registerSkill({
  id: "retry",
  summary: "Retry an async callback with exponential backoff (N max attempts).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bretry\\b.*async|async.*\\bretry\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bretry\\b.*backoff|backoff.*\\bretry\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bexponential.*backoff\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bretry\\b.*attempt|attempt.*\\bretry\\b", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/retry.ts", content: IMPL }]
  },
})
