// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — reverseBits32 reverses the 32 bits of an unsigned integer and returns an unsigned result.\nexport function reverseBits32(n: number): number {\n  let r = 0\n  for (let i = 0; i < 32; i++) r = r * 2 + ((n >>> i) & 1)\n  return r >>> 0\n}\n"

registerSkill({
  id: "reverse-bits-32",
  summary: "reverseBits32 reverses the 32 bits of an unsigned integer and returns an unsigned result.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\breverseBits32\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("reverse.*bits|bit.*reversal", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/reverseBits32.ts", content: IMPL }]
  },
})
