// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Reverse a string.\nexport function reverseString(str: string): string {\n  return str.split('').reverse().join('')\n}\n"

registerSkill({
  id: "reverse-string",
  summary: "Reverse a string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\breverse.*string|string.*revers", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\breverseString\\b", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/reverseString.ts", content: IMPL }]
  },
})
