// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — rot47 applies ROT-47 over printable ASCII characters 33 to 126; it is an involution.\nexport function rot47(s: string): string {\n  return s.replace(/[!-~]/g, c => String.fromCharCode(33 + (c.charCodeAt(0) - 33 + 47) % 94))\n}\n"

registerSkill({
  id: "rot47",
  summary: "rot47 applies ROT-47 over printable ASCII characters 33 to 126; it is an involution.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\brot47\\b|\\brot.?47\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("printable.*ascii.*rotate", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/rot47.ts", content: IMPL }]
  },
})
