// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — sampleWithoutReplacement draws k distinct elements from an array using a seeded PRNG, without mutating.\nexport function sampleWithoutReplacement(arr, k, seed) {\n  if (k >= arr.length) return arr.slice()\n  let s = seed | 0\n  const rng = () => { s = s + 0x6D2B79F5 | 0; let t = Math.imul(s ^ s >>> 15, 1 | s); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296 }\n  const pool = arr.slice()\n  const out = []\n  for (let i = 0; i < k; i++) { const j = i + Math.floor(rng() * (pool.length - i));[pool[i], pool[j]] = [pool[j], pool[i]]; out.push(pool[i]) }\n  return out\n}\n"

registerSkill({
  id: "sample-without-replacement",
  summary: "sampleWithoutReplacement draws k distinct elements from an array using a seeded PRNG, without mutating.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsampleWithoutReplacement\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("sample.*without.*replacement|draw.*k.*distinct", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/sampleWithoutReplacement.ts", content: IMPL }]
  },
})
