// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Lightweight runtime schema validation: required, type, min, max, pattern.\nexport interface FieldRule {\n  type?: 'string' | 'number' | 'boolean' | 'array' | 'object'\n  required?: boolean\n  min?: number; max?: number\n  pattern?: RegExp\n  enum?: unknown[]\n  items?: FieldRule\n}\nexport type Schema = Record<string, FieldRule>\nexport interface ValidationResult { valid: boolean; errors: string[] }\n\nexport function validate(data: Record<string, unknown>, schema: Schema): ValidationResult {\n  const errors: string[] = []\n  for (const [key, rule] of Object.entries(schema)) {\n    const val = data[key]\n    if (rule.required && (val === undefined || val === null || val === '')) {\n      errors.push(`${key}: required`); continue\n    }\n    if (val === undefined || val === null) continue\n    if (rule.type) {\n      const actual = Array.isArray(val) ? 'array' : typeof val\n      if (actual !== rule.type) { errors.push(`${key}: expected ${rule.type}, got ${actual}`); continue }\n    }\n    if (rule.pattern && typeof val === 'string' && !rule.pattern.test(val)) errors.push(`${key}: pattern mismatch`)\n    if (rule.enum && !rule.enum.includes(val)) errors.push(`${key}: must be one of ${rule.enum.join(', ')}`)\n    if (typeof val === 'number') {\n      if (rule.min !== undefined && val < rule.min) errors.push(`${key}: min ${rule.min}`)\n      if (rule.max !== undefined && val > rule.max) errors.push(`${key}: max ${rule.max}`)\n    }\n    if (typeof val === 'string') {\n      if (rule.min !== undefined && val.length < rule.min) errors.push(`${key}: minLength ${rule.min}`)\n      if (rule.max !== undefined && val.length > rule.max) errors.push(`${key}: maxLength ${rule.max}`)\n    }\n  }\n  return { valid: errors.length === 0, errors }\n}\n\nexport function createSchema(schema: Schema) {\n  return (data: Record<string, unknown>) => validate(data, schema)\n}\n"

registerSkill({
  id: "schema-validate",
  summary: "Lightweight runtime schema validation: required, type, min, max, pattern.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bschema.*validat|validat.*schema", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\bruntime.*validat|validat.*runtime", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bcreateSchema\\b|\\bvalidate\\b.*object.*schema", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bzod.*like|yup.*like|simple.*validat", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/schemaValidate.ts", content: IMPL }]
  },
})
