// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Determine whether two 2D line segments intersect using segmentsIntersect, returning true for both proper crossings and touching or collinear-overlapping cases.\ntype Pt = [number, number];\nfunction cross(o: Pt, a: Pt, b: Pt): number {\n  return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);\n}\nfunction onSeg(a: Pt, b: Pt, c: Pt): boolean {\n  return Math.min(a[0], b[0]) <= c[0] && c[0] <= Math.max(a[0], b[0]) && Math.min(a[1], b[1]) <= c[1] && c[1] <= Math.max(a[1], b[1]);\n}\nexport function segmentsIntersect(p1: Pt, p2: Pt, p3: Pt, p4: Pt): boolean {\n  const d1 = cross(p3, p4, p1);\n  const d2 = cross(p3, p4, p2);\n  const d3 = cross(p1, p2, p3);\n  const d4 = cross(p1, p2, p4);\n  if (((d1 > 0 && d2 < 0) || (d1 < 0 && d2 > 0)) && ((d3 > 0 && d4 < 0) || (d3 < 0 && d4 > 0))) return true;\n  if (d1 === 0 && onSeg(p3, p4, p1)) return true;\n  if (d2 === 0 && onSeg(p3, p4, p2)) return true;\n  if (d3 === 0 && onSeg(p1, p2, p3)) return true;\n  if (d4 === 0 && onSeg(p1, p2, p4)) return true;\n  return false;\n}\n\n"

registerSkill({
  id: "segments-intersect-2d",
  summary: "Determine whether two 2D line segments intersect using segmentsIntersect, returning true for both proper crossings and touching or collinear-overlapping cases.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsegmentsIntersect\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bsegments?\\b", 'i'))) sc += 0.2
  if (s.has(new RegExp("\\bintersect\\b", 'i'))) sc += 0.15
  if (s.has(new RegExp("touching", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/segmentsIntersect.ts", content: IMPL }]
  },
})
