// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Parse and compare semantic version strings.\nexport interface SemVer { major: number; minor: number; patch: number; pre?: string }\n\nexport function parseSemver(v: string): SemVer | null {\n  const m = v.replace(/^v/, '').match(/^(\\d+)\\.(\\d+)\\.(\\d+)(?:-([\\w.]+))?$/)\n  if (!m) return null\n  return { major: +m[1], minor: +m[2], patch: +m[3], pre: m[4] }\n}\n\nexport function isValidSemver(v: string): boolean {\n  return parseSemver(v) !== null\n}\n\nexport function compareSemver(a: string, b: string): -1 | 0 | 1 {\n  const pa = parseSemver(a), pb = parseSemver(b)\n  if (!pa || !pb) throw new Error('invalid semver')\n  for (const k of ['major', 'minor', 'patch'] as const) {\n    if (pa[k] < pb[k]) return -1\n    if (pa[k] > pb[k]) return 1\n  }\n  if (!pa.pre && pb.pre) return 1\n  if (pa.pre && !pb.pre) return -1\n  if (pa.pre && pb.pre) return pa.pre < pb.pre ? -1 : pa.pre > pb.pre ? 1 : 0\n  return 0\n}\n"

registerSkill({
  id: "semver",
  summary: "Parse and compare semantic version strings.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsemver\\b|semantic.*version", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bparseSemver\\b|\\bcompareSemver\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bversion.*compar|compar.*version", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/semver.ts", content: IMPL }]
  },
})
