// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Array set operations: intersection, difference, union.\nexport function intersection<T>(a: T[], b: T[]): T[] {\n  const setB = new Set(b)\n  return [...new Set(a)].filter(x => setB.has(x))\n}\n\nexport function difference<T>(a: T[], b: T[]): T[] {\n  const setB = new Set(b)\n  return [...new Set(a)].filter(x => !setB.has(x))\n}\n\nexport function union<T>(a: T[], b: T[]): T[] {\n  return [...new Set([...a, ...b])]\n}\n"

registerSkill({
  id: "set-ops",
  summary: "Array set operations: intersection, difference, union.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bintersection\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bdifference\\b.*array|array.*\\bdifference\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bunion\\b.*array|array.*\\bunion\\b", 'i'))) sc += 0.35
  if (s.has(new RegExp("\\bset.*operation|intersection.*difference", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/setOps.ts", content: IMPL }]
  },
})
