// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — shuffleSeeded performs a deterministic Fisher-Yates shuffle of an array using a seeded PRNG, without mutating the input.\nexport function shuffleSeeded(arr, seed) {\n  let s = seed | 0\n  const rng = () => { s = s + 0x6D2B79F5 | 0; let t = Math.imul(s ^ s >>> 15, 1 | s); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296 }\n  const out = arr.slice()\n  for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1));[out[i], out[j]] = [out[j], out[i]] }\n  return out\n}\n"

registerSkill({
  id: "shuffle-seeded",
  summary: "shuffleSeeded performs a deterministic Fisher-Yates shuffle of an array using a seeded PRNG, without mutating the input.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bshuffleSeeded\\b", 'i'))) sc += 0.9
  if (s.has(new RegExp("deterministic.*Fisher.?Yates|seeded.*shuffle", 'i'))) sc += 0.7
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/shuffleSeeded.ts", content: IMPL }]
  },
})
