// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — slugifyUnicode converts a string to a lowercase ASCII slug: spaces become hyphens, non-alphanumeric is stripped, hyphens are collapsed and trimmed.\nexport function slugifyUnicode(s: string): string {\n  return s.normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase()\n    .replace(/\\s+/g,'-').replace(/[^a-z0-9-]/g,'').replace(/-+/g,'-').replace(/^-|-$/g,'')\n}\n"

registerSkill({
  id: "slugify-unicode",
  summary: "slugifyUnicode converts a string to a lowercase ASCII slug: spaces become hyphens, non-alphanumeric is stripped, hyphens are collapsed and trimmed.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bslugifyUnicode\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("slugif.*unicode|unicode.*slug", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/slugifyUnicode.ts", content: IMPL }]
  },
})
