// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Convert a string to snake_case.\nexport function snakeCase(str: string): string {\n  return str\n    .replace(/([A-Z])/g, '_$1')\n    .replace(/[-\\s]+/g, '_')\n    .replace(/_+/g, '_')\n    .replace(/^_|_$/g, '')\n    .toLowerCase()\n}\n"

registerSkill({
  id: "snake-case",
  summary: "Convert a string to snake_case.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsnake[- ]?case\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bsnakeCase\\b", 'i'))) sc += 0.3
  if (s.has(new RegExp("\\bto[- ]?snake\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bunder[_\\s]?score[- ]?case\\b", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/snakeCase.ts", content: IMPL }]
  },
})
