// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — LIFO stack with push, pop, peek, size, isEmpty.\nexport class Stack<T> {\n  private items: T[] = []\n\n  push(item: T): void { this.items.push(item) }\n  pop(): T | undefined { return this.items.pop() }\n  peek(): T | undefined { return this.items[this.items.length - 1] }\n  size(): number { return this.items.length }\n  isEmpty(): boolean { return this.items.length === 0 }\n  toArray(): T[] { return [...this.items] }\n  clear(): void { this.items = [] }\n}\n"

registerSkill({
  id: "stack",
  summary: "LIFO stack with push, pop, peek, size, isEmpty.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bstack\\b.*(?:push|pop|peek|lifo)", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\blifo\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bStack\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/stack.ts", content: IMPL }]
  },
})
