// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — padLeft, padRight, padBoth — pad a string to a target length.\nexport function padLeft(str: string, len: number, char = ' '): string {\n  if (str.length >= len) return str\n  return char.repeat(Math.ceil((len - str.length) / char.length)).slice(0, len - str.length) + str\n}\n\nexport function padRight(str: string, len: number, char = ' '): string {\n  if (str.length >= len) return str\n  return str + char.repeat(Math.ceil((len - str.length) / char.length)).slice(0, len - str.length)\n}\n\nexport function padBoth(str: string, len: number, char = ' '): string {\n  if (str.length >= len) return str\n  const total = len - str.length\n  const left = Math.floor(total / 2)\n  return padLeft(padRight(str, str.length + (total - left), char), len, char)\n}\n"

registerSkill({
  id: "string-padding",
  summary: "padLeft, padRight, padBoth — pad a string to a target length.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bpadLeft\\b|\\bleft.*pad\\b|\\bpad.*left\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bpadRight\\b|\\bright.*pad\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bpadBoth\\b|\\bcenter.*pad|\\bpad.*center", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\bpad.*string|string.*pad", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/stringPadding.ts", content: IMPL }]
  },
})
