// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — isAlpha, isAlphanumeric, isNumeric, isHexColor, isIPv4, isPort.\nexport function isAlpha(s: string): boolean { return /^[a-zA-Z]+$/.test(s) }\nexport function isAlphanumeric(s: string): boolean { return /^[a-zA-Z0-9]+$/.test(s) }\nexport function isNumeric(s: string): boolean { return s.length > 0 && !isNaN(Number(s)) && !isNaN(parseFloat(s)) }\nexport function isHexColor(s: string): boolean { return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(s) }\nexport function isIPv4(s: string): boolean {\n  const parts = s.split('.')\n  return parts.length === 4 && parts.every(p => /^\\d+$/.test(p) && +p >= 0 && +p <= 255)\n}\nexport function isPort(n: number): boolean { return Number.isInteger(n) && n >= 0 && n <= 65535 }\n"

registerSkill({
  id: "string-validators",
  summary: "isAlpha, isAlphanumeric, isNumeric, isHexColor, isIPv4, isPort.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisAlpha\\b|\\bisAlphanumeric\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bisHexColor\\b|\\bhex.*color.*valid", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bisIPv4\\b|\\bip.*address.*valid", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bisPort\\b|\\bport.*number.*valid", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bstring.*validator|validate.*string.*type", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/stringValidators.ts", content: IMPL }]
  },
})
