// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — subsetSumExists reports whether some subset of non-negative integers sums to a target.\nexport function subsetSumExists(arr: number[], target: number): boolean {\n  if (target === 0) return true\n  if (target < 0) return false\n  const dp = new Array(target + 1).fill(false)\n  dp[0] = true\n  for (const x of arr)\n    for (let t = target; t >= x; t--)\n      if (dp[t - x]) dp[t] = true\n  return dp[target]\n}\n"

registerSkill({
  id: "subset-sum-exists",
  summary: "subsetSumExists reports whether some subset of non-negative integers sums to a target.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bsubsetSumExists\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("subset sum", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/subsetSumExists.ts", content: IMPL }]
  },
})
