// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Simple mustache-style template engine: replace {{key}} placeholders.\nexport function renderTemplate(template: string, vars: Record<string, unknown>): string {\n  return template.replace(/\\{\\{\\s*([\\w.]+)\\s*\\}\\}/g, (_, key) => {\n    const val = key.split('.').reduce((obj: unknown, k: string) =>\n      obj != null && typeof obj === 'object' ? (obj as Record<string, unknown>)[k] : undefined, vars)\n    return val === undefined ? '' : String(val)\n  })\n}\n"

registerSkill({
  id: "template-engine",
  summary: "Simple mustache-style template engine: replace {{key}} placeholders.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btemplate.*engine|mustache\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\brender.*template|template.*render", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\b\\{\\{.*\\}\\}|placeholder.*replac", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/templateEngine.ts", content: IMPL }]
  },
})
