// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — wordFrequency, readingTime, sentenceCount, charCount, longestWord.\nexport function wordFrequency(text: string): Map<string, number> {\n  const map = new Map<string, number>()\n  for (const w of text.toLowerCase().match(/[a-z]+/g) ?? []) map.set(w, (map.get(w) ?? 0) + 1)\n  return map\n}\n\nexport function readingTime(text: string, wpm = 200): number {\n  const count = (text.match(/[a-z]+/gi) ?? []).length\n  return Math.ceil(count / wpm)\n}\n\nexport function sentenceCount(text: string): number {\n  return (text.match(/[.!?]+/g) ?? []).length\n}\n\nexport function longestWord(text: string): string {\n  const words = text.match(/[a-zA-Z]+/g) ?? []\n  return words.reduce((a, b) => b.length > a.length ? b : a, '')\n}\n"

registerSkill({
  id: "text-analysis",
  summary: "wordFrequency, readingTime, sentenceCount, charCount, longestWord.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bword.*frequency|frequency.*word", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\breading.*time|estimate.*read", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\btext.*analysis|analyse.*text", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\blongestWord\\b|\\bsentenceCount\\b", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/textAnalysis.ts", content: IMPL }]
  },
})
