// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — titleCaseSmart applies title case but keeps small words (a, an, the, of, and, or, in, on, to) lowercase unless first word.\nconst SMALL = new Set(['a','an','the','of','and','or','in','on','to','for','but','nor'])\nexport function titleCaseSmart(s: string): string {\n  return s.split(' ').map((w,i) => {\n    const lower = w.toLowerCase()\n    return (i === 0 || !SMALL.has(lower)) ? lower.replace(/^./, c=>c.toUpperCase()) : lower\n  }).join(' ')\n}\n"

registerSkill({
  id: "title-case-smart",
  summary: "titleCaseSmart applies title case but keeps small words (a, an, the, of, and, or, in, on, to) lowercase unless first word.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btitleCaseSmart\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("smart.*title.*case|title.*case.*small.*word", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/titleCaseSmart.ts", content: IMPL }]
  },
})
