// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — toHexString converts an array of bytes (0-255) to a lowercase hex string and fromHexString converts back.\nexport function toHexString(bytes: number[]): string {\n  return bytes.map(b => (b & 0xFF).toString(16).padStart(2,'0')).join('')\n}\nexport function fromHexString(hex: string): number[] {\n  const out: number[] = []\n  for (let i = 0; i < hex.length; i += 2) out.push(parseInt(hex.slice(i,i+2),16))\n  return out\n}\n"

registerSkill({
  id: "to-hex-string",
  summary: "toHexString converts an array of bytes (0-255) to a lowercase hex string and fromHexString converts back.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btoHexString\\b|\\bfromHexString\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("bytes.*hex|hex.*bytes", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/toHexString.ts", content: IMPL }]
  },
})
