// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — topoSortLevels groups nodes into Kahn levels (each inner array sorted ascending); returns empty outer array if graph is cyclic.\nexport function topoSortLevels(n, edges) {\n  const indeg = new Array(n).fill(0)\n  const adj = Array.from({ length: n }, () => [])\n  for (const [u, v] of edges) { adj[u].push(v); indeg[v]++ }\n  let frontier = []\n  for (let i = 0; i < n; i++) if (indeg[i] === 0) frontier.push(i)\n  frontier.sort((a, b) => a - b)\n  const levels = []\n  let processed = 0\n  while (frontier.length) {\n    levels.push([...frontier]); processed += frontier.length\n    const next = []\n    for (const u of frontier) for (const v of adj[u]) if (--indeg[v] === 0) next.push(v)\n    frontier = next.sort((a, b) => a - b)\n  }\n  return processed === n ? levels : []\n}\n"

registerSkill({
  id: "topo-sort-levels",
  summary: "topoSortLevels groups nodes into Kahn levels (each inner array sorted ascending); returns empty outer array if graph is cyclic.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btopoSortLevels\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("topological.*level|level.*kahn", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/topoSortLevels.ts", content: IMPL }]
  },
})
