// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — topoOrderKahn returns a topological order (smallest id first on ties) via Kahn, or an empty array if the graph has a cycle.\nexport function topoOrderKahn(n, edges) {\n  const indeg = new Array(n).fill(0)\n  const adj = Array.from({ length: n }, () => [])\n  for (const [u, v] of edges) { adj[u].push(v); indeg[v]++ }\n  const avail = new Set()\n  for (let i = 0; i < n; i++) if (indeg[i] === 0) avail.add(i)\n  const order = []\n  while (avail.size) {\n    const u = Math.min(...avail); avail.delete(u); order.push(u)\n    for (const v of adj[u]) if (--indeg[v] === 0) avail.add(v)\n  }\n  return order.length === n ? order : []\n}\n"

registerSkill({
  id: "topo-order-kahn",
  summary: "topoOrderKahn returns a topological order (smallest id first on ties) via Kahn, or an empty array if the graph has a cycle.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btopoOrderKahn\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("topological.*kahn|topological order", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/topoOrderKahn.ts", content: IMPL }]
  },
})
