// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — transitiveClosure returns a reachability matrix where entry [i][j] is true if j is reachable from i (a node reaches itself).\nexport function transitiveClosure(n, edges) {\n  const reach = Array.from({ length: n }, (_, i) => {\n    const r = new Array(n).fill(false); r[i] = true; return r\n  })\n  for (const [u, v] of edges) reach[u][v] = true\n  for (let k = 0; k < n; k++)\n    for (let i = 0; i < n; i++)\n      for (let j = 0; j < n; j++)\n        if (reach[i][k] && reach[k][j]) reach[i][j] = true\n  return reach\n}\n"

registerSkill({
  id: "transitive-closure",
  summary: "transitiveClosure returns a reachability matrix where entry [i][j] is true if j is reachable from i (a node reaches itself).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btransitiveClosure\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("transitive.*closure|reachability.*matrix", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/transitiveClosure.ts", content: IMPL }]
  },
})
