// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Truncate a string to maxLength, appending an ellipsis if cut.\nexport function truncate(str: string, maxLength: number, ellipsis = '...'): string {\n  if (str.length <= maxLength) return str\n  return str.slice(0, maxLength - ellipsis.length) + ellipsis\n}\n"

registerSkill({
  id: "truncate",
  summary: "Truncate a string to maxLength, appending an ellipsis if cut.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\btruncate\\b", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bellipsis\\b", 'i'))) sc += 0.3
  if (s.has(new RegExp("\\bclip.*string|string.*clip\\b", 'i'))) sc += 0.2
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/truncate.ts", content: IMPL }]
  },
})
