// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Runtime type-checking guards: isString, isNumber, isArray, isNil, isEmpty.\nexport function isString(v: unknown): v is string { return typeof v === 'string' }\nexport function isNumber(v: unknown): v is number { return typeof v === 'number' && !isNaN(v) }\nexport function isBoolean(v: unknown): v is boolean { return typeof v === 'boolean' }\nexport function isArray(v: unknown): v is unknown[] { return Array.isArray(v) }\nexport function isObject(v: unknown): v is Record<string, unknown> {\n  return v !== null && typeof v === 'object' && !Array.isArray(v)\n}\nexport function isNil(v: unknown): v is null | undefined { return v === null || v === undefined }\nexport function isEmpty(v: unknown): boolean {\n  if (isNil(v)) return true\n  if (typeof v === 'string' || Array.isArray(v)) return v.length === 0\n  if (isObject(v)) return Object.keys(v).length === 0\n  return false\n}\n"

registerSkill({
  id: "type-guards",
  summary: "Runtime type-checking guards: isString, isNumber, isArray, isNil, isEmpty.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bisString\\b|\\bisNumber\\b|\\bisArray\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\btype.*guard|runtime.*type.*check", 'i'))) sc += 0.45
  if (s.has(new RegExp("\\bisNil\\b|\\bisEmpty\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\btype.*check.*util", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/typeGuards.ts", content: IMPL }]
  },
})
