// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Return a new array with duplicate values removed (preserves order).\nexport function unique<T>(arr: T[]): T[] {\n  return [...new Set(arr)]\n}\n\nexport function uniqueBy<T>(arr: T[], key: (item: T) => unknown): T[] {\n  const seen = new Set<unknown>()\n  return arr.filter(item => {\n    const k = key(item)\n    if (seen.has(k)) return false\n    seen.add(k)\n    return true\n  })\n}\n"

registerSkill({
  id: "unique",
  summary: "Return a new array with duplicate values removed (preserves order).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bunique\\b", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bdedupe\\b|\\bdedup\\b|\\bde-dup\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bremove.*duplicate|duplicate.*remov", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\buniqueBy\\b", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/unique.ts", content: IMPL }]
  },
})
