// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — parseURL, buildURL, getQueryParam, updateQueryParam, removeQueryParam.\nexport interface ParsedURL {\n  protocol: string; host: string; pathname: string\n  search: string; hash: string; params: Record<string, string>\n}\n\nexport function parseURL(url: string): ParsedURL | null {\n  try {\n    const u = new URL(url)\n    const params: Record<string, string> = {}\n    u.searchParams.forEach((v, k) => { params[k] = v })\n    return { protocol: u.protocol, host: u.host, pathname: u.pathname, search: u.search, hash: u.hash, params }\n  } catch { return null }\n}\n\nexport function buildURL(base: string, params: Record<string, string>): string {\n  try {\n    const u = new URL(base)\n    Object.entries(params).forEach(([k, v]) => u.searchParams.set(k, v))\n    return u.toString()\n  } catch { return base }\n}\n\nexport function getQueryParam(url: string, key: string): string | null {\n  try { return new URL(url).searchParams.get(key) } catch { return null }\n}\n\nexport function updateQueryParam(url: string, key: string, value: string): string {\n  try {\n    const u = new URL(url); u.searchParams.set(key, value); return u.toString()\n  } catch { return url }\n}\n"

registerSkill({
  id: "url-utils",
  summary: "parseURL, buildURL, getQueryParam, updateQueryParam, removeQueryParam.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bparse.*url|url.*parse", 'i'))) sc += 0.55
  if (s.has(new RegExp("\\bbuildURL\\b|\\bbuild.*url\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bquery.*param.*update|update.*query.*param", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\bgetQueryParam\\b|\\burl.*util", 'i'))) sc += 0.45
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/urlUtils.ts", content: IMPL }]
  },
})
