// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Generate a UUID v4 string.\nexport function uuidv4(): string {\n  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {\n    const r = Math.random() * 16 | 0\n    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16)\n  })\n}\n"

registerSkill({
  id: "uuid",
  summary: "Generate a UUID v4 string.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\buuid\\b.*generat|generat.*\\buuid\\b", 'i'))) sc += 0.65
  if (s.has(new RegExp("\\buuidv4\\b|\\buuid.*v4\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("\\brandom.*uuid|unique.*id.*generat", 'i'))) sc += 0.35
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/uuid.ts", content: IMPL }]
  },
})
