// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — weightedChoice picks an item from an array using cumulative weights and a random float r in [0,1).\nexport function weightedChoice(items, weights, r) {\n  const total = weights.reduce((a, b) => a + b, 0)\n  let cum = 0; const threshold = r * total\n  for (let i = 0; i < items.length; i++) { cum += weights[i]; if (threshold < cum) return items[i] }\n  return items[items.length - 1]\n}\n"

registerSkill({
  id: "weighted-choice",
  summary: "weightedChoice picks an item from an array using cumulative weights and a random float r in [0,1).",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bweightedChoice\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("weighted.*random|random.*weight", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/weightedChoice.ts", content: IMPL }]
  },
})
