// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Wrap text at a given column width without breaking words.\nexport function wordWrap(text: string, width: number): string {\n  const words = text.split(/\\s+/)\n  const lines: string[] = []\n  let current = ''\n  for (const word of words) {\n    if (!word) continue\n    if (!current) { current = word; continue }\n    if (current.length + 1 + word.length <= width) {\n      current += ' ' + word\n    } else {\n      lines.push(current)\n      current = word\n    }\n  }\n  if (current) lines.push(current)\n  return lines.join('\\n')\n}\n"

registerSkill({
  id: "word-wrap",
  summary: "Wrap text at a given column width without breaking words.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bword.*wrap|wrap.*text", 'i'))) sc += 0.7
  if (s.has(new RegExp("\\bwordWrap\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bline.*length.*wrap|column.*width.*wrap", 'i'))) sc += 0.4
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/wordWrap.ts", content: IMPL }]
  },
})
