// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — Zip two arrays into pairs; unzip pairs back into two arrays.\nexport function zip<A, B>(a: A[], b: B[]): [A, B][] {\n  const len = Math.min(a.length, b.length)\n  const out: [A, B][] = []\n  for (let i = 0; i < len; i++) out.push([a[i], b[i]])\n  return out\n}\n\nexport function unzip<A, B>(pairs: [A, B][]): [A[], B[]] {\n  const as: A[] = [], bs: B[] = []\n  for (const [a, b] of pairs) { as.push(a); bs.push(b) }\n  return [as, bs]\n}\n"

registerSkill({
  id: "zip",
  summary: "Zip two arrays into pairs; unzip pairs back into two arrays.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bzip\\b.*array|array.*\\bzip\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("\\bunzip\\b", 'i'))) sc += 0.4
  if (s.has(new RegExp("\\bzip.*pair|pair.*array", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/zip.ts", content: IMPL }]
  },
})
