// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — zipWith combines two arrays elementwise with a function, up to the shorter length.\nexport function zipWith<A, B, R>(a: A[], b: B[], fn: (x: A, y: B) => R): R[] {\n  const n = Math.min(a.length, b.length), out: R[] = []\n  for (let i = 0; i < n; i++) out.push(fn(a[i], b[i]))\n  return out\n}\n"

registerSkill({
  id: "zip-with",
  summary: "zipWith combines two arrays elementwise with a function, up to the shorter length.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bzipWith\\b", 'i'))) sc += 0.6
  if (s.has(new RegExp("zip.*function|elementwise.*combine", 'i'))) sc += 0.3
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/zipWith.ts", content: IMPL }]
  },
})
