// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = "// Synthesized by Crucible — zScoreNormalize maps each value of a numeric array to its z-score using the population standard deviation, returning all zeros when the standard deviation is zero.\nexport function zScoreNormalize(arr: number[]): number[] {\n  const n = arr.length;\n  if (n === 0) return [];\n  let mean = 0;\n  for (const x of arr) mean += x;\n  mean /= n;\n  let v = 0;\n  for (const x of arr) {\n    const d = x - mean;\n    v += d * d;\n  }\n  v /= n;\n  const sd = Math.sqrt(v);\n  if (sd === 0) return arr.map(() => 0);\n  return arr.map((x) => (x - mean) / sd);\n}\n\n"

registerSkill({
  id: "zscore-normalize",
  summary: "zScoreNormalize maps each value of a numeric array to its z-score using the population standard deviation, returning all zeros when the standard deviation is zero.",
  match(s: SpecFeatures): number {
    let sc = 0
  if (s.has(new RegExp("\\bzScoreNormalize\\b", 'i'))) sc += 0.5
  if (s.has(new RegExp("z-score", 'i'))) sc += 0.2
  if (s.has(new RegExp("population standard deviation", 'i'))) sc += 0.15
  if (s.has(new RegExp("numeric array", 'i'))) sc += 0.1
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? "src/zScoreNormalizeArr.ts", content: IMPL }]
  },
})
