import type { KnowledgeEntry } from "./types";

// ── Tier 1 Knowledge Base ────────────────────────────────────────────────────
// Expanded — 80+ entries across all major coding categories

export const TIER_1_ENTRIES: KnowledgeEntry[] = [
  // ── String Manipulation ──────────────────────────────────────────────────
  {
    id: 'string-split-join',
    tier: 1,
    category: 'algorithm',
    description: 'Split a string into parts and rejoin with a different delimiter.',
    structuralTokens: ['split', 'join', 'delimiter', 'separator'],
    antipatterns: ['manual-char-loop', 'regex-when-split-suffices'],
  },
  {
    id: 'string-trim-normalize',
    tier: 1,
    category: 'algorithm',
    description: 'Trim whitespace and normalize spacing in user input.',
    structuralTokens: ['trim', 'trimStart', 'trimEnd', 'replace', 'normalize'],
    antipatterns: ['no-trim-on-user-input', 'double-space-not-collapsed'],
  },
  {
    id: 'string-template-literal',
    tier: 1,
    category: 'algorithm',
    description: 'Use template literals for string interpolation instead of concatenation.',
    structuralTokens: ['template-literal', 'backtick', 'interpolation'],
    antipatterns: ['string-concat-with-plus', 'format-string-injection'],
  },
  {
    id: 'string-regex-extract',
    tier: 1,
    category: 'algorithm',
    description: 'Extract substrings using named capture groups in regex.',
    structuralTokens: ['match', 'exec', 'named-group', 'capture-group', 'regex'],
    antipatterns: ['unnamed-capture-groups', 'regex-without-flags', 'no-null-check-on-match'],
  },
  {
    id: 'string-pad-format',
    tier: 1,
    category: 'algorithm',
    description: 'Pad strings to fixed width for alignment or encoding.',
    structuralTokens: ['padStart', 'padEnd', 'padStart-8-0', 'toString-2'],
    antipatterns: ['manual-padding-loop', 'hardcoded-width'],
  },
  // ── Array Operations ─────────────────────────────────────────────────────
  {
    id: 'array-map-transform',
    tier: 1,
    category: 'algorithm',
    description: 'Transform every element of an array using map.',
    structuralTokens: ['map', 'arrow-function', 'return-value'],
    antipatterns: ['for-loop-push', 'mutating-original-array'],
  },
  {
    id: 'array-filter-predicate',
    tier: 1,
    category: 'algorithm',
    description: 'Filter array elements using a predicate function.',
    structuralTokens: ['filter', 'predicate', 'boolean-return'],
    antipatterns: ['for-loop-with-if-push', 'filter-then-map-when-flatmap-suffices'],
  },
  {
    id: 'array-reduce-aggregate',
    tier: 1,
    category: 'algorithm',
    description: 'Aggregate array values into a single result using reduce.',
    structuralTokens: ['reduce', 'accumulator', 'initial-value'],
    antipatterns: ['missing-initial-value', 'reduce-for-simple-sum'],
  },
  {
    id: 'array-dedup-set',
    tier: 1,
    category: 'algorithm',
    description: 'Remove duplicate values from an array using Set.',
    structuralTokens: ['Set', 'spread', 'unique', 'Array.from'],
    antipatterns: ['nested-loop-dedup', 'indexOf-dedup'],
  },
  {
    id: 'array-chunk',
    tier: 1,
    category: 'algorithm',
    description: 'Split an array into fixed-size chunks.',
    structuralTokens: ['slice', 'chunk', 'batch', 'Math.ceil'],
    antipatterns: ['off-by-one-chunk', 'mutating-splice'],
  },
  {
    id: 'array-flatten',
    tier: 1,
    category: 'algorithm',
    description: 'Flatten nested arrays using flat or flatMap.',
    structuralTokens: ['flat', 'flatMap', 'Infinity', 'depth'],
    antipatterns: ['manual-recursive-flatten', 'concat-spread-in-loop'],
  },
  {
    id: 'array-sort-comparator',
    tier: 1,
    category: 'algorithm',
    description: 'Sort arrays with a custom comparator function.',
    structuralTokens: ['sort', 'comparator', 'localeCompare', 'a-b'],
    antipatterns: ['sort-without-comparator', 'mutating-original-before-sort'],
  },
  {
    id: 'array-find-search',
    tier: 1,
    category: 'algorithm',
    description: 'Find the first matching element in an array.',
    structuralTokens: ['find', 'findIndex', 'predicate', 'undefined-check'],
    antipatterns: ['filter-index-0-instead-of-find', 'no-null-check-on-result'],
  },
  // ── Object Patterns ──────────────────────────────────────────────────────
  {
    id: 'object-spread-merge',
    tier: 1,
    category: 'algorithm',
    description: 'Merge objects using spread operator for immutable updates.',
    structuralTokens: ['spread', 'Object.assign', 'shallow-merge'],
    antipatterns: ['direct-mutation', 'deep-merge-without-recursion'],
  },
  {
    id: 'object-destructure',
    tier: 1,
    category: 'algorithm',
    description: 'Extract object properties using destructuring with defaults.',
    structuralTokens: ['destructuring', 'default-value', 'rename', 'rest'],
    antipatterns: ['repeated-dot-access', 'no-default-on-optional'],
  },
  {
    id: 'object-deep-clone',
    tier: 1,
    category: 'algorithm',
    description: 'Deep clone an object using structuredClone or JSON round-trip.',
    structuralTokens: ['structuredClone', 'JSON.parse', 'JSON.stringify', 'deep-copy'],
    antipatterns: ['shallow-copy-assumed-deep', 'clone-with-functions'],
  },
  {
    id: 'object-pick-omit',
    tier: 1,
    category: 'algorithm',
    description: 'Pick or omit specific keys from an object.',
    structuralTokens: ['pick', 'omit', 'Object.entries', 'Object.fromEntries'],
    antipatterns: ['manual-key-copy', 'delete-on-original'],
  },
  // ── HTTP / Fetch ─────────────────────────────────────────────────────────
  {
    id: 'fetch-get-json',
    tier: 1,
    category: 'api-pattern',
    description: 'Fetch JSON from an API endpoint with error handling.',
    structuralTokens: ['fetch', 'response.ok', 'response.json', 'try-catch'],
    antipatterns: ['no-ok-check', 'swallowed-network-error', 'no-content-type-check'],
  },
  {
    id: 'fetch-post-json',
    tier: 1,
    category: 'api-pattern',
    description: 'POST JSON data to an API with proper headers.',
    structuralTokens: ['fetch', 'POST', 'Content-Type', 'JSON.stringify', 'body'],
    antipatterns: ['missing-content-type', 'stringify-already-stringified', 'no-error-handling'],
  },
  {
    id: 'fetch-abort-controller',
    tier: 1,
    category: 'api-pattern',
    description: 'Cancel in-flight fetch requests using AbortController.',
    structuralTokens: ['AbortController', 'signal', 'abort', 'cleanup'],
    antipatterns: ['no-cleanup-on-unmount', 'abort-error-not-caught'],
  },
  {
    id: 'fetch-timeout',
    tier: 1,
    category: 'api-pattern',
    description: 'Add timeout to fetch using Promise.race and AbortController.',
    structuralTokens: ['Promise.race', 'setTimeout', 'AbortController', 'timeout'],
    antipatterns: ['no-timeout-on-network-call', 'timeout-without-abort'],
  },
  {
    id: 'fetch-retry-backoff',
    tier: 1,
    category: 'api-pattern',
    description: 'Retry failed requests with exponential backoff and jitter.',
    structuralTokens: ['retry', 'exponential-backoff', 'jitter', 'max-attempts'],
    antipatterns: ['fixed-interval-retry', 'infinite-retry', 'retry-non-idempotent'],
  },
  // ── Async Patterns ───────────────────────────────────────────────────────
  {
    id: 'async-await-basic',
    tier: 1,
    category: 'async-pattern',
    description: 'Use async/await with try/catch for clean async control flow.',
    structuralTokens: ['async', 'await', 'try-catch', 'Promise'],
    antipatterns: ['callback-hell', 'promise-chain-without-catch', 'async-without-await'],
  },
  {
    id: 'async-parallel-all',
    tier: 1,
    category: 'async-pattern',
    description: 'Run independent async operations in parallel with Promise.all.',
    structuralTokens: ['Promise.all', 'parallel', 'await', 'map'],
    antipatterns: ['sequential-await-in-loop', 'promise-all-unbounded'],
  },
  {
    id: 'async-settled',
    tier: 1,
    category: 'async-pattern',
    description: 'Handle mixed success/failure in parallel tasks with Promise.allSettled.',
    structuralTokens: ['Promise.allSettled', 'fulfilled', 'rejected', 'status'],
    antipatterns: ['promise-all-when-partial-failure-ok', 'no-rejected-check'],
  },
  {
    id: 'async-queue-concurrency',
    tier: 1,
    category: 'async-pattern',
    description: 'Limit concurrency of async tasks using a queue with max workers.',
    structuralTokens: ['concurrency', 'queue', 'semaphore', 'active-count'],
    antipatterns: ['promise-all-unbounded', 'no-concurrency-limit'],
  },
  {
    id: 'async-event-emitter',
    tier: 1,
    category: 'async-pattern',
    description: 'Use EventEmitter for decoupled async communication.',
    structuralTokens: ['EventEmitter', 'on', 'emit', 'off', 'removeListener'],
    antipatterns: ['memory-leak-no-unsubscribe', 'synchronous-subscriber-throws-stops-chain'],
  },
  // ── Error Handling ───────────────────────────────────────────────────────
  {
    id: 'error-typed-class',
    tier: 1,
    category: 'error-handling',
    description: 'Create typed error classes for domain-specific error handling.',
    structuralTokens: ['extends-Error', 'name', 'instanceof', 'typed-catch'],
    antipatterns: ['stringly-typed-error', 'catch-all-without-rethrow'],
  },
  {
    id: 'error-result-type',
    tier: 1,
    category: 'error-handling',
    description: 'Use Result<T,E> pattern to make errors explicit in return types.',
    structuralTokens: ['ok-variant', 'err-variant', 'discriminated-union', 'pattern-match'],
    antipatterns: ['swallowed-error', 'throw-inside-result-fn'],
  },
  {
    id: 'error-boundary-react',
    tier: 1,
    category: 'error-handling',
    description: 'Catch render errors in React component trees with error boundaries.',
    structuralTokens: ['ErrorBoundary', 'componentDidCatch', 'getDerivedStateFromError', 'fallback'],
    antipatterns: ['no-error-boundary', 'error-boundary-too-broad'],
  },
  {
    id: 'error-validation-guard',
    tier: 1,
    category: 'error-handling',
    description: 'Validate inputs at function boundaries before processing.',
    structuralTokens: ['guard-clause', 'early-return', 'throw-on-invalid', 'validation'],
    antipatterns: ['validate-at-end', 'silent-invalid-input'],
  },
  // ── Type Validation ──────────────────────────────────────────────────────
  {
    id: 'type-guard-function',
    tier: 1,
    category: 'type-system',
    description: 'Use type guard functions to narrow types at runtime.',
    structuralTokens: ['is-type', 'typeof', 'instanceof', 'type-predicate'],
    antipatterns: ['as-cast-without-check', 'any-type-escape-hatch'],
  },
  {
    id: 'type-assertion-safe',
    tier: 1,
    category: 'type-system',
    description: 'Assert types safely with runtime validation before casting.',
    structuralTokens: ['satisfies', 'as-const', 'type-assertion', 'runtime-check'],
    antipatterns: ['blind-as-cast', 'double-cast-through-any'],
  },
  {
    id: 'type-discriminated-union',
    tier: 1,
    category: 'type-system',
    description: 'Model variants with discriminated unions and exhaustive switch.',
    structuralTokens: ['discriminated-union', 'kind-field', 'switch-exhaustive', 'never'],
    antipatterns: ['optional-field-union', 'missing-default-case'],
  },
  {
    id: 'type-generic-constraint',
    tier: 1,
    category: 'type-system',
    description: 'Constrain generic type parameters to enforce valid usage.',
    structuralTokens: ['extends-constraint', 'keyof', 'typeof', 'conditional-type'],
    antipatterns: ['unconstrained-any-generic', 'over-constrained-generic'],
  },
  // ── React Patterns ───────────────────────────────────────────────────────
  {
    id: 'react-useeffect-cleanup',
    tier: 1,
    category: 'design-pattern',
    description: 'Always return cleanup function from useEffect to prevent memory leaks.',
    structuralTokens: ['useEffect', 'cleanup', 'return', 'unmount'],
    antipatterns: ['missing-cleanup', 'stale-closure-in-effect', 'effect-without-deps'],
  },
  {
    id: 'react-usecallback-memo',
    tier: 1,
    category: 'performance',
    description: 'Memoize callbacks and values to prevent unnecessary re-renders.',
    structuralTokens: ['useCallback', 'useMemo', 'deps-array', 'referential-equality'],
    antipatterns: ['new-function-on-every-render', 'missing-dep-in-array', 'over-memoization'],
  },
  {
    id: 'react-context-provider',
    tier: 1,
    category: 'design-pattern',
    description: 'Use Context with Provider to share state without prop drilling.',
    structuralTokens: ['createContext', 'Provider', 'useContext', 'value'],
    antipatterns: ['prop-drilling-5-levels', 'context-without-memo', 'single-context-for-everything'],
  },
  {
    id: 'react-custom-hook',
    tier: 1,
    category: 'design-pattern',
    description: 'Extract reusable stateful logic into custom hooks.',
    structuralTokens: ['use-prefix', 'custom-hook', 'useState', 'useEffect'],
    antipatterns: ['logic-in-component-body', 'hook-in-conditional'],
  },
  {
    id: 'react-suspense-lazy',
    tier: 1,
    category: 'performance',
    description: 'Lazy load components with React.lazy and Suspense.',
    structuralTokens: ['React.lazy', 'Suspense', 'fallback', 'dynamic-import'],
    antipatterns: ['no-suspense-boundary', 'eager-load-all-routes'],
  },
  // ── Performance ──────────────────────────────────────────────────────────
  {
    id: 'perf-debounce',
    tier: 1,
    category: 'performance',
    description: 'Debounce frequent events to limit execution rate.',
    structuralTokens: ['debounce', 'setTimeout', 'clearTimeout', 'delay'],
    antipatterns: ['debounce-on-every-render', 'missing-clearTimeout'],
  },
  {
    id: 'perf-throttle',
    tier: 1,
    category: 'performance',
    description: 'Throttle high-frequency events to execute at most once per interval.',
    structuralTokens: ['throttle', 'lastCall', 'interval', 'requestAnimationFrame'],
    antipatterns: ['no-throttle-on-scroll', 'throttle-too-aggressive'],
  },
  {
    id: 'perf-virtual-scroll',
    tier: 1,
    category: 'performance',
    description: 'Render only visible items in long lists using virtual scrolling.',
    structuralTokens: ['virtual-scroll', 'viewport', 'offset', 'visible-range'],
    antipatterns: ['render-all-items', 'layout-thrash-in-scroll'],
  },
  {
    id: 'perf-lazy-init',
    tier: 1,
    category: 'performance',
    description: 'Defer expensive initialization until first use.',
    structuralTokens: ['lazy-init', 'getter', 'once', 'memoize'],
    antipatterns: ['eager-init-in-constructor', 'recompute-on-every-access'],
  },
  {
    id: 'perf-batch-updates',
    tier: 1,
    category: 'performance',
    description: 'Batch multiple state updates or DB writes to reduce round trips.',
    structuralTokens: ['batch', 'flush', 'queue', 'bulk-insert'],
    antipatterns: ['update-per-item-in-loop', 'n-plus-one-queries'],
  },
  // ── Security ─────────────────────────────────────────────────────────────
  {
    id: 'security-input-sanitize',
    tier: 1,
    category: 'security',
    description: 'Sanitize user input before rendering or storing.',
    structuralTokens: ['sanitize', 'escape', 'DOMPurify', 'textContent'],
    antipatterns: ['innerHTML-from-user-input', 'no-sanitize-before-render'],
  },
  {
    id: 'security-sql-parameterized',
    tier: 1,
    category: 'security',
    description: 'Use parameterized queries to prevent SQL injection.',
    structuralTokens: ['parameterized', 'prepared-statement', 'placeholder', 'bind'],
    antipatterns: ['string-concat-sql', 'template-literal-sql', 'no-escape'],
  },
  {
    id: 'security-env-secrets',
    tier: 1,
    category: 'security',
    description: 'Store secrets in environment variables, never in source code.',
    structuralTokens: ['process.env', 'dotenv', 'secret', 'env-var'],
    antipatterns: ['hardcoded-secret', 'secret-in-git', 'console-log-secret'],
  },
  {
    id: 'security-cors-config',
    tier: 1,
    category: 'security',
    description: 'Configure CORS with explicit allowed origins.',
    structuralTokens: ['cors', 'origin', 'allowedOrigins', 'credentials'],
    antipatterns: ['wildcard-cors', 'cors-disabled', 'no-preflight-handling'],
  },
  {
    id: 'security-rate-limit',
    tier: 1,
    category: 'security',
    description: 'Apply rate limiting to API endpoints to prevent abuse.',
    structuralTokens: ['rate-limit', 'window', 'max-requests', '429'],
    antipatterns: ['no-rate-limit-on-auth', 'rate-limit-per-ip-only'],
  },
  // ── Auth Patterns ────────────────────────────────────────────────────────
  {
    id: 'auth-jwt-verify',
    tier: 1,
    category: 'api-pattern',
    description: 'Verify JWT tokens with proper algorithm and expiry checks.',
    structuralTokens: ['jwt', 'verify', 'algorithm', 'expiry', 'secret'],
    antipatterns: ['jwt-none-algorithm', 'no-expiry-check', 'secret-in-source'],
  },
  {
    id: 'auth-token-refresh',
    tier: 1,
    category: 'api-pattern',
    description: 'Implement token refresh flow with refresh token rotation.',
    structuralTokens: ['refresh-token', 'rotation', 'expiry', 'blacklist'],
    antipatterns: ['no-refresh-rotation', 'long-lived-access-token', 'refresh-in-localstorage'],
  },
  {
    id: 'auth-password-hash',
    tier: 1,
    category: 'security',
    description: 'Hash passwords with bcrypt or argon2 before storing.',
    structuralTokens: ['bcrypt', 'argon2', 'salt', 'hash', 'compare'],
    antipatterns: ['plaintext-password', 'md5-sha1-password', 'no-salt'],
  },
  // ── SQL / DB Patterns ────────────────────────────────────────────────────
  {
    id: 'db-transaction',
    tier: 1,
    category: 'async-pattern',
    description: 'Wrap related DB operations in a transaction for atomicity.',
    structuralTokens: ['transaction', 'commit', 'rollback', 'atomic'],
    antipatterns: ['partial-update-on-failure', 'no-rollback-on-error'],
  },
  {
    id: 'db-pagination',
    tier: 1,
    category: 'api-pattern',
    description: 'Paginate large result sets with cursor or offset/limit.',
    structuralTokens: ['cursor', 'limit', 'offset', 'page', 'hasMore'],
    antipatterns: ['fetch-all-rows', 'offset-pagination-at-scale', 'no-total-count'],
  },
  {
    id: 'db-index-query',
    tier: 1,
    category: 'performance',
    description: 'Ensure queries use indexes to avoid full table scans.',
    structuralTokens: ['index', 'explain', 'covering-index', 'composite-index'],
    antipatterns: ['select-star', 'filter-on-unindexed-column', 'n-plus-one-queries'],
  },
  {
    id: 'db-connection-pool',
    tier: 1,
    category: 'performance',
    description: 'Use connection pooling to reuse DB connections efficiently.',
    structuralTokens: ['pool', 'acquire', 'release', 'max-connections'],
    antipatterns: ['new-connection-per-request', 'connection-not-released'],
  },
  // ── Node.js Patterns ─────────────────────────────────────────────────────
  {
    id: 'node-stream-pipe',
    tier: 1,
    category: 'async-pattern',
    description: 'Process large data with Node.js streams to avoid memory overload.',
    structuralTokens: ['createReadStream', 'pipe', 'Transform', 'on-data'],
    antipatterns: ['readFileSync-large-file', 'buffer-entire-file', 'no-backpressure'],
  },
  {
    id: 'node-env-config',
    tier: 1,
    category: 'design-pattern',
    description: 'Load and validate environment config at startup.',
    structuralTokens: ['process.env', 'dotenv', 'required-check', 'startup-validation'],
    antipatterns: ['missing-env-silent-fail', 'no-env-validation', 'default-production-secret'],
  },
  {
    id: 'node-child-process',
    tier: 1,
    category: 'async-pattern',
    description: 'Run shell commands safely using child_process with error handling.',
    structuralTokens: ['exec', 'spawn', 'stderr', 'exit-code', 'promise-wrap'],
    antipatterns: ['shell-injection', 'no-stderr-check', 'sync-exec-in-server'],
  },
  // ── Testing Patterns ─────────────────────────────────────────────────────
  {
    id: 'test-arrange-act-assert',
    tier: 1,
    category: 'testing',
    description: 'Structure tests with clear Arrange-Act-Assert sections.',
    structuralTokens: ['arrange', 'act', 'assert', 'expect', 'describe-it'],
    antipatterns: ['test-multiple-behaviors', 'no-assertion', 'arrange-in-assert'],
  },
  {
    id: 'test-mock-dependency',
    tier: 1,
    category: 'testing',
    description: 'Mock external dependencies to isolate units under test.',
    structuralTokens: ['mock', 'stub', 'spy', 'jest.fn', 'vi.fn'],
    antipatterns: ['test-with-real-network', 'mock-implementation-too-complex'],
  },
  {
    id: 'test-snapshot',
    tier: 1,
    category: 'testing',
    description: 'Use snapshot tests for UI components with controlled updates.',
    structuralTokens: ['toMatchSnapshot', 'toMatchInlineSnapshot', 'snapshot-update'],
    antipatterns: ['snapshot-entire-page', 'auto-accept-all-snapshots'],
  },
  {
    id: 'test-edge-cases',
    tier: 1,
    category: 'testing',
    description: 'Explicitly test boundary conditions and edge cases.',
    structuralTokens: ['empty-input', 'null-undefined', 'max-value', 'boundary'],
    antipatterns: ['happy-path-only', 'no-null-test', 'no-empty-array-test'],
  },
  // ── Algorithm Classics ───────────────────────────────────────────────────
  {
    id: 'algo-binary-search',
    tier: 1,
    category: 'algorithm',
    description: 'Binary search on sorted array for O(log n) lookup.',
    structuralTokens: ['binary-search', 'mid', 'low', 'high', 'sorted'],
    antipatterns: ['linear-scan-on-sorted', 'off-by-one-bounds', 'missing-sorted-precondition'],
  },
  {
    id: 'algo-two-pointer',
    tier: 1,
    category: 'algorithm',
    description: 'Use two pointers to solve array problems in O(n) time.',
    structuralTokens: ['left', 'right', 'two-pointer', 'while-left-less-right'],
    antipatterns: ['nested-loop-when-two-pointer-works', 'pointer-not-advancing'],
  },
  {
    id: 'algo-sliding-window',
    tier: 1,
    category: 'algorithm',
    description: 'Sliding window technique for subarray/substring problems.',
    structuralTokens: ['window', 'start', 'end', 'expand', 'shrink'],
    antipatterns: ['brute-force-all-subarrays', 'window-not-shrinking'],
  },
  {
    id: 'algo-dynamic-programming',
    tier: 1,
    category: 'algorithm',
    description: 'Break problems into overlapping subproblems with memoization.',
    structuralTokens: ['memo', 'dp-table', 'subproblem', 'base-case', 'recurrence'],
    antipatterns: ['exponential-recursion-without-memo', 'wrong-base-case'],
  },
  {
    id: 'algo-graph-bfs',
    tier: 1,
    category: 'algorithm',
    description: 'Breadth-first search for shortest path in unweighted graphs.',
    structuralTokens: ['queue', 'visited', 'neighbors', 'level', 'BFS'],
    antipatterns: ['no-visited-set', 'dfs-when-bfs-needed', 'infinite-loop'],
  },
  {
    id: 'algo-graph-dfs',
    tier: 1,
    category: 'algorithm',
    description: 'Depth-first search for traversal and cycle detection.',
    structuralTokens: ['stack', 'visited', 'recursive', 'DFS', 'backtrack'],
    antipatterns: ['no-visited-set', 'stack-overflow-no-base-case'],
  },
  // ── Data Structures ──────────────────────────────────────────────────────
  {
    id: 'ds-map-lookup',
    tier: 1,
    category: 'data-structure',
    description: 'Use Map for O(1) key-value lookups instead of array search.',
    structuralTokens: ['Map', 'get', 'set', 'has', 'O(1)-lookup'],
    antipatterns: ['array-find-as-map', 'object-as-map-with-numeric-keys'],
  },
  {
    id: 'ds-set-membership',
    tier: 1,
    category: 'data-structure',
    description: 'Use Set for O(1) membership tests and deduplication.',
    structuralTokens: ['Set', 'has', 'add', 'delete', 'O(1)-membership'],
    antipatterns: ['array-includes-in-hot-path', 'indexOf-for-membership'],
  },
  {
    id: 'ds-stack-lifo',
    tier: 1,
    category: 'data-structure',
    description: 'Implement LIFO stack using array push/pop.',
    structuralTokens: ['push', 'pop', 'peek', 'stack', 'LIFO'],
    antipatterns: ['shift-unshift-as-stack', 'no-empty-check-before-pop'],
  },
  {
    id: 'ds-queue-fifo',
    tier: 1,
    category: 'data-structure',
    description: 'Implement FIFO queue efficiently without O(n) shift.',
    structuralTokens: ['enqueue', 'dequeue', 'head', 'tail', 'FIFO'],
    antipatterns: ['array-shift-as-queue', 'unbounded-queue'],
  },
  {
    id: 'ds-lru-cache',
    tier: 1,
    category: 'data-structure',
    description: 'LRU cache using Map for O(1) get/put with eviction.',
    structuralTokens: ['LRU', 'Map', 'capacity', 'evict', 'move-to-front'],
    antipatterns: ['unbounded-cache', 'no-eviction-policy', 'o-n-eviction'],
  },
  // ── Design Patterns ──────────────────────────────────────────────────────
  {
    id: 'pattern-observer',
    tier: 1,
    category: 'design-pattern',
    description: 'Observer pattern for decoupled event-driven communication.',
    structuralTokens: ['subscribe', 'unsubscribe', 'notify', 'observer', 'listener'],
    antipatterns: ['memory-leak-no-unsubscribe', 'synchronous-subscriber-throws'],
  },
  {
    id: 'pattern-factory',
    tier: 1,
    category: 'design-pattern',
    description: 'Factory function to encapsulate object creation logic.',
    structuralTokens: ['factory', 'create', 'constructor', 'encapsulate'],
    antipatterns: ['new-everywhere', 'factory-with-side-effects'],
  },
  {
    id: 'pattern-singleton',
    tier: 1,
    category: 'design-pattern',
    description: 'Singleton pattern for shared instance with lazy initialization.',
    structuralTokens: ['instance', 'getInstance', 'lazy-init', 'single-instance'],
    antipatterns: ['eager-singleton', 'singleton-with-mutable-global-state'],
  },
  {
    id: 'pattern-strategy',
    tier: 1,
    category: 'design-pattern',
    description: 'Strategy pattern to swap algorithms at runtime.',
    structuralTokens: ['strategy', 'interface', 'swap', 'execute', 'context'],
    antipatterns: ['instanceof-chain-instead', 'strategy-with-state'],
  },
  {
    id: 'pattern-command',
    tier: 1,
    category: 'design-pattern',
    description: 'Command pattern for undoable operations and queuing.',
    structuralTokens: ['execute', 'undo', 'command', 'history', 'queue'],
    antipatterns: ['no-undo-implementation', 'command-with-side-effects-only'],
  },
  {
    id: 'pattern-builder',
    tier: 1,
    category: 'design-pattern',
    description: 'Builder pattern for constructing complex objects step by step.',
    structuralTokens: ['builder', 'chain', 'build', 'fluent', 'step'],
    antipatterns: ['constructor-with-20-params', 'mutable-builder-shared'],
  },
]
