// ═══════════════════════════════════════════════════════════════════════════════
// VERIFIED DECOMPOSITION — the methodology for "the proposer is too weak to converge"
// ═══════════════════════════════════════════════════════════════════════════════
//
// iterate() climbs while it improves, injects research when it stalls, and abstains
// honestly when research cannot move the score. That is correct — but for a hard goal
// a WEAK ~3B proposer often cannot one-shot the whole artifact at all: it thrashes on
// scoping errors, copies reference fragments without their declarations, and never
// reaches a certifiable candidate. Bigger models are NOT the answer (that violates the
// north star). The answer is to shrink the STEP until it fits the model's competence.
//
// The insight generalises the whole thesis: correctness comes from the LOOP. If one
// loop can't converge, we don't trust the model harder — we run MORE loops, each over
// a smaller, independently-verifiable subgoal, and let the verifier certify each rung:
//
//   goal ──(weak model proposes an ordered plan)──► [sub₁, sub₂, …, sub_n]
//     solve sub₁ by iterate()  → certified s₁     (freeze s₁ as grounding)
//     solve sub₂ | context=s₁  → certified s₂     (freeze s₂ …)
//     …
//     solve sub_n | context=s₁…s₋₁ → candidate
//   VERIFY the composed result against the ORIGINAL verifier  ► solved | honest abstain
//
// This is a CURRICULUM GENERATED BY THE VERIFIER. Each rung is small enough that the
// weak model can produce a candidate the verifier certifies, and each certified rung
// becomes sound grounding (real, checked artifact — not a model belief) that makes the
// next rung reachable. It is domain-agnostic: it only ever touches Proposer / Verifier /
// TaskSpec, so the same machinery decomposes code (build increment by increment), games
// (canvas → player → input → projectile → collision), research (a question into
// independently-checkable sub-claims), and agentic plans (a task into verifiable steps).
//
// SOUNDNESS IS PRESERVED. The plan the weak model proposes is UNTRUSTED — a bad split
// only wastes budget, it can never make a wrong answer look right, because:
//   (1) every rung is certified by a real Verifier, never by the model's say-so, and
//   (2) the composed result is re-verified against the ORIGINAL spec's verifier before
//       we ever call it solved. If composition fails, we abstain with the best partial.
// The model chooses the PATH; the verifier owns the TRUTH. Same doctrine as everywhere.
// ═══════════════════════════════════════════════════════════════════════════════

import { iterate, type IterateOpts, type IterateResult } from './iterate'
import type { Attempt, Candidate, Proposer, TaskSpec, Verifier } from './types'

/** An ordered subgoal in a decomposition plan. Opaque text the domain interprets. */
export interface SubGoal {
  /** Human-readable subgoal statement, handed to subSpecFor(). */
  goal: string
  /** Optional note for the audit trail (why this rung exists). */
  rationale?: string
}

/**
 * Proposes an ordered decomposition of a stuck goal into smaller subgoals. UNTRUSTED —
 * a poor plan only costs budget, never correctness (every rung and the composition are
 * verifier-certified). Returns null when the goal cannot meaningfully be split, in which
 * case decomposition declines and the caller keeps the flat abstain.
 */
export type Planner = (
  spec: TaskSpec,
  best: Attempt | null,
  signal?: AbortSignal,
) => Promise<SubGoal[] | null>

/**
 * Builds a fully-wired, INDEPENDENTLY-VERIFIABLE sub-problem for one rung. The domain
 * owns this because "what makes a subgoal correct" is domain-specific:
 *   • code/games: a growing acceptance subset over the frozen prior artifact,
 *   • research:   an independent consensus verifier for the sub-claim.
 * `priorSolutions` are the certified artifacts of every earlier rung (soundly checked),
 * available as grounding. Return null to SKIP a rung (treat as vacuously satisfied).
 */
export type SubSpecFactory<T> = (
  sub: SubGoal,
  index: number,
  priorSolutions: T[],
  parent: TaskSpec,
) => {
  spec: TaskSpec
  proposer: Proposer<T>
  verifier: Verifier<T>
} | null

export interface DecomposeOpts<T> {
  planner: Planner
  /**
   * Optional domain factory for per-rung sub-problems. When omitted, a sound DEFAULT is
   * used: each rung reuses the PARENT proposer + verifier with prior certified solutions
   * folded into context ("verified restart with accumulated grounding"). The default
   * cannot certify a rung the parent verifier wouldn't, so it is always sound — it just
   * converges less aggressively than a bespoke incremental factory.
   */
  subSpecFor?: SubSpecFactory<T>
  /** iterate() options applied to EACH rung (budgets are per-rung). */
  iterateOpts?: IterateOpts<T>
  /** Max rungs to accept from the planner (runaway guard). Default 6. */
  maxSubGoals?: number
  /** How a prior certified solution is rendered into the next rung's context. Default: JSON/string. */
  renderPrior?: (solution: T, sub: SubGoal, index: number) => string
  emit?: IterateOpts<T>['emit']
  signal?: AbortSignal
}

export interface RungRecord<T> {
  index: number
  goal: string
  status: IterateResult<T>['status']
  bestScore: number
  modelCalls: number
  certified: boolean
}

export interface DecomposeResult<T> {
  status: 'solved' | 'decompose-failed' | 'declined' | 'aborted'
  /** Composed certified solution (re-verified against the ORIGINAL spec), when solved. */
  solution: Candidate<T> | null
  /** Best partial across all rungs, for honest reporting when unsolved. */
  best: Attempt<T> | null
  rungs: RungRecord<T>[]
  modelCalls: number
  detail: string
}

const defaultRender = <T>(sol: T, sub: SubGoal, i: number): string => {
  const body = typeof sol === 'string' ? sol : JSON.stringify(sol, null, 2)
  return `[certified subgoal ${i + 1}: ${sub.goal}]\n${body}`
}

/**
 * Default sub-problem factory: reuse the parent proposer + verifier, appending every
 * prior certified solution to the rung's context. Sound (the parent verifier is the
 * judge) and general (no domain knowledge). A domain with true incremental structure
 * should supply its own subSpecFor for faster convergence.
 */
function defaultSubSpec<T>(
  render: (s: T, sub: SubGoal, i: number) => string,
  proposer: Proposer<T>,
  verifier: Verifier<T>,
): SubSpecFactory<T> {
  return (sub, index, priorSolutions, parent) => {
    const grounding = priorSolutions.map((s, i) => render(s, { goal: '' }, i)).join('\n\n')
    const context = [parent.context, grounding].filter(Boolean).join('\n\n') || undefined
    const spec: TaskSpec = { ...parent, goal: sub.goal, context }
    return { spec, proposer, verifier }
  }
}

/**
 * Solve a goal by verified decomposition. Intended as a FALLBACK after a flat iterate()
 * has stalled — call it with the same proposer/verifier and a domain Planner.
 *
 * Termination is deterministic: solved (composition certified) · decompose-failed (a rung
 * or the composition could not be certified) · declined (planner returned no usable split)
 * · aborted. It NEVER ships an unverified guess — the composed artifact is re-checked by
 * the original verifier before being called solved.
 */
export async function solveByDecomposition<T>(
  spec: TaskSpec,
  proposer: Proposer<T>,
  verifier: Verifier<T>,
  opts: DecomposeOpts<T>,
): Promise<DecomposeResult<T>> {
  const emit = opts.emit ?? (() => {})
  const maxSub = opts.maxSubGoals ?? 6
  const render = opts.renderPrior ?? defaultRender<T>
  const subSpecFor = opts.subSpecFor ?? defaultSubSpec<T>(render, proposer, verifier)
  let modelCalls = 0
  const rungs: RungRecord<T>[] = []
  let best: Attempt<T> | null = null

  const trackBest = (a: Attempt<T> | null) => {
    if (a && (!best || a.verdict.score > best.verdict.score)) best = a
  }

  if (opts.signal?.aborted) {
    return { status: 'aborted', solution: null, best, rungs, modelCalls, detail: 'aborted before planning' }
  }

  // 1) Ask the (untrusted) model for an ordered plan. A refusal to split is honest —
  //    it means decomposition has nothing to offer here; the caller keeps its abstain.
  let plan: SubGoal[] | null = null
  try {
    plan = await opts.planner(spec, best, opts.signal)
  } catch (e: any) {
    emit({ type: 'thought', text: `decompose: planner error ${String(e?.message ?? e)}` })
  }
  if (!plan || plan.length < 2) {
    return { status: 'declined', solution: null, best, rungs, modelCalls,
      detail: plan ? `planner returned ${plan.length} subgoal(s) — not a decomposition` : 'planner declined to split' }
  }
  const subgoals = plan.slice(0, maxSub)
  emit({ type: 'thought', text: `decompose: ${subgoals.length} rung(s) — ${subgoals.map(s => s.goal).join(' → ')}` })

  // 2) Climb the curriculum. Each rung is certified before it becomes grounding for the
  //    next; a rung that cannot be certified collapses the whole decomposition (honest).
  const priorSolutions: T[] = []
  for (let i = 0; i < subgoals.length; i++) {
    if (opts.signal?.aborted) {
      return { status: 'aborted', solution: null, best, rungs, modelCalls, detail: `aborted at rung ${i}` }
    }
    const sub = subgoals[i]
    const wired = subSpecFor(sub, i, priorSolutions.slice(), spec)
    if (!wired) {
      rungs.push({ index: i, goal: sub.goal, status: 'solved', bestScore: 0, modelCalls: 0, certified: true })
      continue // domain declared this rung vacuous
    }

    const res = await iterate<T>(wired.spec, wired.proposer, wired.verifier, {
      ...opts.iterateOpts, signal: opts.signal, emit: opts.emit,
    })
    modelCalls += res.modelCalls
    trackBest(res.best)
    const certified = res.status === 'solved' && !!res.solution
    rungs.push({ index: i, goal: sub.goal, status: res.status, bestScore: res.bestScore, modelCalls: res.modelCalls, certified })

    if (!certified) {
      return { status: 'decompose-failed', solution: null, best, rungs, modelCalls,
        detail: `rung ${i + 1}/${subgoals.length} (“${sub.goal}”) did not certify — ${res.detail}` }
    }
    priorSolutions.push(res.solution!.value)
    emit({ type: 'thought', text: `decompose: rung ${i + 1}/${subgoals.length} certified (${modelCalls} calls so far)` })
  }

  // 3) The composed result is the final rung's certified artifact. RE-VERIFY it against
  //    the ORIGINAL spec's verifier — the plan was untrusted, so the whole must be proven
  //    correct as a whole, not merely rung-by-rung.
  const composed = priorSolutions[priorSolutions.length - 1]
  if (composed === undefined) {
    return { status: 'decompose-failed', solution: null, best, rungs, modelCalls, detail: 'no rung produced a solution' }
  }
  const candidate: Candidate<T> = { value: composed, fingerprint: 'decomposed' }
  const finalVerdict = await verifier(candidate, spec)
  trackBest({ candidate, verdict: finalVerdict })

  if (finalVerdict.pass) {
    return { status: 'solved', solution: candidate, best, rungs, modelCalls,
      detail: `decomposition solved in ${subgoals.length} rung(s), ${modelCalls} model call(s)` }
  }
  return { status: 'decompose-failed', solution: null, best, rungs, modelCalls,
    detail: `all rungs certified but composition failed original verifier: ${finalVerdict.signals.slice(0, 3).join('; ')}` }
}
