// Generated by generate.ts — hidden adversarial suite for all-any-pass.
// Run via `npx tsx __audit__/allAnyPass.hidden.ts` inside the scratch project.
import { allPass, anyPass } from '../src/allAnyPass'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("allPass true", allPass<number>([x=>x>0,x=>x<10])(5), true)
await check("allPass false", allPass<number>([x=>x>0,x=>x<10])(15), false)
await check("anyPass true", anyPass<number>([x=>x>100,x=>x<0])(-5), true)
await check("anyPass false", anyPass<number>([x=>x>100,x=>x<0])(5), false)
await check("allPass empty true", allPass<number>([])(1), true)
await check("anyPass empty false", anyPass<number>([])(1), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
