// Generated by generate.ts — hidden adversarial suite for async-patterns.
// Run via `npx tsx __audit__/asyncPatterns.hidden.ts` inside the scratch project.
import { memoizeAsync, sequential, waterfall } from '../src/asyncPatterns'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("memoizeAsync caches", (async()=>{let n=0;const f=memoizeAsync(async()=>++n);await f();await f();return n})(), 1)
await check("memoizeAsync different args", (async()=>{let n=0;const f=memoizeAsync(async(x:number)=>{n++;return x*2});const r=[await f(1),await f(2),await f(1)];return [r,n]})(), [[2,4,2],2])
await check("sequential order", sequential([async()=>1, async()=>2, async()=>3]), [1,2,3])
await check("sequential empty", sequential([]), [])
await check("waterfall transforms", waterfall(1, [async x=>x+1, async x=>x*2, async x=>x-1]), 3)
await check("waterfall no fns", waterfall(42, []), 42)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
