// Generated by generate.ts — hidden adversarial suite for bfs-hop-counts.
// Run via `npx tsx __audit__/bfsHopCounts.hidden.ts` inside the scratch project.
import { bfsHopCounts } from '../src/bfsHopCounts'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", bfsHopCounts(4,[[1,2],[0,3],[0],[1]],0), [0,1,1,2])
await check("unreachable", bfsHopCounts(3,[[1],[0],[]],0), [0,1,-1])
await check("single", bfsHopCounts(1,[[]],0), [0])
await check("chain", bfsHopCounts(4,[[1],[2],[3],[]],0), [0,1,2,3])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
