// Generated by generate.ts — hidden adversarial suite for bimap.
// Run via `npx tsx __audit__/bimap.hidden.ts` inside the scratch project.
import { BiMap } from '../src/bimap'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("set and getByKey", (() => { const m = new BiMap<string,number>(); m.set("a",1); return m.getByKey("a") })(), 1)
await check("getByValue", (() => { const m = new BiMap<string,number>(); m.set("a",1); return m.getByValue(1) })(), "a")
await check("hasKey", (() => { const m = new BiMap<string,number>(); m.set("a",1); return m.hasKey("a") })(), true)
await check("hasValue", (() => { const m = new BiMap<string,number>(); m.set("a",1); return m.hasValue(1) })(), true)
await check("size", (() => { const m = new BiMap<string,number>(); m.set("a",1).set("b",2); return m.size() })(), 2)
await check("overwrite key removes old value", (() => { const m = new BiMap<string,number>(); m.set("a",1); m.set("a",2); return m.hasValue(1) })(), false)
await check("delete", (() => { const m = new BiMap<string,number>(); m.set("a",1); m.deleteByKey("a"); return m.hasKey("a") })(), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
