// Generated by generate.ts — hidden adversarial suite for business-days-between.
// Run via `npx tsx __audit__/businessDaysBetween.hidden.ts` inside the scratch project.
import { businessDaysBetween } from '../src/businessDaysBetween'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("Mon to Fri", businessDaysBetween(new Date("2024-01-01T00:00:00Z"),new Date("2024-01-05T00:00:00Z")), 4)
await check("same day", businessDaysBetween(new Date("2024-01-01T00:00:00Z"),new Date("2024-01-01T00:00:00Z")), 0)
await check("skips weekend", businessDaysBetween(new Date("2024-01-05T00:00:00Z"),new Date("2024-01-08T00:00:00Z")), 1)
await check("full week", businessDaysBetween(new Date("2024-01-01T00:00:00Z"),new Date("2024-01-08T00:00:00Z")), 5)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
