// Generated by generate.ts — hidden adversarial suite for cache-aside.
// Run via `npx tsx __audit__/cacheAside.hidden.ts` inside the scratch project.
import { CacheAside } from '../src/cacheAside'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("loads on miss", (async()=>{let loads=0;const c=new CacheAside(async k=>{loads++;return k*2});await c.get(5);return loads})(), 1)
await check("caches on hit", (async()=>{let loads=0;const c=new CacheAside(async k=>{loads++;return k});await c.get(1);await c.get(1);return loads})(), 1)
await check("returns correct value", (async()=>{const c=new CacheAside(async k=>k+"!");return await c.get("hello")})(), "hello!")
await check("has after load", (async()=>{const c=new CacheAside(async k=>k);await c.get("x");return c.has("x")})(), true)
await check("delete removes", (async()=>{const c=new CacheAside(async k=>k);await c.get("x");c.delete("x");return c.has("x")})(), false)
await check("set bypasses loader", (async()=>{let loads=0;const c=new CacheAside(async k=>{loads++;return k});c.set("x","manual");await c.get("x");return loads})(), 0)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
