// Generated by generate.ts — hidden adversarial suite for coin-change-min.
// Run via `npx tsx __audit__/coinChangeMin.hidden.ts` inside the scratch project.
import { coinChangeMin } from '../src/coinChangeMin'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic 11", coinChangeMin([1,2,5],11), 3)
await check("impossible", coinChangeMin([2],3), -1)
await check("zero amount", coinChangeMin([1,2,5],0), 0)
await check("exact single", coinChangeMin([1,5,10,25],30), 2)
await check("only ones", coinChangeMin([1],7), 7)
await check("no coins", coinChangeMin([],5), -1)
await check("no coins zero amount", coinChangeMin([],0), 0)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
