// Generated by generate.ts — hidden adversarial suite for combinations.
// Run via `npx tsx __audit__/combinations.hidden.ts` inside the scratch project.
import { combinations, permutations, powerSet } from '../src/combinations'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("combinations 2 from 3", combinations([1,2,3], 2), [[1,2],[1,3],[2,3]])
await check("combinations 0", combinations([1,2,3], 0), [[]])
await check("combinations k=n", combinations([1,2], 2), [[1,2]])
await check("combinations k>n", combinations([1,2], 3), [])
await check("permutations 3", permutations([1,2,3]).length, 6)
await check("permutations 1", permutations([1]), [[1]])
await check("powerSet 3", powerSet([1,2,3]).length, 8)
await check("powerSet includes empty", powerSet([1,2]).some(s=>s.length===0), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
