// Generated by generate.ts — hidden adversarial suite for convex-hull-area.
// Run via `npx tsx __audit__/convexHullArea.hidden.ts` inside the scratch project.
import { convexHullArea } from '../src/convexHullArea'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("square with interior point", convexHullArea([[0,0],[4,0],[4,4],[0,4],[2,2]]), 16)
await check("triangle", convexHullArea([[0,0],[4,0],[0,3]]), 6)
await check("collinear points degenerate to 0", convexHullArea([[0,0],[1,1],[2,2]]), 0)
await check("two points returns 0", convexHullArea([[0,0],[1,1]]), 0)
await check("empty returns 0", convexHullArea([]), 0)
await check("duplicate point ignored", convexHullArea([[0,0],[0,0],[4,0],[4,4]]), 8)
await check("negative coordinate square", convexHullArea([[-2,-2],[2,-2],[2,2],[-2,2]]), 16)
await check("interior cluster does not enlarge", convexHullArea([[0,0],[6,0],[6,6],[0,6],[3,3],[2,2],[4,4]]), 36)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
