// Generated by generate.ts — hidden adversarial suite for cookie-parse.
// Run via `npx tsx __audit__/cookieParse.hidden.ts` inside the scratch project.
import { parseCookies, serializeCookie } from '../src/cookieParse'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parse single", parseCookies("session=abc123")["session"], "abc123")
await check("parse multiple", parseCookies("a=1; b=2; c=3")["b"], "2")
await check("parse encoded", parseCookies("k=hello%20world")["k"], "hello world")
await check("parse empty", JSON.stringify(parseCookies("")), "{}")
await check("serialize basic", serializeCookie("id", "abc"), "id=abc")
await check("serialize maxAge", serializeCookie("id","abc",{maxAge:3600}), "id=abc; Max-Age=3600")
await check("serialize httpOnly", serializeCookie("id","abc",{httpOnly:true}), "id=abc; HttpOnly")
await check("serialize encodes name", serializeCookie("my id","val"), "my%20id=val")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
