// Generated by generate.ts — hidden adversarial suite for date-format.
// Run via `npx tsx __audit__/dateFormat.hidden.ts` inside the scratch project.
import { formatDate, parseDate } from '../src/dateFormat'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("format YYYY-MM-DD", formatDate(new Date("2024-01-15T00:00:00Z"), "YYYY-MM-DD"), "2024-01-15")
await check("format with time", formatDate(new Date("2024-06-28T14:30:45Z"), "YYYY-MM-DD HH:mm:ss"), "2024-06-28 14:30:45")
await check("format DD/MM/YYYY", formatDate(new Date("2024-03-07T00:00:00Z"), "DD/MM/YYYY"), "07/03/2024")
await check("format single digit padded", formatDate(new Date("2024-01-05T00:00:00Z"), "MM/DD/YYYY"), "01/05/2024")
await check("parseDate valid", parseDate("2024-01-15") instanceof Date, true)
await check("parseDate timestamp", formatDate(parseDate("2024-06-01T00:00:00Z"), "YYYY-MM-DD"), "2024-06-01")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
