// Generated by generate.ts — hidden adversarial suite for degree-sequence.
// Run via `npx tsx __audit__/degreeSequence.hidden.ts` inside the scratch project.
import { degreeSequence } from '../src/degreeSequence'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("triangle", degreeSequence(3,[[0,1],[1,2],[2,0]]), [2,2,2])
await check("star", degreeSequence(4,[[0,1],[0,2],[0,3]]), [3,1,1,1])
await check("no edges", degreeSequence(3,[]), [0,0,0])
await check("path", degreeSequence(3,[[0,1],[1,2]]), [2,1,1])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
