// Generated by generate.ts — hidden adversarial suite for deque-structure.
// Run via `npx tsx __audit__/dequeStructure.hidden.ts` inside the scratch project.
import { Deque } from '../src/dequeStructure'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("pushBack order", (() => { const d = new Deque<number>(); d.pushBack(1); d.pushBack(2); return d.toArray() })(), [1,2])
await check("pushFront order", (() => { const d = new Deque<number>(); d.pushBack(2); d.pushFront(1); return d.toArray() })(), [1,2])
await check("popFront", (() => { const d = new Deque<number>(); [1,2,3].forEach(n=>d.pushBack(n)); return d.popFront() })(), 1)
await check("popBack", (() => { const d = new Deque<number>(); [1,2,3].forEach(n=>d.pushBack(n)); return d.popBack() })(), 3)
await check("size", (() => { const d = new Deque<number>(); d.pushBack(1); d.pushFront(0); return d.size() })(), 2)
await check("popFront empty", new Deque().popFront(), undefined)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
