// Generated by generate.ts — hidden adversarial suite for digit-sum.
// Run via `npx tsx __audit__/digitSum.hidden.ts` inside the scratch project.
import { digitSum } from '../src/digitSum'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("multi digit", digitSum(12345), 15)
await check("zero", digitSum(0), 0)
await check("single digit", digitSum(7), 7)
await check("negative uses absolute value", digitSum(-987), 24)
await check("trailing zeros", digitSum(1000000), 1)
await check("all nines", digitSum(99999), 45)
await check("negative single digit", digitSum(-4), 4)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
