// Generated by generate.ts — hidden adversarial suite for dijkstra-distances.
// Run via `npx tsx __audit__/dijkstraDistances.hidden.ts` inside the scratch project.
import { dijkstraDistances } from '../src/dijkstraDistances'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic", dijkstraDistances(5,[[0,1,4],[0,2,1],[2,1,2],[1,3,1]],0), [0,3,1,4,null])
await check("single", dijkstraDistances(1,[],0), [0])
await check("unreachable", dijkstraDistances(2,[],0), [0,null])
await check("direct", dijkstraDistances(2,[[0,1,5]],0), [0,5])
await check("shorter via relay", dijkstraDistances(3,[[0,1,10],[0,2,1],[2,1,1]],0), [0,2,1])
await check("source offset", dijkstraDistances(3,[[0,1,1],[1,2,1]],2), [null,null,0])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
