// Generated by generate.ts — hidden adversarial suite for euclidean-distance-points.
// Run via `npx tsx __audit__/distancePoints.hidden.ts` inside the scratch project.
import { distancePoints } from '../src/distancePoints'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("3-4-5 triangle", distancePoints(0,0,3,4), 5)
await check("same point is zero", distancePoints(2,2,2,2), 0)
await check("negative coords", distancePoints(-1,-1,2,3), 5)
await check("horizontal", distancePoints(1,5,4,5), 3)
await check("vertical", distancePoints(7,-2,7,3), 5)
await check("symmetric", distancePoints(5,5,1,2), 5)
await check("all negative", distancePoints(-4,-3,0,0), 5)
await check("unit", distancePoints(0,0,1,0), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
