// Generated by generate.ts — hidden adversarial suite for error-utils.
// Run via `npx tsx __audit__/errorUtils.hidden.ts` inside the scratch project.
import { createError, serializeError, wrapError, isNetworkError } from '../src/errorUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("createError has code", createError("oops","ERR_BAD","ignored" as any).code, "ERR_BAD")
await check("createError is Error", createError("msg","CODE") instanceof Error, true)
await check("serializeError message", serializeError(new Error("boom"))["message"], "boom")
await check("serializeError non-error", serializeError("raw")["message"], "raw")
await check("wrapError wraps", wrapError(new Error("orig"),"wrapped").message, "wrapped")
await check("isNetworkError ECONNREFUSED", isNetworkError(new Error("ECONNREFUSED")), true)
await check("isNetworkError false", isNetworkError(new Error("SyntaxError")), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
