// Generated by generate.ts — hidden adversarial suite for extended-gcd.
// Run via `npx tsx __audit__/extendedGcd.hidden.ts` inside the scratch project.
import { extendedGcd } from '../src/extendedGcd'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("coprime-ish 240 and 46", extendedGcd(240,46), [2,-9,47])
await check("one divides the other", extendedGcd(12,8), [4,1,-1])
await check("a is zero", extendedGcd(0,5), [5,0,1])
await check("b is zero", extendedGcd(5,0), [5,1,0])
await check("shared factor 35 and 15", extendedGcd(35,15), [5,1,-2])
await check("both zero gives zero gcd", extendedGcd(0,0), [0,1,0])
await check("identity check via Bezout", (() => { const [g,x,y] = extendedGcd(240,46); return 240*x + 46*y === g })(), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
