// Generated by generate.ts — hidden adversarial suite for flatten.
// Run via `npx tsx __audit__/flatten.hidden.ts` inside the scratch project.
import { flatten } from '../src/flatten'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("one level", flatten([[1,2],[3,4]]), [1,2,3,4])
await check("nested one level default", flatten([[1,[2]],[3]]), [1,[2],3])
await check("deep flatten", flatten([[1,[2,[3]]]], Infinity as any), [1,2,3])
await check("empty", flatten([]), [])
await check("no nesting", flatten([1,2,3]), [1,2,3])
await check("depth 2", flatten([[1,[2,[3]]]], 2), [1,2,[3]])
await check("mixed types", flatten([["a",["b"]],"c"]), ["a",["b"],"c"])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
