// Generated by generate.ts — hidden adversarial suite for fnv1a-hash.
// Run via `npx tsx __audit__/fnv1aHash.hidden.ts` inside the scratch project.
import { fnv1aHash } from '../src/fnv1aHash'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("hello", fnv1aHash("hello"), 1335831723)
await check("empty", fnv1aHash(""), 2166136261)
await check("deterministic", fnv1aHash("test") === fnv1aHash("test"), true)
await check("unsigned", fnv1aHash("x") >= 0, true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
