// Generated by generate.ts — hidden adversarial suite for graph-simple.
// Run via `npx tsx __audit__/graphSimple.hidden.ts` inside the scratch project.
import { Graph } from '../src/graphSimple'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("addEdge and neighbors", (() => { const g = new Graph<number>(); g.addEdge(1,2); return g.neighbors(1) })(), [2])
await check("undirected both ways", (() => { const g = new Graph<number>(); g.addEdge(1,2); return g.hasEdge(2,1) })(), true)
await check("directed one way", (() => { const g = new Graph<number>(); g.addEdge(1,2,true); return g.hasEdge(2,1) })(), false)
await check("bfs order", (() => { const g = new Graph<number>(); g.addEdge(1,2); g.addEdge(1,3); g.addEdge(2,4); return g.bfs(1) })(), [1,2,3,4])
await check("dfs visits all", (() => { const g = new Graph<number>(); g.addEdge(1,2); g.addEdge(2,3); return g.dfs(1).length })(), 3)
await check("shortestPath basic", (() => { const g = new Graph<number>(); g.addEdge(1,2); g.addEdge(2,3); return g.shortestPath(1,3) })(), [1,2,3])
await check("shortestPath no path", (() => { const g = new Graph<number>(); g.addVertex(1); g.addVertex(2); return g.shortestPath(1,2) })(), null)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
