// Generated by generate.ts — hidden adversarial suite for humanize-relative-time.
// Run via `npx tsx __audit__/humanizeRelativeTime.hidden.ts` inside the scratch project.
import { humanizeRelativeTime } from '../src/humanizeRelativeTime'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("in 3 days", humanizeRelativeTime(new Date("2024-01-01T00:00:00Z"),new Date("2024-01-04T00:00:00Z")), "in 3 days")
await check("2 hours ago", humanizeRelativeTime(new Date("2024-01-01T02:00:00Z"),new Date("2024-01-01T00:00:00Z")), "2 hours ago")
await check("1 minute", humanizeRelativeTime(new Date("2024-01-01T00:00:00Z"),new Date("2024-01-01T00:01:00Z")), "in 1 minute")
await check("1 year", humanizeRelativeTime(new Date("2023-01-01T00:00:00Z"),new Date("2024-01-01T00:00:00Z")), "in 1 year")
await check("just now", humanizeRelativeTime(new Date("2024-01-01T00:00:00Z"),new Date("2024-01-01T00:00:00Z")), "just now")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
