// Generated by generate.ts — hidden adversarial suite for interval-set.
// Run via `npx tsx __audit__/intervalSet.hidden.ts` inside the scratch project.
import { IntervalSet } from '../src/intervalSet'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("merge overlap", (() => { const s = new IntervalSet(); s.add(1,3); s.add(2,4); return s.list() })(), [[1,4]])
await check("disjoint", (() => { const s = new IntervalSet(); s.add(1,3); s.add(5,7); return s.list() })(), [[1,3],[5,7]])
await check("merge all", (() => { const s = new IntervalSet(); s.add(1,3); s.add(5,7); s.add(2,6); return s.list() })(), [[1,7]])
await check("contains inside", (() => { const s = new IntervalSet(); s.add(1,5); return s.contains(3) })(), true)
await check("contains outside", (() => { const s = new IntervalSet(); s.add(1,5); return s.contains(9) })(), false)
await check("adjacent merge", (() => { const s = new IntervalSet(); s.add(1,4); s.add(4,7); return s.list() })(), [[1,7]])
await check("reversed input", (() => { const s = new IntervalSet(); s.add(5,2); return s.list() })(), [[2,5]])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
