// Generated by generate.ts — hidden adversarial suite for is-bipartite-graph.
// Run via `npx tsx __audit__/isBipartiteGraph.hidden.ts` inside the scratch project.
import { isBipartiteGraph } from '../src/isBipartiteGraph'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("even cycle", isBipartiteGraph(4,[[0,1],[1,2],[2,3],[3,0]]), true)
await check("triangle", isBipartiteGraph(3,[[0,1],[1,2],[2,0]]), false)
await check("no edges", isBipartiteGraph(4,[]), true)
await check("path", isBipartiteGraph(3,[[0,1],[1,2]]), true)
await check("odd cycle", isBipartiteGraph(5,[[0,1],[1,2],[2,3],[3,4],[4,0]]), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
