// Generated by generate.ts — hidden adversarial suite for is-email.
// Run via `npx tsx __audit__/isEmail.hidden.ts` inside the scratch project.
import { isEmail } from '../src/isEmail'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("valid basic", isEmail("user@example.com"), true)
await check("valid with plus", isEmail("user+tag@example.co.uk"), true)
await check("missing @", isEmail("userexample.com"), false)
await check("missing domain", isEmail("user@"), false)
await check("missing tld", isEmail("user@example"), false)
await check("empty", isEmail(""), false)
await check("spaces", isEmail("user @example.com"), false)
await check("double @", isEmail("u@@ex.com"), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
