// Generated by generate.ts — hidden adversarial suite for iso-week-number.
// Run via `npx tsx __audit__/isoWeekNumber.hidden.ts` inside the scratch project.
import { isoWeekNumber } from '../src/isoWeekNumber'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("2024-01-01 is week 1", isoWeekNumber(new Date("2024-01-01T00:00:00Z")), 1)
await check("2024-01-07 is week 1", isoWeekNumber(new Date("2024-01-07T00:00:00Z")), 1)
await check("2024-01-08 is week 2", isoWeekNumber(new Date("2024-01-08T00:00:00Z")), 2)
await check("2023-12-31 is week 52", isoWeekNumber(new Date("2023-12-31T00:00:00Z")), 52)
await check("mid year", isoWeekNumber(new Date("2024-06-15T00:00:00Z")), 24)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
