// Generated by generate.ts — hidden adversarial suite for is-palindrome.
// Run via `npx tsx __audit__/isPalindrome.hidden.ts` inside the scratch project.
import { isPalindrome } from '../src/isPalindrome'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("simple palindrome", isPalindrome("racecar"), true)
await check("not palindrome", isPalindrome("hello"), false)
await check("mixed case", isPalindrome("RaceCar"), true)
await check("with spaces/punct", isPalindrome("A man a plan a canal Panama"), true)
await check("empty string", isPalindrome(""), true)
await check("single char", isPalindrome("a"), true)
await check("two same chars", isPalindrome("aa"), true)
await check("two diff chars", isPalindrome("ab"), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
