// Generated by generate.ts — hidden adversarial suite for json-utils.
// Run via `npx tsx __audit__/jsonUtils.hidden.ts` inside the scratch project.
import { jsonDiff, jsonFlatten, jsonUnflatten } from '../src/jsonUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("diff no change", jsonDiff({a:1},{a:1}).length, 0)
await check("diff changed value", jsonDiff({a:1},{a:2})[0], {"path":"a","from":1,"to":2})
await check("diff added key", jsonDiff({},{a:1})[0].path, "a")
await check("diff nested", jsonDiff({a:{b:1}},{a:{b:2}})[0].path, "a.b")
await check("flatten basic", JSON.stringify(jsonFlatten({a:{b:1},c:2})), "{\"a.b\":1,\"c\":2}")
await check("flatten nested", jsonFlatten({x:{y:{z:42}}})["x.y.z"], 42)
await check("unflatten roundtrip", JSON.stringify(jsonUnflatten(jsonFlatten({a:{b:1},c:2}))), "{\"a\":{\"b\":1},\"c\":2}")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
