// Generated by generate.ts — hidden adversarial suite for kmp-search-index.
// Run via `npx tsx __audit__/kmpSearchIndex.hidden.ts` inside the scratch project.
import { kmpSearchIndex } from '../src/kmpSearchIndex'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", kmpSearchIndex("hello world","world"), 6)
await check("overlap start", kmpSearchIndex("aaaa","aa"), 0)
await check("no match", kmpSearchIndex("abc","d"), -1)
await check("empty text", kmpSearchIndex("","a"), -1)
await check("empty pattern", kmpSearchIndex("abc",""), 0)
await check("mid match", kmpSearchIndex("mississippi","issip"), 4)
await check("lps reuse", kmpSearchIndex("abcabcabd","abcabd"), 3)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
