// Generated by generate.ts — hidden adversarial suite for linear-regression-lsq.
// Run via `npx tsx __audit__/linearRegressionLsq.hidden.ts` inside the scratch project.
import { linearRegression } from '../src/linearRegressionLsq'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("proportional line through origin", linearRegression([1,2,3],[2,4,6]), {"slope":2,"intercept":0})
await check("line with positive intercept", linearRegression([0,1,2,3],[1,3,5,7]), {"slope":2,"intercept":1})
await check("noisy fit", linearRegression([1,2,3,4],[6,5,7,10]), {"slope":1.4,"intercept":3.5})
await check("flat horizontal line", linearRegression([1,2,3,4],[5,5,5,5]), {"slope":0,"intercept":5})
await check("negative slope", linearRegression([1,2,3],[6,4,2]), {"slope":-2,"intercept":8})
await check("slope extracted from object", linearRegression([0,1,2,3],[1,3,5,7]).slope, 2)
await check("intercept extracted from object", linearRegression([1,2,3],[2,4,6]).intercept, 0)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
