// Generated by generate.ts — hidden adversarial suite for luhn-check.
// Run via `npx tsx __audit__/luhnCheck.hidden.ts` inside the scratch project.
import { luhnCheck } from '../src/luhnCheck'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("valid 16-digit card with spaces", luhnCheck("4539 1488 0343 6467"), true)
await check("classic valid Luhn number", luhnCheck("79927398713"), true)
await check("invalid last digit", luhnCheck("79927398710"), false)
await check("empty string is invalid", luhnCheck(""), false)
await check("non-digit characters rejected", luhnCheck("abc"), false)
await check("single zero is valid (sum 0)", luhnCheck("0"), true)
await check("two-digit valid case 18", luhnCheck("18"), true)
await check("doubling overflow case 59", luhnCheck("59"), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
