// Generated by generate.ts — hidden adversarial suite for memoize-ttl.
// Run via `npx tsx __audit__/memoizeTTL.hidden.ts` inside the scratch project.
import { memoizeTTL } from '../src/memoizeTTL'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("returns correct value", memoizeTTL((x:number)=>x*2, 1000)(5), 10)
await check("caches within TTL", (()=>{let n=0;const f=memoizeTTL(()=>++n,1000);f();f();return n})(), 1)
await check("recomputes after TTL", (()=>{let n=0,t=0;const f=memoizeTTL(()=>++n,100,()=>t);f();t=200;f();return n})(), 2)
await check("different args separate", (()=>{const f=memoizeTTL((x:number)=>x,1000);return [f(1),f(2)]})(), [1,2])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
