// Generated by generate.ts — hidden adversarial suite for moving-median-window.
// Run via `npx tsx __audit__/movingMedianWindow.hidden.ts` inside the scratch project.
import { movingMedian } from '../src/movingMedianWindow'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("window larger than input is empty", movingMedian([1,2], 5), [])
await check("zero window is empty", movingMedian([1,2,3], 0), [])
await check("window of one is identity", movingMedian([5,1,3], 1), [5,1,3])
await check("odd window of three", movingMedian([1,3,2,5,4], 3), [2,3,4])
await check("even window averages middle two", movingMedian([1,3,2,5], 2), [2,2.5,3.5])
await check("full even window once", movingMedian([4,1,3,2], 4), [2.5])
await check("sorts within each window", movingMedian([9,1,5], 3), [5])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
