// Generated by generate.ts — hidden adversarial suite for mulberry32-prng.
// Run via `npx tsx __audit__/mulberry32Prng.hidden.ts` inside the scratch project.
import { mulberry32 } from '../src/mulberry32Prng'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("returns function", typeof mulberry32(42), "function")
await check("deterministic", mulberry32(42)() === mulberry32(42)(), true)
await check("in range 0-1", (() => { const r = mulberry32(1)(); return r >= 0 && r < 1 })(), true)
await check("different seeds differ", mulberry32(1)() !== mulberry32(2)(), true)
await check("sequence reproducible", (() => { const a = mulberry32(99); return [a(),a(),a()] })(), (() => { const b = mulberry32(99); return [b(),b(),b()] })())
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
