// Generated by generate.ts — hidden adversarial suite for negate-predicate.
// Run via `npx tsx __audit__/negatePredicate.hidden.ts` inside the scratch project.
import { negate } from '../src/negatePredicate'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("negates true", negate((x:number)=>x>0)(5), false)
await check("negates false", negate((x:number)=>x>0)(-5), true)
await check("isEven to isOdd", negate((x:number)=>x%2===0)(3), true)
await check("multi-arg", negate((a:number,b:number)=>a>b)(1,2), true)
await check("double negate", negate(negate((x:number)=>x>0))(5), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
