// Generated by generate.ts — hidden adversarial suite for number-theory.
// Run via `npx tsx __audit__/numberTheory.hidden.ts` inside the scratch project.
import { gcd, lcm, isPrime, factorial, fibonacci } from '../src/numberTheory'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("gcd basic", gcd(12, 8), 4)
await check("gcd primes", gcd(13, 7), 1)
await check("gcd with zero", gcd(0, 5), 5)
await check("lcm basic", lcm(4, 6), 12)
await check("lcm with zero", lcm(0, 5), 0)
await check("isPrime 2", isPrime(2), true)
await check("isPrime 1", isPrime(1), false)
await check("isPrime 17", isPrime(17), true)
await check("isPrime 4", isPrime(4), false)
await check("isPrime 97", isPrime(97), true)
await check("factorial 0", factorial(0), 1)
await check("factorial 5", factorial(5), 120)
await check("fibonacci 0", fibonacci(0), 0)
await check("fibonacci 1", fibonacci(1), 1)
await check("fibonacci 10", fibonacci(10), 55)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
