// Generated by generate.ts — hidden adversarial suite for number-format-utils.
// Run via `npx tsx __audit__/numberFormatUtils.hidden.ts` inside the scratch project.
import { ordinal, toRoman, fromRoman } from '../src/numberFormatUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("ordinal 1", ordinal(1), "1st")
await check("ordinal 2", ordinal(2), "2nd")
await check("ordinal 3", ordinal(3), "3rd")
await check("ordinal 4", ordinal(4), "4th")
await check("ordinal 11", ordinal(11), "11th")
await check("ordinal 12", ordinal(12), "12th")
await check("ordinal 21", ordinal(21), "21st")
await check("toRoman 1", toRoman(1), "I")
await check("toRoman 4", toRoman(4), "IV")
await check("toRoman 9", toRoman(9), "IX")
await check("toRoman 2024", toRoman(2024), "MMXXIV")
await check("fromRoman XIV", fromRoman("XIV"), 14)
await check("fromRoman MMXXIV", fromRoman("MMXXIV"), 2024)
await check("roundtrip", fromRoman(toRoman(42)), 42)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
