// Generated by generate.ts — hidden adversarial suite for object-diff.
// Run via `npx tsx __audit__/objectDiff.hidden.ts` inside the scratch project.
import { objectDiff } from '../src/objectDiff'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("added key", JSON.stringify(objectDiff({a:1},{a:1,b:2}).added), "{\"b\":2}")
await check("removed key", JSON.stringify(objectDiff({a:1,b:2},{a:1}).removed), "{\"b\":2}")
await check("changed key", objectDiff({a:1},{a:2}).changed["a"], {"from":1,"to":2})
await check("no diff", JSON.stringify(objectDiff({a:1},{a:1})), "{\"added\":{},\"removed\":{},\"changed\":{}}")
await check("nested change detected", Object.keys(objectDiff({a:{b:1}},{a:{b:2}}).changed).length, 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
