// Generated by generate.ts — hidden adversarial suite for parse-semver-parts.
// Run via `npx tsx __audit__/parseSemverParts.hidden.ts` inside the scratch project.
import { parseSemverParts, compareSemver } from '../src/parseSemverParts'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parse basic", parseSemverParts("1.2.3"), {"major":1,"minor":2,"patch":3,"prerelease":""})
await check("parse v prefix", parseSemverParts("v2.0.0"), {"major":2,"minor":0,"patch":0,"prerelease":""})
await check("parse pre", parseSemverParts("1.0.0-beta.1"), {"major":1,"minor":0,"patch":0,"prerelease":"beta.1"})
await check("parse invalid", parseSemverParts("1.2"), null)
await check("compare equal", compareSemver("1.2.3","1.2.3"), 0)
await check("higher minor", compareSemver("1.3.0","1.2.0"), 1)
await check("lower patch", compareSemver("1.0.0","1.0.1"), -1)
await check("pre is lower", compareSemver("1.0.0-alpha","1.0.0"), -1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
