// Generated by generate.ts — hidden adversarial suite for parse-cron-fields.
// Run via `npx tsx __audit__/parseCronFields.hidden.ts` inside the scratch project.
import { parseCronFields } from '../src/parseCronFields'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", parseCronFields("0 * * * *"), {"minute":"0","hour":"*","dayOfMonth":"*","month":"*","dayOfWeek":"*"})
await check("complex", parseCronFields("*/5 8-18 * * 1-5"), {"minute":"*/5","hour":"8-18","dayOfMonth":"*","month":"*","dayOfWeek":"1-5"})
await check("four fields", parseCronFields("* * * *"), null)
await check("six fields", parseCronFields("0 0 * * * *"), null)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
