// Generated by generate.ts — hidden adversarial suite for parse-data-uri.
// Run via `npx tsx __audit__/parseDataUri.hidden.ts` inside the scratch project.
import { parseDataUri } from '../src/parseDataUri'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("base64 png", parseDataUri("data:image/png;base64,abc123"), {"mime":"image/png","isBase64":true,"data":"abc123"})
await check("text plain", parseDataUri("data:text/plain,hello"), {"mime":"text/plain","isBase64":false,"data":"hello"})
await check("invalid", parseDataUri("notadata"), null)
await check("no mime", parseDataUri("data:,hello"), {"mime":"text/plain","isBase64":false,"data":"hello"})
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
