// Generated by generate.ts — hidden adversarial suite for percent-encode.
// Run via `npx tsx __audit__/percentEncode.hidden.ts` inside the scratch project.
import { percentEncode, percentDecode } from '../src/percentEncode'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("space", percentEncode("hello world"), "hello%20world")
await check("special chars", percentEncode("a+b=c"), "a%2Bb%3Dc")
await check("decode", percentDecode("hello%20world"), "hello world")
await check("roundtrip", percentDecode(percentEncode("hello/world?q=1")), "hello/world?q=1")
await check("plain passthrough", percentEncode("abc"), "abc")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
