// Generated by generate.ts — hidden adversarial suite for priority-queue-min.
// Run via `npx tsx __audit__/priorityQueueMin.hidden.ts` inside the scratch project.
import { PriorityQueue } from '../src/priorityQueueMin'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("lowest first", (() => { const q = new PriorityQueue<string>(); q.push("a",3); q.push("b",1); q.push("c",2); return q.pop() })(), "b")
await check("full order", (() => { const q = new PriorityQueue<number>(); [5,1,4,2,3].forEach(n=>q.push(n,n)); return [q.pop(),q.pop(),q.pop()] })(), [1,2,3])
await check("peek", (() => { const q = new PriorityQueue<number>(); q.push(9,9); q.push(1,1); return q.peek() })(), 1)
await check("size", (() => { const q = new PriorityQueue<number>(); q.push(1,1); q.push(2,2); return q.size() })(), 2)
await check("empty pop", new PriorityQueue().pop(), undefined)
await check("isEmpty", new PriorityQueue().isEmpty(), true)
await check("peek does not remove", (() => { const q = new PriorityQueue<number>(); q.push(1,1); q.peek(); return q.size() })(), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
