// Generated by generate.ts — hidden adversarial suite for queue.
// Run via `npx tsx __audit__/queue.hidden.ts` inside the scratch project.
import { Queue } from '../src/queue'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("enqueue and dequeue FIFO", (() => { const q = new Queue<number>(); q.enqueue(1); q.enqueue(2); return q.dequeue() })(), 1)
await check("peek first", (() => { const q = new Queue<number>(); q.enqueue(1); q.enqueue(2); return q.peek() })(), 1)
await check("isEmpty true", new Queue().isEmpty(), true)
await check("dequeue empty", new Queue().dequeue(), undefined)
await check("size after enqueue", (() => { const q = new Queue<number>(); q.enqueue(1); q.enqueue(2); return q.size() })(), 2)
await check("size after dequeue", (() => { const q = new Queue<number>(); q.enqueue(1); q.enqueue(2); q.dequeue(); return q.size() })(), 1)
await check("toArray order", (() => { const q = new Queue<number>(); q.enqueue(1); q.enqueue(2); q.enqueue(3); return q.toArray() })(), [1,2,3])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
