// Generated by generate.ts — hidden adversarial suite for random-int.
// Run via `npx tsx __audit__/randomInt.hidden.ts` inside the scratch project.
import { randomInt } from '../src/randomInt'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("in range", (() => { const n = randomInt(1, 10); return n >= 1 && n <= 10 })(), true)
await check("min equals max", randomInt(5, 5), 5)
await check("deterministic with rng", randomInt(0, 9, () => 0), 0)
await check("deterministic max", randomInt(0, 9, () => 0.9999), 9)
await check("negative range", randomInt(-5, -1, () => 0), -5)
await check("is integer", Number.isInteger(randomInt(1, 100)), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
