// Generated by generate.ts — hidden adversarial suite for roll-dice.
// Run via `npx tsx __audit__/rollDice.hidden.ts` inside the scratch project.
import { rollDice } from '../src/rollDice'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("min when rng=0", rollDice(6,1,()=>0), 1)
await check("max when rng near 1", rollDice(6,1,()=>0.9999), 6)
await check("two dice", rollDice(6,2,()=>0), 2)
await check("zero dice", rollDice(6,0,()=>0), 0)
await check("d20", rollDice(20,1,()=>0.95), 20)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
