// Generated by generate.ts — hidden adversarial suite for rot47.
// Run via `npx tsx __audit__/rot47.hidden.ts` inside the scratch project.
import { rot47 } from '../src/rot47'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("hello", rot47("Hello, World!"), "w6==@[ (@C=5P")
await check("involution", rot47(rot47("Hello, World!")), "Hello, World!")
await check("space preserved", rot47("a b"), "2 3")
await check("involution abc", rot47(rot47("abc")), "abc")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
