// Generated by generate.ts — hidden adversarial suite for safe-json.
// Run via `npx tsx __audit__/safeJSON.hidden.ts` inside the scratch project.
import { safeJSONParse, safeJSONStringify } from '../src/safeJSON'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parse valid", safeJSONParse('{"a":1}'), {"a":1})
await check("parse invalid returns null", safeJSONParse("not json"), null)
await check("parse with fallback", safeJSONParse("bad", 42), 42)
await check("stringify basic", safeJSONStringify({a:1,b:2}), "{\"a\":1,\"b\":2}")
await check("stringify circular safe", (() => { const o: any = {a:1}; o.self = o; return safeJSONStringify(o) })(), "{\"a\":1,\"self\":\"[Circular]\"}")
await check("stringify with space", safeJSONStringify({a:1}, 2).includes("\n"), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
