// Generated by generate.ts — hidden adversarial suite for sample-without-replacement.
// Run via `npx tsx __audit__/sampleWithoutReplacement.hidden.ts` inside the scratch project.
import { sampleWithoutReplacement } from '../src/sampleWithoutReplacement'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("correct size", sampleWithoutReplacement([1,2,3,4,5],3,42).length, 3)
await check("no duplicates", (() => { const s = sampleWithoutReplacement([1,2,3,4,5],5,1); return new Set(s).size })(), 5)
await check("deterministic", JSON.stringify(sampleWithoutReplacement([1,2,3,4],2,9)) === JSON.stringify(sampleWithoutReplacement([1,2,3,4],2,9)), true)
await check("no mutate", (() => { const a=[1,2,3]; sampleWithoutReplacement(a,2,1); return a })(), [1,2,3])
await check("k >= len returns all", sampleWithoutReplacement([1,2],5,1).sort((a,b)=>a-b), [1,2])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
