// Generated by generate.ts — hidden adversarial suite for schema-validate.
// Run via `npx tsx __audit__/schemaValidate.hidden.ts` inside the scratch project.
import { validate, createSchema } from '../src/schemaValidate'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("valid object", validate({name:"Alice",age:25},{name:{type:"string",required:true},age:{type:"number",min:0}}).valid, true)
await check("missing required", validate({},{name:{required:true}}).valid, false)
await check("wrong type", validate({age:"25"},{age:{type:"number"}}).valid, false)
await check("min number", validate({age:-1},{age:{type:"number",min:0}}).valid, false)
await check("max string length", validate({name:"toolongname"},{name:{type:"string",max:5}}).valid, false)
await check("enum valid", validate({color:"red"},{color:{enum:["red","blue"]}}).valid, true)
await check("enum invalid", validate({color:"green"},{color:{enum:["red","blue"]}}).valid, false)
await check("createSchema", createSchema({x:{type:"number",required:true}})({x:1}).valid, true)
await check("error messages", validate({},{name:{required:true}}).errors.length, 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
