// Generated by generate.ts — hidden adversarial suite for shuffle.
// Run via `npx tsx __audit__/shuffle.hidden.ts` inside the scratch project.
import { shuffle, sample } from '../src/shuffle'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("shuffle same elements", shuffle([1,2,3,4,5], ()=>0.5).sort((a,b)=>a-b), [1,2,3,4,5])
await check("shuffle length preserved", shuffle([1,2,3]).length, 3)
await check("shuffle does not mutate", (() => { const a=[1,2,3]; shuffle(a); return a })(), [1,2,3])
await check("shuffle empty", shuffle([]), [])
await check("sample from array", [1,2,3].includes(sample([1,2,3])!), true)
await check("sample empty", sample([]), undefined)
await check("sample single", sample([42]), 42)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
