// Generated by generate.ts — hidden adversarial suite for sieve-of-eratosthenes.
// Run via `npx tsx __audit__/sieveOfEratosthenes.hidden.ts` inside the scratch project.
import { sieveOfEratosthenes } from '../src/sieveOfEratosthenes'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("n below 2 yields empty", sieveOfEratosthenes(1), [])
await check("n=0 empty", sieveOfEratosthenes(0), [])
await check("smallest prime boundary n=2", sieveOfEratosthenes(2), [2])
await check("includes endpoint when prime", sieveOfEratosthenes(11), [2,3,5,7,11])
await check("excludes endpoint when composite", sieveOfEratosthenes(10), [2,3,5,7])
await check("primes up to 30", sieveOfEratosthenes(30), [2,3,5,7,11,13,17,19,23,29])
await check("negative input empty", sieveOfEratosthenes(-5), [])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
