// Generated by generate.ts — hidden adversarial suite for slugify-unicode.
// Run via `npx tsx __audit__/slugifyUnicode.hidden.ts` inside the scratch project.
import { slugifyUnicode } from '../src/slugifyUnicode'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", slugifyUnicode("Hello World"), "hello-world")
await check("special chars", slugifyUnicode("Hello, World!"), "hello-world")
await check("multiple spaces", slugifyUnicode("  foo   bar  "), "foo-bar")
await check("accents", slugifyUnicode("café"), "cafe")
await check("empty", slugifyUnicode(""), "")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
