// Generated by generate.ts — hidden adversarial suite for stack.
// Run via `npx tsx __audit__/stack.hidden.ts` inside the scratch project.
import { Stack } from '../src/stack'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("push and pop", (() => { const s = new Stack<number>(); s.push(1); s.push(2); return s.pop() })(), 2)
await check("peek does not remove", (() => { const s = new Stack<number>(); s.push(1); s.peek(); return s.size() })(), 1)
await check("isEmpty true", new Stack().isEmpty(), true)
await check("isEmpty false", (() => { const s = new Stack<number>(); s.push(1); return s.isEmpty() })(), false)
await check("pop empty", new Stack().pop(), undefined)
await check("size", (() => { const s = new Stack<number>(); s.push(1); s.push(2); s.push(3); return s.size() })(), 3)
await check("toArray order", (() => { const s = new Stack<number>(); s.push(1); s.push(2); return s.toArray() })(), [1,2])
await check("clear", (() => { const s = new Stack<number>(); s.push(1); s.clear(); return s.size() })(), 0)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
