// Generated by generate.ts — hidden adversarial suite for string-padding.
// Run via `npx tsx __audit__/stringPadding.hidden.ts` inside the scratch project.
import { padLeft, padRight, padBoth } from '../src/stringPadding'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("padLeft basic", padLeft("5", 3, "0"), "005")
await check("padLeft spaces", padLeft("hi", 5), "   hi")
await check("padLeft no change", padLeft("hello", 3), "hello")
await check("padRight basic", padRight("hi", 5, "."), "hi...")
await check("padRight spaces", padRight("hi", 4), "hi  ")
await check("padBoth even", padBoth("hi", 6), "  hi  ")
await check("padBoth odd", padBoth("hi", 5), " hi  ")
await check("padBoth no change", padBoth("hello", 3), "hello")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
