// Generated by generate.ts — hidden adversarial suite for string-search.
// Run via `npx tsx __audit__/stringSearch.hidden.ts` inside the scratch project.
import { editDistance, fuzzyScore } from '../src/stringSearch'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("editDistance same", editDistance("hello", "hello"), 0)
await check("editDistance kitten sitting", editDistance("kitten", "sitting"), 3)
await check("editDistance one deletion", editDistance("abc", "ac"), 1)
await check("editDistance one insertion", editDistance("ac", "abc"), 1)
await check("editDistance one substitution", editDistance("cat", "bat"), 1)
await check("editDistance empty", editDistance("", "abc"), 3)
await check("fuzzyScore exact", fuzzyScore("hello", "hello") > 0, true)
await check("fuzzyScore no match", fuzzyScore("xyz", "hello"), 0)
await check("fuzzyScore partial", fuzzyScore("hlo", "hello") > 0, true)
await check("fuzzyScore empty pattern", fuzzyScore("", "hello"), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
