// Generated by generate.ts — hidden adversarial suite for table-format.
// Run via `npx tsx __audit__/tableFormat.hidden.ts` inside the scratch project.
import { formatTable } from '../src/tableFormat'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic table", formatTable([{a:"x",b:"y"}]).includes("a"), true)
await check("has separator", formatTable([{n:"Alice",age:"30"}]).includes("---"), true)
await check("empty returns empty", formatTable([]), "")
await check("includes data", formatTable([{name:"Bob"}]).includes("Bob"), true)
await check("custom columns", formatTable([{a:1,b:2,c:3}],["a","c"]).includes("b"), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
