// Generated by generate.ts — hidden adversarial suite for to-base64-url.
// Run via `npx tsx __audit__/toBase64Url.hidden.ts` inside the scratch project.
import { toBase64Url, fromBase64Url } from '../src/toBase64Url'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("encode hello", toBase64Url("hello"), "aGVsbG8")
await check("no padding", toBase64Url("hello").includes("="), false)
await check("no slash", toBase64Url("hello world").includes("/"), false)
await check("roundtrip", fromBase64Url(toBase64Url("Hello, World!")), "Hello, World!")
await check("decode hello", fromBase64Url("aGVsbG8"), "hello")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
