// Generated by generate.ts — hidden adversarial suite for topo-order-kahn.
// Run via `npx tsx __audit__/topoOrderKahn.hidden.ts` inside the scratch project.
import { topoOrderKahn } from '../src/topoOrderKahn'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("diamond", topoOrderKahn(4,[[0,1],[0,2],[1,3],[2,3]]), [0,1,2,3])
await check("cycle", topoOrderKahn(2,[[0,1],[1,0]]), [])
await check("no edges", topoOrderKahn(3,[]), [0,1,2])
await check("reversed chain", topoOrderKahn(3,[[2,1],[1,0]]), [2,1,0])
await check("self loop", topoOrderKahn(2,[[0,0]]), [])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
