// Generated by generate.ts — hidden adversarial suite for truncate.
// Run via `npx tsx __audit__/truncate.hidden.ts` inside the scratch project.
import { truncate } from '../src/truncate'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("no truncation needed", truncate("hello", 10), "hello")
await check("exact length", truncate("hello", 5), "hello")
await check("truncated with ellipsis", truncate("hello world", 8), "hello...")
await check("custom ellipsis", truncate("hello world", 7, "…"), "hello …")
await check("very short max", truncate("hello", 3), "...")
await check("empty string", truncate("", 5), "")
await check("maxLength equals ellipsis length", truncate("hi there", 3), "...")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
