// Generated by generate.ts — hidden adversarial suite for user/slugify.
// Run via `npx tsx __audit__/user_slugify.hidden.ts` inside the scratch project.
import { slugify } from '../src/lib/slugify'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("slugify(\"Hello World\") === \"hello-world\"", slugify("Hello World"), "hello-world")
await check("slugify(\"A  B!\") === \"a-b\"", slugify("A  B!"), "a-b")
await check("slugify(\"  Already-Slugged \") === \"already-slugged\"", slugify("  Already-Slugged "), "already-slugged")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
