// Generated by generate.ts — hidden adversarial suite for zip-with.
// Run via `npx tsx __audit__/zipWith.hidden.ts` inside the scratch project.
import { zipWith } from '../src/zipWith'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("add", zipWith([1,2,3],[10,20,30],(a,b)=>a+b), [11,22,33])
await check("shorter b", zipWith([1,2,3],[10,20],(a,b)=>a+b), [11,22])
await check("empty", zipWith([],[1,2],(a,b)=>a), [])
await check("pairs", zipWith([1,2],["a","b"],(a,b)=>[a,b]), [[1,"a"],[2,"b"]])
await check("multiply", zipWith([2,3],[4,5],(a,b)=>a*b), [8,15])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
