// Generated by generate.ts — hidden adversarial suite for zscore-normalize.
// Run via `npx tsx __audit__/zScoreNormalizeArr.hidden.ts` inside the scratch project.
import { zScoreNormalize } from '../src/zScoreNormalizeArr'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("empty array returns empty", zScoreNormalize([]), [])
await check("constant array all zeros", zScoreNormalize([5,5,5]), [0,0,0])
await check("single element is zero", zScoreNormalize([42]), [0])
await check("symmetric three values", zScoreNormalize([1,2,3]), [-1.224744871391589,0,1.224744871391589])
await check("four value spread", zScoreNormalize([2,4,6,8]), [-1.3416407864998738,-0.4472135954999579,0.4472135954999579,1.3416407864998738])
await check("mean maps to zero", zScoreNormalize([1,2,3])[1], 0)
await check("length preserved", zScoreNormalize([2,4,6,8]).length, 4)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
