// Derive runnable behavioral or property tests from a spec.
//
// deriveTests        — extracts worked examples from spec text (f(x)===y lines).
// derivePropertyTests — generates family-specific property tests when no examples exist.
//                       Used by L2 as a fallback so prose-only specs can still be oracle-gated.
//
// Supported example forms for deriveTests:
//   editDistance('kitten','sitting') === 3
//   chunk([1,2,3], 2) -> [[1,2],[3]]
//   slug("Hello World") => "hello-world"
//   f(x) returns y
import { extractFeatures, type SynthFile } from './synthEngine'

export interface DerivedTests { testFile: SynthFile; count: number }

const SEP = /\s*(?:===|==>|=>|->|→|\breturns?\b|\bgives?\b)\s*/

/** Escape a string for embedding in a RegExp constructor. */
function escapeRe(s: string): string { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') }

/** Raw declared parameter-list text for `name` from the spec's own "Exact public API"
 *  signature (e.g. `export function unionTags(a: string[], b: string[]): string[]`) —
 *  read from the PROMPT text, not candidate code, since property tests here are built
 *  before any candidate exists. Returns null when no such declaration is found. */
function getSpecParamsRaw(spec: string, name: string): string | null {
  const esc = escapeRe(name)
  const m = spec.match(new RegExp(`\\bfunction\\s+${esc}\\s*\\(([^)]*)\\)`))
  return m ? m[1] : null
}

/** Count top-level (bracket-depth-0) comma-separated params in a signature's param string. */
function countTopLevelParams(params: string): number {
  const trimmed = params.trim()
  if (!trimmed) return 0
  let depth = 0, count = 1
  for (const ch of trimmed) {
    if ('<([{'.includes(ch)) depth++
    else if ('>)]}'.includes(ch)) depth--
    else if (ch === ',' && depth === 0) count++
  }
  return count
}

export interface SpecExample { lhs: string; rhs: string }

/** Extract the worked `call → expected` example pairs from a spec's own text.
 *  This is deriveTests' exact extraction, exported so the user-skill pipeline can
 *  record the SAME examples the oracle verified into a catalog entry's tests[]. */
export function extractSpecExamples(spec: string): SpecExample[] {
  const feats = extractFeatures(spec)
  const names = feats.exports
  if (!names.length) return []
  const nameAlt = names.map(n => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')
  const callsAName = new RegExp(`\\b(?:${nameAlt})\\s*\\(`)

  const examples: SpecExample[] = []
  for (const line of spec.split('\n')) {
    const t = line.trim().replace(/^[-*\d.)\s]+/, '')   // strip list bullets / numbering
    if (!callsAName.test(t)) continue
    const parts = t.split(SEP)
    if (parts.length !== 2) continue
    const lhs = parts[0].trim()
    let rhs = parts[1].trim().replace(/[.;,]+$/, '')
    if (!lhs || !rhs) continue
    if (!callsAName.test(lhs)) continue            // LHS must be the call
    examples.push({ lhs, rhs })
  }
  return examples
}

export function deriveTests(spec: string, modulePath: string): DerivedTests | null {
  const feats = extractFeatures(spec)
  const names = feats.exports
  if (!names.length) return null

  const examples = extractSpecExamples(spec)
  if (!examples.length) return null

  const importSpec = '../' + modulePath.replace(/\.tsx?$/, '')   // test sits in __derived__/
  const body = examples.map((e, i) => `
try {
  const got_${i}: unknown = (${e.lhs})
  const exp_${i}: unknown = (${e.rhs})
  const ok_${i} = eq(got_${i}, exp_${i})
  console.log((ok_${i} ? 'PASS' : 'FAIL') + ' — ${e.lhs.replace(/'/g, "\\'").replace(/`/g, '\\`')} === ${e.rhs.replace(/'/g, "\\'").replace(/`/g, '\\`')}' + (ok_${i} ? '' : '  (got ' + JSON.stringify(got_${i}) + ')'))
  if (!ok_${i}) failures++
} catch (err) { console.log('FAIL — ${e.lhs.replace(/'/g, "\\'")} threw ' + String(err)); failures++ }`).join('')

  const content = `// Spec-derived behavioral test (auto-generated by Crucible synth/derive).
import { ${names.join(', ')} } from '${importSpec}'
function eq(a: unknown, b: unknown): boolean { return JSON.stringify(a) === JSON.stringify(b) }
let failures = 0
${body}
console.log(failures === 0 ? 'ALL PASS' : failures + ' FAILURE(S)')
process.exit(failures === 0 ? 0 : 1)
`
  return { testFile: { path: '__derived__/spec.test.ts', content }, count: examples.length }
}

// ── Phase 3: property-based derivation ──────────────────────────────────────
//
// Generates weaker-but-universal property tests when the spec has no worked examples.
// Properties are strictly tiered below behavioral tests — the result is labeled
// 'property' so callers can decide how much trust to grant.
//
// High-confidence families (safe to oracle-gate):
//   validator  → named `is*` → returns boolean on any string input
//   codec      → has *Encode + *Decode → decode(encode(x)) === x (roundtrip)
//   sort       → named *[Ss]ort → output is sorted permutation of input
//   transform  → returns same type as input (string → string)
//
// Lower-confidence families are NOT included — better to escalate honestly.

export interface PropertyTests extends DerivedTests {
  family: string
}

export function derivePropertyTests(spec: string, modulePath: string): PropertyTests | null {
  const feats = extractFeatures(spec)
  if (!feats.exports.length) return null

  const importPath = '../' + modulePath.replace(/\.tsx?$/, '')
  const lower = feats.lower
  const assertions: string[] = []
  let family = ''

  // ── Codec: *Encode + *Decode pair → roundtrip ──────────────────────────────
  const encoders = feats.exports.filter(n => /[Ee]ncode/.test(n))
  const decoders = feats.exports.filter(n => /[Dd]ecode/.test(n))
  if (encoders.length && decoders.length) {
    family = 'codec'
    const enc = encoders[0], dec = decoders[0]
    assertions.push(
      `prop('roundtrip empty', ${dec}(${enc}('')) === '')`,
      `prop('roundtrip hello', ${dec}(${enc}('hello')) === 'hello')`,
      `prop('roundtrip special', ${dec}(${enc}('Hello, World! 123')) === 'Hello, World! 123')`,
    )
  }

  // ── Validator: is* functions → always returns boolean ─────────────────────
  const validators = feats.exports.filter(n => /^is[A-Z]/.test(n))
  if (!family && validators.length) {
    family = 'validator'
    for (const name of validators.slice(0, 4)) {
      assertions.push(
        `prop('${name} returns bool on empty', typeof ${name}('') === 'boolean')`,
        `prop('${name} returns bool on string', typeof ${name}('test@example.com') === 'boolean')`,
        `prop('${name} false on empty string', ${name}('') === false)`,
      )
    }
  }

  // ── Sort: *[Ss]ort → output is sorted permutation (must look like comparison sort) ──────
  // Exclude topological sorts (take nodes+edges) and similar structural sorts.
  //
  // TWO BUGS FOUND 2026-07-04 root-causing sortModule's 0/3 "never produces a module":
  // 1. The `/[Ss]ort/` name filter also matches a co-declared `SortOpts` INTERFACE (e.g.
  //    "export interface SortOpts { ... }" alongside "export function sortProducts(...)") —
  //    `feats.exports` lists the interface first, so `sorters[0]` picked 'SortOpts' (not a
  //    function at all) as "the sorter" and generated a test calling it as one. Fixed by
  //    excluding names the spec declares via `interface`/`type` before treating them as a
  //    callable sorter.
  // 2. Even with the right name, this family's tests call `name([3,1,2])` — a single-arg
  //    numeric-array signature. A sorter like `sortProducts(products: Product[], opts:
  //    SortOpts)` takes TWO args, so the generated test itself fails tsc (wrong arity/type)
  //    regardless of whether the candidate is correct — a false-negative self-inflicted
  //    oracle failure, not a real generation-capability gap. Only apply this family when the
  //    spec's own declared signature for the sorter is single-arg (or no signature is found
  //    at all, preserving old behavior for looser specs).
  const isTopo = /topolog|topo[_\s-]?sort|dependency/i.test(lower)
  const sorters = feats.exports.filter(n =>
    /[Ss]ort/.test(n) && !/topo|topolog/i.test(n) &&
    !new RegExp(`\\b(?:interface|type)\\s+${escapeRe(n)}\\b`).test(spec),
  )
  if (!family && sorters.length && !isTopo) {
    const name = sorters[0]
    const sig = spec.match(new RegExp(`\\bfunction\\s+${escapeRe(name)}\\s*\\(([^)]*)\\)`))
      ?? spec.match(new RegExp(`\\b${escapeRe(name)}\\s*\\(([^)]*)\\)\\s*:`))
    const arity = sig ? countTopLevelParams(sig[1]) : 1
    if (arity <= 1) {
      family = 'sort'
      assertions.push(
        `prop('${name} returns array', Array.isArray(${name}([])))`,
        `prop('${name} sorted [3,1,2]', (() => { const r=${name}([3,1,2]); return r[0]<=r[1] && r[1]<=r[2] })())`,
        `prop('${name} preserves length', ${name}([5,3,1,4,2]).length === 5)`,
        `prop('${name} empty', ${name}([]).length === 0)`,
        `prop('${name} same elements', JSON.stringify(${name}([3,1,2]).slice().sort((a,b)=>a-b)) === '[1,2,3]')`,
      )
    }
    // arity >= 2 (e.g. items+opts) falls through — a multi-key/opts sorter is a different
    // shape than this family covers; skip rather than emit a broken test. May be picked up
    // by deriveInvariantTests (context-getter-fed runtime checks) or fall to gate-A-only.
  }

  // ── String transform: single export, takes string → returns string ─────────
  // 2026-07-06: name-substring match alone isn't enough to gate this family — found live
  // via `caseCompareModule`'s `compareCaseInsensitive(a: string, b: string)`, whose name
  // contains "Case" and so matched `/case/i` even though it's a 2-arg comparator, not a
  // 1-arg string transform. The family then called it with a single string argument
  // (`${name}('')`), which fails tsc on the generated test file itself
  // (`Expected 2 arguments, but got 1`) — an unwinnable gate for a real, correctly-typed
  // comparator, same false-positive-by-name-collision class as items 11/24/25/30/31.
  // Arity-gate it (mirrors the 'sort' family's own arity check just above) so a 2-arg
  // export falls through to the 'comparator' family instead of being misclassified here.
  const transforms = feats.exports.filter(n => {
    if (n.startsWith('is') || sorters.includes(n)) return false
    if (!/case|capitaliz|slug|wrap|trim|pad|strip|format|encode|decode|escape|unescape|reverse|truncat/i.test(n)) return false
    const sig = getSpecParamsRaw(feats.raw, n)
    return sig === null || countTopLevelParams(sig) <= 1
  })
  if (!family && transforms.length === 1) {
    family = 'string-transform'
    const name = transforms[0]
    assertions.push(
      `prop('${name} returns string on empty', typeof ${name}('') === 'string')`,
      `prop('${name} returns string', typeof ${name}('hello world') === 'string')`,
    )
    // Idempotency for case transforms (capitalize/title-case/slug are stable on their own output)
    if (/case|slug|capitaliz/i.test(name)) {
      assertions.push(`prop('${name} idempotent on output', (() => { const r=${name}('hello world'); return ${name}(r) === r })())`)
    }
  }

  // ── Object transform: single export, takes an object → returns an object ────
  // Narrow, name-gated family (flatten/unflatten/invert/pick/omit/mapValues style).
  // Property is weak (shape-preserving), so it is strictly name-conditioned and the
  // empty-object identity (f({}) is an object) must hold — enough to gate intent.
  const objTransforms = feats.exports.filter(n =>
    /^(flatten|unflatten|invert|mapValues|mapKeys|filterValues|deepMerge|omitBy|pickBy)/i.test(n)
  )
  if (!family && objTransforms.length === 1) {
    family = 'object-transform'
    const name = objTransforms[0]
    assertions.push(
      `prop('${name} returns object on empty', (() => { const r=${name}({}); return r !== null && typeof r === 'object' && !Array.isArray(r) })())`,
      `prop('${name} empty in → empty out', JSON.stringify(${name}({})) === '{}')`,
      `prop('${name} returns object', (() => { const r=${name}({a:1}); return r !== null && typeof r === 'object' })())`,
    )
  }

  // ── Comparator: compare*/ascending/descending → antisymmetric + reflexive ───
  // compare(a,a)===0, sign(compare(a,b))=== -sign(compare(b,a)), returns number.
  // Name-gated tightly to avoid matching arbitrary functions that take two args.
  const comparators = feats.exports.filter(n =>
    /^(compare|comparator|ascending|descending|byKey|sortKey|cmp)/i.test(n)
  )
  if (!family && comparators.length >= 1) {
    family = 'comparator'
    const name = comparators[0]
    // 2026-07-06: same closed-world bug as the set-op fix above — this family used to
    // unconditionally call the candidate with BOTH a numeric pair and a string pair
    // regardless of the spec's declared param types. A comparator explicitly typed
    // `(a: string, b: string)` (e.g. `compareVersions(a: string, b: string): number`)
    // fails tsc on the generated test file itself (`${name}(1, 2)` — number not
    // assignable to string), an unwinnable oracle gate identical in shape to the
    // tagSetModule root cause. Sniff the declared signature and only emit the
    // assertion shape(s) that actually typecheck; untyped/generic signatures keep
    // both (unchanged behavior).
    const paramsRaw = getSpecParamsRaw(feats.raw, name)
    const stringOnly = paramsRaw !== null && /:\s*string\b/.test(paramsRaw) && !/:\s*number\b/.test(paramsRaw)
    const numberOnly = paramsRaw !== null && /:\s*number\b/.test(paramsRaw) && !/:\s*string\b/.test(paramsRaw)
    if (!stringOnly) {
      assertions.push(
        `prop('${name} returns number', typeof ${name}(1, 2) === 'number')`,
        `prop('${name} reflexive', ${name}(1, 1) === 0)`,
        `prop('${name} antisymmetric numbers', (() => { const ab=${name}(1,2), ba=${name}(2,1); return (ab < 0 && ba > 0) || (ab > 0 && ba < 0) })())`,
      )
    }
    if (!numberOnly) {
      assertions.push(
        `prop('${name} reflexive string', ${name}('a', 'a') === 0)`,
        `prop('${name} antisymmetric strings', (() => { const ab=${name}('a','b'), ba=${name}('b','a'); return (ab < 0 && ba > 0) || (ab > 0 && ba < 0) })())`,
      )
    }
  }

  // ── Set operations: union/intersect/difference → length/subset invariants ──
  // union(A,B).length >= max(A.length,B.length); intersect ⊆ both; diff ⊆ A.
  const setOps = feats.exports.filter(n =>
    /^(union|intersect|intersection|difference|subtract|complement|xor|symmetricDiff)/i.test(n)
  )
  if (!family && setOps.length >= 1) {
    family = 'set-op'
    const name = setOps[0]
    const isUnion = /union/i.test(name)
    const isInter = /intersect/i.test(name)
    // 2026-07-06: literal test data must match the REAL declared param type, not always
    // assume numbers. A set-op function whose spec declares `string[]` params (e.g.
    // `unionTags(a: string[], b: string[])`) had every numeric literal below fail tsc on
    // the generated test file ITSELF (`Type 'number' is not assignable to type 'string'`)
    // — an unwinnable oracle gate the candidate could never pass regardless of correctness.
    // Confirmed live: this is the exact root cause of the tagSetModule generation-stress
    // task going RED (identical-fingerprint tripwire on this one compile error, 3
    // consecutive rounds). Same audit discipline as agent/localHardenFuzz.ts's
    // paramsLookNonNumeric — sniff the spec's own signature and switch to string literals
    // when it's explicitly typed as strings; numeric/untyped stays numeric (unchanged).
    const paramsRaw = getSpecParamsRaw(feats.raw, name)
    const stringTyped = paramsRaw !== null && /:\s*string(\[\])?\b/.test(paramsRaw)
    // 1->'a', 2->'b', ... — preserves each literal's overlap relationships across the
    // numeric/string variants so the assertions' semantics (dedup, subset, etc.) are identical.
    const q = (n: number) => stringTyped ? `'${String.fromCharCode(96 + n)}'` : String(n)
    const arr = (...ns: number[]) => `[${ns.map(q).join(',')}]`
    assertions.push(
      `prop('${name} returns array', Array.isArray(${name}(${arr(1, 2, 3)},${arr(2, 3, 4)})))`,
      `prop('${name} empty+empty', ${name}([],[]).length === 0)`,
    )
    if (isUnion) {
      assertions.push(
        `prop('union A+empty = A', ${name}(${arr(1, 2, 3)},[]).length === 3)`,
        `prop('union A+A has no dupes', ${name}(${arr(1, 2)},${arr(1, 2)}).length <= 2)`,
        `prop('union A+B >= max(A,B)', ${name}(${arr(1, 2, 3)},${arr(4, 5)}).length >= 3)`,
      )
    } else if (isInter) {
      assertions.push(
        `prop('intersect A+empty = empty', ${name}(${arr(1, 2, 3)},[]).length === 0)`,
        `prop('intersect A+A = A', ${name}(${arr(1, 2)},${arr(1, 2)}).length <= 2)`,
        `prop('intersect subset of A', ${name}(${arr(1, 2, 3)},${arr(2, 3, 4)}).length <= 3)`,
      )
    } else {
      // difference / subtract
      assertions.push(
        `prop('diff A-empty = A', ${name}(${arr(1, 2, 3)},[]).length === 3)`,
        `prop('diff A-A = empty', ${name}(${arr(1, 2)},${arr(1, 2)}).length === 0)`,
      )
    }
  }

  // ── Number transform: clamp/lerp/normalize/mapRange → returns number, bounded ──
  // Weak but reliable: output is always a number. Bounds only asserted where name implies them.
  const numTransforms = feats.exports.filter(n =>
    /^(clamp|lerp|normalize|remap|mapRange|scale|lerpAngle|invLerp)/i.test(n)
  )
  if (!family && numTransforms.length >= 1) {
    family = 'number-transform'
    const name = numTransforms[0]
    assertions.push(
      `prop('${name} returns number', typeof ${name}(0.5, 0, 1) === 'number')`,
      `prop('${name} identity at midpoint', (() => { const r=${name}(5,0,10); return typeof r === 'number' })())`,
    )
    if (/clamp/i.test(name)) {
      assertions.push(
        `prop('clamp below min', ${name}(-5, 0, 10) === 0)`,
        `prop('clamp above max', ${name}(15, 0, 10) === 10)`,
        `prop('clamp mid passthrough', ${name}(5, 0, 10) === 5)`,
      )
    } else if (/lerp/i.test(name)) {
      assertions.push(
        `prop('lerp at 0', ${name}(0, 10, 0) === 0)`,
        `prop('lerp at 1', ${name}(0, 10, 1) === 10)`,
        `prop('lerp at 0.5', Math.abs(${name}(0, 10, 0.5) - 5) < 0.001)`,
      )
    } else if (/normalize/i.test(name)) {
      assertions.push(
        `prop('normalize at min', ${name}(0, 0, 10) === 0)`,
        `prop('normalize at max', ${name}(10, 0, 10) === 1)`,
      )
    }
  }

  // ── Deterministic / memoize: same input → same output (hash, checksum, memoize) ──
  // Tests only the determinism property (no side-effect). Does not assert correctness.
  const deterministicFns = feats.exports.filter(n =>
    /^(memoize|memoizeAsync|hash|checksum|crc|fnv|djb|murmurhash|md5|sha)/i.test(n)
  )
  if (!family && deterministicFns.length >= 1) {
    family = 'deterministic'
    const name = deterministicFns[0]
    const isMemoize = /memoize/i.test(name)
    if (isMemoize) {
      assertions.push(
        `prop('memoize returns function', typeof ${name}((x: number) => x * 2) === 'function')`,
        `prop('memoize same result', (() => { const f=${name}((x: number) => x*2); return f(3)===f(3) })())`,
        `prop('memoize caches value', (() => { let n=0; const f=${name}((x: number) => { n++; return x*2 }); f(4); f(4); return n===1 })())`,
      )
    } else {
      // hash / checksum / crc family
      assertions.push(
        `prop('${name} returns string or number', (() => { const r=${name}('hello'); return typeof r==='string'||typeof r==='number' })())`,
        `prop('${name} deterministic', ${name}('hello') === ${name}('hello'))`,
        `prop('${name} different inputs differ', ${name}('hello') !== ${name}('world'))`,
        `prop('${name} empty string', (() => { const r=${name}(''); return typeof r==='string'||typeof r==='number' })())`,
      )
    }
  }

  // ── Array predicate: every*/some*/all*/none* → correct boolean vacuous cases ──
  const arrPredicates = feats.exports.filter(n =>
    /^(every|some|none|all|any)[A-Z_]/.test(n)
  )
  if (!family && arrPredicates.length >= 1) {
    family = 'array-predicate'
    for (const name of arrPredicates.slice(0, 3)) {
      const isEvery = /^(every|all)/i.test(name)
      const isSome  = /^(some|any)/i.test(name)
      const isNone  = /^none/i.test(name)
      assertions.push(`prop('${name} returns boolean', typeof ${name}([]) === 'boolean')`)
      if (isEvery) assertions.push(`prop('${name} vacuous true on empty', ${name}([]) === true)`)
      if (isSome)  assertions.push(`prop('${name} vacuous false on empty', ${name}([]) === false)`)
      if (isNone)  assertions.push(`prop('${name} vacuous true on empty', ${name}([]) === true)`)
    }
  }

  // ── Parser roundtrip: parse/stringify (module-level, distinct from codec) ────
  // parse(stringify(val)) deep-equals val for primitive scalars.
  // Distinct from codec (which uses Encode/Decode): this targets format parsers
  // (JSON-like, TOML, INI, CSV…) where the round-trip identity must hold on primitives.
  const parsers    = feats.exports.filter(n => /^(parse|deserialize|decode|fromString|read)[A-Z_]?$/.test(n) || n === 'parse')
  const stringifiers = feats.exports.filter(n => /^(stringify|serialize|encode|toString|write)[A-Z_]?$/.test(n) || n === 'stringify')
  if (!family && parsers.length >= 1 && stringifiers.length >= 1 && !encoders.length) {
    family = 'parser-roundtrip'
    const p = parsers[0], s = stringifiers[0]
    assertions.push(
      `prop('roundtrip number',  (() => { const v=42;      const r=${p}(${s}(v)); return r===v || JSON.stringify(r)===JSON.stringify(v) })())`,
      `prop('roundtrip string',  (() => { const v='hello'; const r=${p}(${s}(v)); return r===v || JSON.stringify(r)===JSON.stringify(v) })())`,
      `prop('roundtrip null',    (() => { const v=null;    const r=${p}(${s}(v)); return r===v || JSON.stringify(r)===JSON.stringify(v) })())`,
      `prop('stringify returns string', typeof ${s}(42) === 'string')`,
    )
  }

  // ── Filter-with-opts: filter*(items, opts) where opts has active?: boolean ────────────
  // Detected by: (1) export named filter*, (2) spec mentions `active?: boolean`.
  // We generate inline test data (no project imports needed) so the test is self-contained
  // and works in the oracle scratch without access to the project's getData() functions.
  // Properties verified: empty opts returns all, active=true filter, active=false filter.
  const filterFns = feats.exports.filter(n => /^filter[A-Z]?/.test(n))
  const hasActiveBoolOpt = /active\s*\?:\s*boolean/.test(spec)
  if (!family && filterFns.length === 1 && hasActiveBoolOpt) {
    family = 'filter-opts'
    const fn = filterFns[0]
    // Detect a query string option (name or email search).
    const hasQueryOpt = /query\s*\?:\s*string/.test(spec) || /search\s*\?:\s*string/.test(spec)
    const queryField = hasQueryOpt ? (spec.match(/query|search/) ?? ['query'])[0] : null
    // Build inline test data: 3 items, one active/one inactive/one inactive with distinct name.
    // The data structure mirrors what the spec describes — active + name + email fields.
    const items = `[
    { id: 1, name: 'Alpha', email: 'alpha@x.com', active: true  },
    { id: 2, name: 'Beta',  email: 'beta@y.com',  active: false },
    { id: 3, name: 'Gamma', email: 'gamma@z.org', active: false },
  ]`
    assertions.push(
      `prop('empty opts returns all', (() => { const r = ${fn}(${items}, {}); return r.length === 3 })())`,
      `prop('active=true returns only active', (() => { const r = ${fn}(${items}, { active: true }); return r.length === 1 && r[0].active === true })())`,
      `prop('active=false returns only inactive', (() => { const r = ${fn}(${items}, { active: false }); return r.length === 2 && r.every((u: any) => u.active === false) })())`,
      `prop('does not mutate input', (() => { const data = [...(${items})]; ${fn}(data, { active: true }); return data.length === 3 })())`,
    )
    if (queryField) {
      assertions.push(
        `prop('${queryField} filter by name', (() => { const r = ${fn}(${items}, { ${queryField}: 'Alpha' }); return r.length === 1 })())`,
        `prop('${queryField} filter case-insensitive', (() => { const r = ${fn}(${items}, { ${queryField}: 'ALPHA' }); return r.length === 1 })())`,
        `prop('${queryField} no match returns empty', (() => { const r = ${fn}(${items}, { ${queryField}: 'zzznomatch' }); return r.length === 0 })())`,
        `prop('both filters compose', (() => { const r = ${fn}(${items}, { active: true, ${queryField}: 'Alpha' }); return r.length === 1 && r[0].active === true })())`,
      )
    }
  }

  // ── Class stateful: standalone class with primitive constructor args ─────────
  // Detects: PascalCase export, `constructor` in spec, no known framework deps.
  // Tests: constructor doesn't throw, instance is object, methods exist.
  // EXCLUDES framework-entangled classes (PrismaClient, Express, React, etc.)
  // because those types aren't available in the oracle scratch dir.
  const FRAMEWORK_TYPES = /\b(PrismaClient|Express|Request|Response|NextFunction|Router|ReactNode|JSX|Angular|Vue|Knex|Mongoose|Sequelize|TypeORM|Socket\.io|Fastify|Hapi|Koa)\b/
  // Same closed-world bug class as the 'sort' family's SortOpts fix above (found live
  // 2026-07-04 in the fm-rounds ledger): extractFeatures lists INTERFACE/TYPE exports too,
  // and this family then emitted `new AccountSummary(...)` for an interface — the generated
  // property test itself fails tsc, burning every FM round AND shadowing the (correct)
  // context-invariant family that runs at lower precedence. A name only counts as a class
  // here if the spec doesn't declare it as interface/type.
  const classExports = feats.exports.filter(n =>
    /^[A-Z]/.test(n) &&
    !new RegExp(`\\b(?:interface|type)\\s+${escapeRe(n)}\\b`).test(spec),
  )
  const hasConstructorInSpec = /\bconstructor\s*\(/.test(spec)
  const hasPrimitiveConstructorOnly = (() => {
    // Extract constructor signature, check that all param types are primitive or generic
    const m = spec.match(/constructor\s*\(([^)]*)\)/)
    if (!m) return true  // no constructor → default constructor, safe
    const params = m[1].trim()
    if (!params) return true  // no params → safe
    // Reject if any param type looks like a framework/external type
    return !FRAMEWORK_TYPES.test(params) && !/[A-Z][a-z]+[A-Z]/.test(params.replace(/\bstring\b|\bnumber\b|\bboolean\b|\bany\b|\bunknown\b|\bnever\b|\bvoid\b|\bnull\b/g, ''))
  })()
  const isFrameworkEntangled = FRAMEWORK_TYPES.test(spec)
  if (!family && classExports.length >= 1 && !isFrameworkEntangled && hasPrimitiveConstructorOnly) {
    // Only trigger when the spec describes the class API (has method-like lines)
    const hasMethodLines = /\b(?:get|set|push|pop|add|remove|delete|has|clear|size|peek|enqueue|dequeue|emit|on|off|run|start|stop|reset|parse|encode|decode|serialize|deserialize|keys|values|entries)\s*\(/.test(spec)
    if (hasMethodLines || hasConstructorInSpec) {
      family = 'class-stateful'
      const cls = classExports[0]
      // Derive constructor args from spec (primitive-only)
      const ctorMatch = spec.match(/constructor\s*\(([^)]*)\)/)
      const ctorParams = ctorMatch?.[1]?.trim() ?? ''
      // Build a safe default argument list from types
      const defaultArgs = ctorParams
        ? ctorParams.split(',').map(p => {
            const t = p.split(':').pop()?.trim().toLowerCase() ?? ''
            if (t.startsWith('number')) return '0'
            if (t.startsWith('string')) return "''"
            if (t.startsWith('boolean')) return 'false'
            return 'null'
          }).join(', ')
        : ''
      const ctorCall = `new ${cls}(${defaultArgs})`
      assertions.push(
        `prop('${cls} constructor does not throw', (() => { try { const i = ${ctorCall}; return i !== null && typeof i === 'object' } catch { return false } })())`,
        `prop('${cls} is object', typeof ${ctorCall} === 'object')`,
      )
      // Check each mentioned method exists on the instance. Scope the scan to the target
      // class's own `{ … }` body sketch — a bare /word(/ scan over the WHOLE spec grabs
      // filename references ("src/types.ts (defines…" → `ts`) and ordinary English words
      // before an open paren ("the API named below (" → `below`), inventing phantom methods
      // whose typed property access fails tsc (TS2339) and burns every FM round. If no class
      // body is found, extract no methods (constructor asserts only) rather than guess.
      const clsBody = spec.match(new RegExp(`\\bclass\\s+${escapeRe(cls)}\\b[^{]*\\{([\\s\\S]*?)\\n\\s*\\}`))?.[1] ?? ''
      const methodNames = Array.from(clsBody.matchAll(/\b([a-z][a-zA-Z0-9]*)\s*\(/g), m => m[1])
        .filter(n => !['new','if','for','while','return','typeof','instanceof','prop','try','catch'].includes(n))
        .slice(0, 5)
      for (const method of methodNames) {
        assertions.push(
          `prop('${cls}.${method} is function', (() => { try { const i = ${ctorCall}; return typeof i.${method} === 'function' } catch { return false } })())`
        )
      }
    }
  }

  if (!family || !assertions.length) return null

  const importedNames = feats.exports.join(', ')
  const content = `// Property-derived test (Phase-3 fallback — weaker than behavioral, stronger than shape-only).
// Family: ${family}. Generated by Crucible synth/derive.
import { ${importedNames} } from '${importPath}'
let failures = 0
function prop(name: string, ok: boolean) {
  console.log((ok ? 'PASS' : 'FAIL') + ' — ' + name)
  if (!ok) failures++
}
;(async () => {
${assertions.map(a => `try { ${a} } catch(e) { prop(${JSON.stringify(a.match(/prop\('([^']+)'/)?.[1] ?? 'test')}, false) }`).join('\n')}
console.log(failures === 0 ? 'ALL PASS' : failures + ' FAILURE(S)')
process.exit(failures === 0 ? 0 : 1)
})()`

  return {
    testFile: { path: '__property__/spec.test.ts', content },
    count: assertions.length,
    family,
  }
}
