// ============================================================================
// Skill generator — reads catalog.ts, idempotently writes:
//   skills/<filename>.ts          — the skill file (registerSkill)
//   skills/_suites/<filename>.hidden.ts — the adversarial suite
// Run: npm run generate:skills
// Then: npm run prove:all   (gates everything through Invariant 4)
// ============================================================================

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import CATALOG, { type CatalogEntry } from './catalogIndex'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const SKILLS_DIR = path.join(HERE, 'skills')
const SUITES_DIR = path.join(SKILLS_DIR, '_suites')

fs.mkdirSync(SUITES_DIR, { recursive: true })

function buildMatchBody(entry: CatalogEntry): string {
  return entry.patterns.map(p =>
    `  if (s.has(new RegExp(${JSON.stringify(p.re)}, 'i'))) sc += ${p.weight}`
  ).join('\n')
}

function buildSkillFile(entry: CatalogEntry): string {
  // JSON.stringify handles all escaping (backslashes, template interpolations, etc.)
  const implJson = JSON.stringify(`// Synthesized by Crucible — ${entry.summary}\n${entry.impl}\n`)
  return `// Generated by generate.ts from catalog.ts — edit catalog.ts, not this file.
import { registerSkill, type SpecFeatures, type SynthFile } from '../synthEngine'

const IMPL = ${implJson}

registerSkill({
  id: ${JSON.stringify(entry.id)},
  summary: ${JSON.stringify(entry.summary)},
  match(s: SpecFeatures): number {
    let sc = 0
${buildMatchBody(entry)}
    return sc
  },
  emit(s: SpecFeatures): SynthFile[] {
    return [{ path: s.modulePath ?? ${JSON.stringify(entry.defaultPath)}, content: IMPL }]
  },
})
`
}

function buildSuiteFile(entry: CatalogEntry): string {
  const stem = entry.defaultPath.replace(/^src\//, '').replace(/\.ts$/, '')
  const importLine = `import { ${entry.exports.join(', ')} } from '../src/${stem}'`

  const testBlocks = entry.tests.map(t =>
    `await check(${JSON.stringify(t.desc)}, ${t.call}, ${t.want})`
  ).join('\n')

  return `// Generated by generate.ts — hidden adversarial suite for ${entry.id}.
// Run via \`npx tsx __audit__/${entry.filename}.hidden.ts\` inside the scratch project.
${importLine}

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(\`  \${ok ? 'PASS' : 'FAIL'} — \${name}\`)
  if (!ok) {
    console.log(\`       got:  \${JSON.stringify(got)}\`)
    console.log(\`       want: \${JSON.stringify(want)}\`)
    failures++
  }
}

;(async () => {
${testBlocks}
console.log(failures === 0 ? 'ALL PASS' : \`\${failures} FAILURE(S)\`)
process.exit(failures === 0 ? 0 : 1)
})()
`
}

let written = 0, skipped = 0

for (const entry of CATALOG) {
  const skillPath = path.join(SKILLS_DIR, `${entry.filename}.ts`)
  const suitePath = path.join(SUITES_DIR, `${entry.filename}.hidden.ts`)

  const skillContent = buildSkillFile(entry)
  const suiteContent = buildSuiteFile(entry)

  // Idempotent: only write if content changed
  const writeIfChanged = (filePath: string, content: string) => {
    if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === content) {
      return false
    }
    fs.writeFileSync(filePath, content)
    return true
  }

  const sw = writeIfChanged(skillPath, skillContent)
  const ss = writeIfChanged(suitePath, suiteContent)
  if (sw || ss) {
    console.log(`  wrote  ${entry.filename}`)
    written++
  } else {
    skipped++
  }
}

console.log(`\ngenerate:skills — ${written} written, ${skipped} unchanged`)
console.log('Run `npm run prove:all` to validate and update _manifest.ts')
