// ============================================================================
// Where is this Crucible reachable from the outside?
//
// The pairing link is useless without a public hostname, and making the user set
// CRUCIBLE_PUBLIC_HOST by hand is a footgun: the one moment they need the link is
// the one moment they are not at the Mac to discover the variable exists. But the
// answer is already written down — cloudflared's own config declares which
// hostname it forwards to this port:
//
//   ingress:
//     - hostname: crucible.cam
//       service: http://localhost:3001
//     - service: http_status:404
//
// So read it. This is a tiny purpose-built reader, not a YAML parser: the file is
// machine-generated by `cloudflared tunnel route dns` in a fixed shape, and taking
// a YAML dependency to read two keys would be worse than the fifteen lines here.
//
// Resolution order, most explicit first:
//   1. CRUCIBLE_PUBLIC_HOST      — the user said so; never argue
//   2. the request's own x-forwarded-host — we ARE being reached publicly right now
//   3. cloudflared's ingress, matched to this server's port
//   4. null — the UI then shows the bare ?device= fragment and says why
// ============================================================================

/**
 * Extract the ingress hostname that forwards to `port` from a cloudflared config.
 *
 * Entries are matched as a pair: a `hostname:` line, then the `service:` line that
 * follows it. A catch-all entry (`- service: http_status:404`) has no hostname and
 * is correctly skipped, and a config routing several ports to several hostnames
 * yields the one that actually points at us rather than simply the first.
 */
export function ingressHostForPort(configText: string, port: number): string | null {
  const lines = configText.split('\n')
  let pendingHost: string | null = null
  for (const raw of lines) {
    const line = raw.trim()
    const hostMatch = /^-?\s*hostname:\s*["']?([^"'\s#]+)/.exec(line)
    if (hostMatch) { pendingHost = hostMatch[1]; continue }
    const svcMatch = /^-?\s*service:\s*["']?([^"'\s#]+)/.exec(line)
    if (svcMatch) {
      // A `service:` closes the current entry either way — a hostname is only ever
      // claimed by the service directly beneath it.
      const host = pendingHost
      pendingHost = null
      if (!host) continue
      const svc = svcMatch[1]
      // Only a real origin has a port. `http_status:404` is a cloudflared
      // DIRECTIVE, not a URL, and its trailing `:404` is a status code — reading it
      // as a port made the catch-all entry answer for port 404.
      if (!svc.includes('://')) continue
      const portMatch = /:(\d+)$/.exec(svc)
      if (portMatch && Number(portMatch[1]) === port) return host
    }
  }
  return null
}

/** Strip any scheme/trailing slash a user may have typed into CRUCIBLE_PUBLIC_HOST. */
export function normalizeHost(value: string): string {
  return value.trim().replace(/^https?:\/\//, '').replace(/\/+$/, '')
}

/**
 * Build the pairing URL. Returns null when no public host is known — the caller
 * must NOT invent one, because a link to the wrong origin is worse than no link:
 * it fails silently on the phone and looks like the token is broken.
 */
export function pairingUrl(host: string | null, token: string): string | null {
  if (!host) return null
  const clean = normalizeHost(host)
  if (!clean) return null
  // Always https: a pairing token is a bearer secret and must not cross the public
  // internet in the clear, and every tunnel that gives you a public hostname
  // terminates TLS anyway.
  return `https://${clean}/?device=${encodeURIComponent(token)}`
}
