#!/usr/bin/env node
/**
 * Write server/build.ts — the identity of the artefact about to be built.
 *
 * Runs before every build (see the `prebuild` script), so the client bundle and
 * the Worker are stamped from the SAME computation in the same pass and cannot
 * disagree about which code they are. That matters more than the value itself:
 * two independent stamps that drift are worse than no stamp, because they look
 * authoritative while lying.
 *
 * The hash covers exactly what ships — the same file set the deploy script
 * fingerprints — so "same tree" means "the deployed artefact would be
 * identical", not "the working copy felt unchanged".
 */
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

let tree = 'unknown'
try {
  tree = execSync(
    // server/build.ts is this file's own output. Including it would make the
    // hash depend on the previous build's timestamp, so every build would look
    // like a change — which would both break the deploy script's no-op check
    // and make the stamp meaningless as an identity.
    "find src server worker public index.html wrangler.jsonc package.json -type f" +
      " -not -path '*/node_modules/*' -not -path 'server/build.ts' -print0" +
      ' | LC_ALL=C sort -z | xargs -0 shasum | shasum',
    { cwd: root, encoding: 'utf8', shell: '/bin/bash' },
  )
    .trim()
    .slice(0, 12)
} catch {
  // A stamp we could not compute says 'unknown' rather than failing the build.
  // Losing the diagnostic is a smaller harm than losing the deploy.
}

writeFileSync(
  join(root, 'server', 'build.ts'),
  `// GENERATED by scripts/stamp.mjs at build time. Do not edit; do not commit meaning to it.
export const BUILD = ${JSON.stringify({ tree, at: new Date().toISOString() }, null, 2)} as const
`,
)

process.stdout.write(`stamped build ${tree}\n`)
