// Generated by generate.ts — hidden adversarial suite for base32-encode.
// Run via `npx tsx __audit__/base32Encode.hidden.ts` inside the scratch project.
import { base32Encode, base32Decode } from '../src/base32Encode'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("encode hello", base32Encode("hello"), "NBSWY3DP")
await check("length multiple of 8", base32Encode("hello").length % 8 === 0, true)
await check("roundtrip", base32Decode(base32Encode("Hello World")), "Hello World")
await check("empty", base32Encode(""), "")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
