// Generated by generate.ts — hidden adversarial suite for bellman-ford-distances.
// Run via `npx tsx __audit__/bellmanFordDistances.hidden.ts` inside the scratch project.
import { bellmanFordDistances } from '../src/bellmanFordDistances'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("positive edges", bellmanFordDistances(4,[[0,1,1],[1,2,2],[0,2,4]],0), [0,1,3,null])
await check("negative edge ok", bellmanFordDistances(3,[[0,1,4],[1,2,-2],[0,2,5]],0), [0,4,2])
await check("negative cycle", bellmanFordDistances(3,[[0,1,1],[1,2,-1],[2,1,-1]],0), null)
await check("unreachable", bellmanFordDistances(2,[],0), [0,null])
await check("single", bellmanFordDistances(1,[],0), [0])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
