// Generated by generate.ts — hidden adversarial suite for binary-search.
// Run via `npx tsx __audit__/binarySearch.hidden.ts` inside the scratch project.
import { binarySearch, lowerBound, upperBound } from '../src/binarySearch'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("found mid", binarySearch([1,3,5,7,9], 5), 2)
await check("found first", binarySearch([1,3,5,7,9], 1), 0)
await check("found last", binarySearch([1,3,5,7,9], 9), 4)
await check("not found", binarySearch([1,3,5,7,9], 4), -1)
await check("empty array", binarySearch([], 1), -1)
await check("lowerBound", lowerBound([1,2,2,3,4], 2), 1)
await check("upperBound", upperBound([1,2,2,3,4], 2), 3)
await check("single element found", binarySearch([42], 42), 0)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
