// Generated by generate.ts — hidden adversarial suite for bounding-box-2d.
// Run via `npx tsx __audit__/boundingBox.hidden.ts` inside the scratch project.
import { boundingBox } from '../src/boundingBox'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("three points", boundingBox([[1,2],[3,4],[-1,5]]), [-1,2,3,5])
await check("single point", boundingBox([[2,2]]), [2,2,2,2])
await check("empty input", boundingBox([]), [0,0,0,0])
await check("all negative", boundingBox([[-5,-5],[-1,-2],[-3,-9]]), [-5,-9,-1,-2])
await check("axis-aligned square", boundingBox([[0,0],[4,0],[4,4],[0,4]]), [0,0,4,4])
await check("mixed signs", boundingBox([[-2,3],[5,-4],[0,0]]), [-2,-4,5,3])
await check("two points", boundingBox([[10,1],[2,20]]), [2,1,10,20])
await check("duplicate points", boundingBox([[3,3],[3,3]]), [3,3,3,3])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
