// Generated by generate.ts — hidden adversarial suite for caesar-cipher.
// Run via `npx tsx __audit__/caesarCipher.hidden.ts` inside the scratch project.
import { caesarCipher } from '../src/caesarCipher'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("hello shift 3", caesarCipher("hello",3), "khoor")
await check("wrap", caesarCipher("xyz",3), "abc")
await check("uppercase", caesarCipher("ABC",1), "BCD")
await check("decode", caesarCipher("khoor",-3), "hello")
await check("preserve non-alpha", caesarCipher("hello, world!",13), "uryyb, jbeyq!")
await check("shift 0", caesarCipher("hello",0), "hello")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
