// Generated by generate.ts — hidden adversarial suite for color-utils.
// Run via `npx tsx __audit__/colorUtils.hidden.ts` inside the scratch project.
import { hexToRgb, rgbToHex, rgbToHsl, hslToRgb } from '../src/colorUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("hexToRgb white", JSON.stringify(hexToRgb("#ffffff")), "{\"r\":255,\"g\":255,\"b\":255}")
await check("hexToRgb black", JSON.stringify(hexToRgb("#000000")), "{\"r\":0,\"g\":0,\"b\":0}")
await check("hexToRgb red", JSON.stringify(hexToRgb("#ff0000")), "{\"r\":255,\"g\":0,\"b\":0}")
await check("hexToRgb invalid", hexToRgb("invalid"), null)
await check("rgbToHex black", rgbToHex({r:0,g:0,b:0}), "#000000")
await check("rgbToHex white", rgbToHex({r:255,g:255,b:255}), "#ffffff")
await check("roundtrip hex", rgbToHex(hexToRgb("#3a7bd5")!), "#3a7bd5")
await check("rgbToHsl black", JSON.stringify(rgbToHsl({r:0,g:0,b:0})), "{\"h\":0,\"s\":0,\"l\":0}")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
