// Generated by generate.ts — hidden adversarial suite for compact.
// Run via `npx tsx __audit__/compact.hidden.ts` inside the scratch project.
import { compact } from '../src/compact'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("removes all falsy", compact([0, 1, false, 2, "", 3, null, undefined]), [1,2,3])
await check("no falsy", compact([1,2,3]), [1,2,3])
await check("all falsy", compact([0, false, null, undefined, ""]), [])
await check("empty", compact([]), [])
await check("strings", compact(["","a","","b"]), ["a","b"])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
