// Generated by generate.ts — hidden adversarial suite for counter-frequency.
// Run via `npx tsx __audit__/counterFrequency.hidden.ts` inside the scratch project.
import { Counter } from '../src/counterFrequency'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("count", (() => { const c = new Counter<string>(); c.add("a"); c.add("a"); c.add("b"); return c.count("a") })(), 2)
await check("missing count", new Counter<string>().count("x"), 0)
await check("total", (() => { const c = new Counter<string>(); c.add("a"); c.add("b"); c.add("a"); return c.total() })(), 3)
await check("mostCommon top", (() => { const c = new Counter<string>(); ["a","a","a","b","b","c"].forEach(x=>c.add(x)); return c.mostCommon(1) })(), [["a",3]])
await check("mostCommon two", (() => { const c = new Counter<string>(); ["a","a","b","b","b","c"].forEach(x=>c.add(x)); return c.mostCommon(2) })(), [["b",3],["a",2]])
await check("empty mostCommon", new Counter<string>().mostCommon(3), [])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
