// Generated by generate.ts — hidden adversarial suite for count-by.
// Run via `npx tsx __audit__/countBy.hidden.ts` inside the scratch project.
import { countBy, frequencies } from '../src/countBy'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("countBy length", JSON.stringify(countBy(["a","bb","cc","ddd"], s=>s.length)), "{\"1\":1,\"2\":2,\"3\":1}")
await check("countBy parity", JSON.stringify(countBy([1,2,3,4,5,6], n=>n%2===0?"even":"odd")), "{\"odd\":3,\"even\":3}")
await check("countBy empty", JSON.stringify(countBy([], (x:any)=>x)), "{}")
await check("frequencies basic", frequencies([1,2,1,3,2,1]).get(1), 3)
await check("frequencies missing key", frequencies([1,2,3]).get(4), undefined)
await check("frequencies strings", frequencies(["a","b","a"]).get("a"), 2)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
