// Generated by generate.ts — hidden adversarial suite for crc32-checksum.
// Run via `npx tsx __audit__/crc32Checksum.hidden.ts` inside the scratch project.
import { crc32 } from '../src/crc32Checksum'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("hello", crc32("hello"), 907060870)
await check("empty", crc32(""), 0)
await check("deterministic", crc32("abc") === crc32("abc"), true)
await check("different inputs", crc32("a") !== crc32("b"), true)
await check("unsigned 32-bit", crc32("x") >= 0, true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
