// Generated by generate.ts — hidden adversarial suite for crypto-hash.
// Run via `npx tsx __audit__/cryptoHash.hidden.ts` inside the scratch project.
import { md5, sha1, sha256 } from '../src/cryptoHash'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("md5 hello", md5("hello"), "5d41402abc4b2a76b9719d911017c592")
await check("md5 empty", md5(""), "d41d8cd98f00b204e9800998ecf8427e")
await check("sha256 hello", sha256("hello"), "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824")
await check("sha256 empty", sha256(""), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
await check("sha1 hello", sha1("hello"), "aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d")
await check("deterministic", sha256("test") === sha256("test"), true)
await check("different inputs differ", sha256("a") !== sha256("b"), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
