// Generated by generate.ts — hidden adversarial suite for csv-parse.
// Run via `npx tsx __audit__/csvParse.hidden.ts` inside the scratch project.
import { parseCSV, stringifyCSV } from '../src/csvParse'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic parse", JSON.stringify(parseCSV("a,b,c\n1,2,3")), "[[\"a\",\"b\",\"c\"],[\"1\",\"2\",\"3\"]]")
await check("quoted comma field", parseCSV("name,\"John, Jr.\"")[0][1], "John, Jr.")
await check("quoted roundtrip", parseCSV(stringifyCSV([["a,b","c,d"]]))[0][1], "c,d")
await check("empty cells", JSON.stringify(parseCSV("a,,c")), "[[\"a\",\"\",\"c\"]]")
await check("stringify basic", stringifyCSV([["a","b"],["1","2"]]), "a,b\n1,2")
await check("stringify quotes comma", stringifyCSV([["a,b","c"]]), "\"a,b\",c")
await check("stringify round-trips quote", parseCSV(stringifyCSV([["say \"hi\""]]))[0][0], "say \"hi\"")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
