// Generated by generate.ts — hidden adversarial suite for debounce-throttle.
// Run via `npx tsx __audit__/debounceThrottle.hidden.ts` inside the scratch project.
import { debounce, throttle } from '../src/debounceThrottle'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("throttle allows first call", (() => { let n=0; const t=throttle(()=>n++,100); t(); return n })(), 1)
await check("throttle blocks second call", (() => { let n=0; const now=()=>0; const t=throttle(()=>n++,100,now); t(); t(); return n })(), 1)
await check("throttle allows after wait", (() => { let n=0; let time=0; const t=throttle(()=>n++,100,()=>time); t(); time=100; t(); return n })(), 2)
await check("debounce returns cancel/flush", (() => { const d=debounce(()=>{},50); return typeof d.cancel === "function" && typeof d.flush === "function" })(), true)
await check("throttle cancel resets", (() => { let n=0; const now=()=>0; const t=throttle(()=>n++,100,now); t(); t.cancel(); t(); return n })(), 2)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
