// Generated by generate.ts — hidden adversarial suite for deep-merge.
// Run via `npx tsx __audit__/deepMerge.hidden.ts` inside the scratch project.
import { deepMerge } from '../src/deepMerge'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic merge", JSON.stringify(deepMerge({a:1,b:2},{b:3,c:4})), "{\"a\":1,\"b\":3,\"c\":4}")
await check("deep nested", JSON.stringify(deepMerge({a:{x:1,y:2}},{a:{y:3,z:4}})), "{\"a\":{\"x\":1,\"y\":3,\"z\":4}}")
await check("does not mutate target", (() => { const t={a:1}; deepMerge(t,{b:2}); return t })(), {"a":1})
await check("array replaced not merged", JSON.stringify(deepMerge({a:[1,2]},{a:[3]})), "{\"a\":[3]}")
await check("multiple sources", JSON.stringify(deepMerge({a:1},{b:2},{c:3})), "{\"a\":1,\"b\":2,\"c\":3}")
await check("empty source", JSON.stringify(deepMerge({a:1},{})), "{\"a\":1}")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
