// Generated by generate.ts — hidden adversarial suite for dotenv-parse.
// Run via `npx tsx __audit__/dotenvParse.hidden.ts` inside the scratch project.
import { parseDotenv, stringifyDotenv } from '../src/dotenvParse'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parse basic", parseDotenv("KEY=value")["KEY"], "value")
await check("parse quoted double", parseDotenv('KEY="hello world"')["KEY"], "hello world")
await check("parse quoted single", parseDotenv("KEY='hello'")["KEY"], "hello")
await check("skip comments", Object.keys(parseDotenv("# comment\nK=v")).length, 1)
await check("multiple keys", parseDotenv("A=1\nB=2")["B"], "2")
await check("stringify basic", stringifyDotenv({FOO:"bar"}), "FOO=bar")
await check("stringify with spaces quotes", stringifyDotenv({A:"hello world"}).startsWith("A=\""), true)
await check("roundtrip", parseDotenv(stringifyDotenv({K:"v",X:"y"}))["X"], "y")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
