// Generated by generate.ts — hidden adversarial suite for edit-distance-lev.
// Run via `npx tsx __audit__/editDistanceLev.hidden.ts` inside the scratch project.
import { editDistanceLev } from '../src/editDistanceLev'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("kitten/sitting", editDistanceLev("kitten","sitting"), 3)
await check("empty to abc", editDistanceLev("","abc"), 3)
await check("identical", editDistanceLev("abc","abc"), 0)
await check("flaw/lawn", editDistanceLev("flaw","lawn"), 2)
await check("single sub", editDistanceLev("a","b"), 1)
await check("both empty", editDistanceLev("",""), 0)
await check("insertion", editDistanceLev("ac","abc"), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
