// Generated by generate.ts — hidden adversarial suite for exponential-moving-average.
// Run via `npx tsx __audit__/exponentialMovingAvg.hidden.ts` inside the scratch project.
import { exponentialMovingAverage } from '../src/exponentialMovingAvg'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("empty array returns empty", exponentialMovingAverage([], 0.5), [])
await check("single element seeds itself", exponentialMovingAverage([7], 0.3), [7])
await check("alpha one tracks input exactly", exponentialMovingAverage([5,10,15], 1), [5,10,15])
await check("alpha zero holds the seed", exponentialMovingAverage([5,10,15], 0), [5,5,5])
await check("half smoothing", exponentialMovingAverage([1,2,3,4], 0.5), [1,1.5,2.25,3.125])
await check("first element always equals seed", exponentialMovingAverage([9,1,1], 0.7)[0], 9)
await check("length matches input", exponentialMovingAverage([1,2,3,4,5], 0.2).length, 5)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
