// Generated by generate.ts — hidden adversarial suite for fn-utils.
// Run via `npx tsx __audit__/fnUtils.hidden.ts` inside the scratch project.
import { once, compose, pipe } from '../src/fnUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("once calls fn once", (() => { let n=0; const f = once(()=>++n); f();f();f(); return n })(), 1)
await check("once returns same value", (() => { let n=0; const f = once(()=>++n); return [f(),f(),f()] })(), [1,1,1])
await check("compose right to left", compose((x:number)=>x*2,(x:number)=>x+1)(3), 8)
await check("compose single", compose((x:number)=>x*2)(5), 10)
await check("compose empty", compose<number>()(5), 5)
await check("pipe left to right", pipe((x:number)=>x+1,(x:number)=>x*2)(3), 8)
await check("pipe single", pipe((x:number)=>x*3)(4), 12)
await check("pipe three fns", pipe((x:number)=>x+1,(x:number)=>x*2,(x:number)=>x-1)(0), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
