// Generated by generate.ts — hidden adversarial suite for format-currency.
// Run via `npx tsx __audit__/formatCurrency.hidden.ts` inside the scratch project.
import { formatCurrency } from '../src/formatCurrency'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", formatCurrency(1234.50,"$"), "$1,234.50")
await check("negative", formatCurrency(-1234.50,"$"), "-$1,234.50")
await check("zero", formatCurrency(0,"€"), "€0.00")
await check("millions", formatCurrency(1000000,"£"), "£1,000,000.00")
await check("small", formatCurrency(9.99,"$"), "$9.99")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
