// Generated by generate.ts — hidden adversarial suite for format-number.
// Run via `npx tsx __audit__/formatNumber.hidden.ts` inside the scratch project.
import { formatNumber } from '../src/formatNumber'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic thousands", formatNumber(1000), "1,000")
await check("millions", formatNumber(1000000), "1,000,000")
await check("with decimals", formatNumber(1234.5678, 2), "1,234.57")
await check("zero", formatNumber(0), "0")
await check("small number", formatNumber(42), "42")
await check("negative", formatNumber(-1234567), "-1,234,567")
await check("custom sep", formatNumber(1234567, 2, ",", "."), "1.234.567,00")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
