// Generated by generate.ts — hidden adversarial suite for format-duration.
// Run via `npx tsx __audit__/formatDuration.hidden.ts` inside the scratch project.
import { formatDuration } from '../src/formatDuration'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("zero", formatDuration(0), "0s")
await check("90 min", formatDuration(5400000), "1h 30m")
await check("45 sec", formatDuration(45000), "45s")
await check("2 days 3 hours", formatDuration(2*86400000+3*3600000), "2d 3h")
await check("exact hour", formatDuration(3600000), "1h")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
