// Generated by generate.ts — hidden adversarial suite for fp-utils.
// Run via `npx tsx __audit__/fpUtils.hidden.ts` inside the scratch project.
import { curry, partial, identity, constant, noop, flip } from '../src/fpUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("curry two args", (curry((a:number,b:number)=>a+b) as any)(1)(2), 3)
await check("curry all at once", (curry((a:number,b:number)=>a+b) as any)(1,2), 3)
await check("partial first arg", partial((a:number,b:number)=>a+b, 10)(5), 15)
await check("identity", identity(42), 42)
await check("constant", constant(42)(), 42)
await check("noop returns undefined", noop(), undefined)
await check("flip args", flip((a:string,b:string)=>a+b)("world","hello"), "helloworld")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
