// Generated by generate.ts — hidden adversarial suite for has-cycle-undirected.
// Run via `npx tsx __audit__/hasCycleUndirected.hidden.ts` inside the scratch project.
import { hasCycleUndirected } from '../src/hasCycleUndirected'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("triangle", hasCycleUndirected(3,[[0,1],[1,2],[2,0]]), true)
await check("tree", hasCycleUndirected(3,[[0,1],[1,2]]), false)
await check("forest", hasCycleUndirected(4,[[0,1],[2,3]]), false)
await check("single", hasCycleUndirected(1,[]), false)
await check("self loop", hasCycleUndirected(2,[[0,0]]), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
