// Generated by generate.ts — hidden adversarial suite for hash-utils.
// Run via `npx tsx __audit__/hashUtils.hidden.ts` inside the scratch project.
import { djb2Hash, simpleChecksum } from '../src/hashUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("djb2 hello is number", typeof djb2Hash("hello") === "number", true)
await check("djb2 empty", djb2Hash(""), 5381)
await check("djb2 deterministic", djb2Hash("test") === djb2Hash("test"), true)
await check("djb2 different strings differ", djb2Hash("abc") !== djb2Hash("xyz"), true)
await check("checksum empty", simpleChecksum(""), 0)
await check("checksum deterministic", simpleChecksum("hello") === simpleChecksum("hello"), true)
await check("checksum in range", simpleChecksum("hello world") <= 0xffff, true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
