// Generated by generate.ts — hidden adversarial suite for ini-parse.
// Run via `npx tsx __audit__/iniParse.hidden.ts` inside the scratch project.
import { parseINI, stringifyINI } from '../src/iniParse'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parse global key", parseINI("key=value")["key"], "value")
await check("parse section", (parseINI("[db]\nhost=localhost") ["db"] as any)["host"], "localhost")
await check("skip comments", Object.keys(parseINI("; comment\nkey=val")).length, 1)
await check("parse empty", JSON.stringify(parseINI("")), "{}")
await check("stringify global", stringifyINI({key:"val"}), "key=val")
await check("stringify section", stringifyINI({db:{host:"localhost"}}), "[db]\nhost=localhost")
await check("roundtrip", (parseINI(stringifyINI({a:"1",s:{x:"2"}})) as any)["s"]["x"], "2")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
