// Generated by generate.ts — hidden adversarial suite for integer-sqrt.
// Run via `npx tsx __audit__/integerSqrt.hidden.ts` inside the scratch project.
import { integerSqrt } from '../src/integerSqrt'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("sqrt of zero", integerSqrt(0), 0)
await check("sqrt of one", integerSqrt(1), 1)
await check("floors non perfect square", integerSqrt(15), 3)
await check("perfect square 16", integerSqrt(16), 4)
await check("just below next square", integerSqrt(24), 4)
await check("large perfect square", integerSqrt(1000000), 1000)
await check("large non-square exact", integerSqrt(999999999999), 999999)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
