// Generated by generate.ts — hidden adversarial suite for invert.
// Run via `npx tsx __audit__/invert.hidden.ts` inside the scratch project.
import { invert } from '../src/invert'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", invert({a:"1",b:"2",c:"3"}), {"1":"a","2":"b","3":"c"})
await check("empty", invert({}), {})
await check("single", invert({x:"y"}), {"y":"x"})
await check("roundtrip", JSON.stringify(invert(invert({a:"1",b:"2"}))), JSON.stringify({a:"1",b:"2"}))
await check("duplicate value last wins", Object.keys(invert({a:"x",b:"x"})).length, 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
