// Generated by generate.ts — hidden adversarial suite for is-credit-card-type.
// Run via `npx tsx __audit__/isCreditCardType.hidden.ts` inside the scratch project.
import { isCreditCardType } from '../src/isCreditCardType'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("Visa 16-digit with spaces", isCreditCardType("4111 1111 1111 1111"), "visa")
await check("Visa 13-digit", isCreditCardType("4222222222222"), "visa")
await check("Amex 15-digit", isCreditCardType("3782 822463 10005"), "amex")
await check("Mastercard 55 prefix", isCreditCardType("5555555555554444"), "mastercard")
await check("Mastercard 2221 new range", isCreditCardType("2221000000000009"), "mastercard")
await check("Discover 6011 prefix", isCreditCardType("6011111111111117"), "discover")
await check("Discover 65 prefix", isCreditCardType("6500000000000002"), "discover")
await check("unrecognized number", isCreditCardType("1234567812345678"), "unknown")
await check("empty string unknown", isCreditCardType(""), "unknown")
await check("non-digit unknown", isCreditCardType("4111a"), "unknown")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
