// Generated by generate.ts — hidden adversarial suite for is-ean13.
// Run via `npx tsx __audit__/isEAN13.hidden.ts` inside the scratch project.
import { isEAN13 } from '../src/isEAN13'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("valid EAN-13 barcode", isEAN13("4006381333931"), true)
await check("another valid EAN-13", isEAN13("5901234123457"), true)
await check("invalid check digit", isEAN13("4006381333930"), false)
await check("empty string invalid", isEAN13(""), false)
await check("all zeros has check digit zero", isEAN13("0000000000000"), true)
await check("valid EAN-13 with spaces", isEAN13("4006 381 333931"), true)
await check("too short rejected", isEAN13("400638133393"), false)
await check("non-digit rejected", isEAN13("400638133393X"), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
