// Generated by generate.ts — hidden adversarial suite for knapsack-01.
// Run via `npx tsx __audit__/knapsack01.hidden.ts` inside the scratch project.
import { knapsack01 } from '../src/knapsack01'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic", knapsack01([1,3,4,5],[1,4,5,7],7), 9)
await check("zero capacity", knapsack01([1,2,3],[10,20,30],0), 0)
await check("empty items", knapsack01([],[],10), 0)
await check("all fit", knapsack01([1,2,3],[6,10,12],6), 28)
await check("none fit", knapsack01([5,6],[10,20],4), 0)
await check("single fits", knapsack01([4],[100],4), 100)
await check("choose better", knapsack01([2,3],[3,4],5), 7)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
