// Generated by generate.ts — hidden adversarial suite for longest-increasing-subsequence.
// Run via `npx tsx __audit__/longestIncreasingSubsequence.hidden.ts` inside the scratch project.
import { longestIncreasingSubsequence } from '../src/longestIncreasingSubsequence'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic", longestIncreasingSubsequence([10,9,2,5,3,7,101,18]), 4)
await check("empty", longestIncreasingSubsequence([]), 0)
await check("increasing", longestIncreasingSubsequence([1,2,3]), 3)
await check("decreasing", longestIncreasingSubsequence([3,2,1]), 1)
await check("single", longestIncreasingSubsequence([5]), 1)
await check("with dip", longestIncreasingSubsequence([1,3,2,4]), 3)
await check("all equal strict", longestIncreasingSubsequence([7,7,7]), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
