// Generated by generate.ts — hidden adversarial suite for longest-common-subsequence.
// Run via `npx tsx __audit__/longestCommonSubsequence.hidden.ts` inside the scratch project.
import { longestCommonSubsequence } from '../src/longestCommonSubsequence'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic ABCBDAB/BDCAB", longestCommonSubsequence("ABCBDAB","BDCAB"), 4)
await check("AGGTAB/GXTXAYB", longestCommonSubsequence("AGGTAB","GXTXAYB"), 4)
await check("identical", longestCommonSubsequence("abc","abc"), 3)
await check("disjoint", longestCommonSubsequence("abc","def"), 0)
await check("empty", longestCommonSubsequence("","xyz"), 0)
await check("single match", longestCommonSubsequence("a","a"), 1)
await check("abcde/ace", longestCommonSubsequence("abcde","ace"), 3)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
