// Generated by generate.ts — hidden adversarial suite for manhattan-distance-l1.
// Run via `npx tsx __audit__/manhattanDistance.hidden.ts` inside the scratch project.
import { manhattanDistance } from '../src/manhattanDistance'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", manhattanDistance(0,0,3,4), 7)
await check("same point zero", manhattanDistance(2,2,2,2), 0)
await check("negative coords", manhattanDistance(-2,-3,1,1), 7)
await check("horizontal only", manhattanDistance(1,5,6,5), 5)
await check("vertical only", manhattanDistance(3,-1,3,4), 5)
await check("symmetric", manhattanDistance(5,5,1,2), 7)
await check("all negative", manhattanDistance(-5,-5,-1,-2), 7)
await check("unit step", manhattanDistance(0,0,0,1), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
