// Generated by generate.ts — hidden adversarial suite for math-stats.
// Run via `npx tsx __audit__/mathStats.hidden.ts` inside the scratch project.
import { sum, average, median, mode } from '../src/mathStats'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("sum basic", sum([1,2,3,4,5]), 15)
await check("sum empty", sum([]), 0)
await check("sum negatives", sum([-1,-2,3]), 0)
await check("average basic", average([1,2,3,4,5]), 3)
await check("average empty", Number.isNaN(average([])), true)
await check("average float", average([1,2]), 1.5)
await check("median odd", median([3,1,2]), 2)
await check("median even", median([1,2,3,4]), 2.5)
await check("median unsorted", median([5,1,3]), 3)
await check("mode single", mode([1,2,2,3]), [2])
await check("mode multi", mode([1,1,2,2,3]), [1,2])
await check("mode all same", mode([3,3,3]), [3])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
