// Generated by generate.ts — hidden adversarial suite for matrix-multiply.
// Run via `npx tsx __audit__/matrixMultiply.hidden.ts` inside the scratch project.
import { matrixMultiply } from '../src/matrixMultiply'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("2x2", matrixMultiply([[1,2],[3,4]],[[5,6],[7,8]]), [[19,22],[43,50]])
await check("identity", matrixMultiply([[1,2],[3,4]],[[1,0],[0,1]]), [[1,2],[3,4]])
await check("row by col", matrixMultiply([[1,2]],[[3],[4]]), [[11]])
await check("rectangular", matrixMultiply([[1,2,3]],[[1],[1],[1]]), [[6]])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
