// Generated by generate.ts — hidden adversarial suite for measure-time.
// Run via `npx tsx __audit__/measureTime.hidden.ts` inside the scratch project.
import { measureTime, measureTimeAsync } from '../src/measureTime'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("returns result", measureTime(() => 42).result, 42)
await check("ms is number", typeof measureTime(() => {}).ms === "number", true)
await check("ms >= 0", measureTime(() => {}).ms >= 0, true)
await check("async returns result", measureTimeAsync(async () => 99).then(r => r.result), 99)
await check("async ms is number", measureTimeAsync(async () => {}).then(r => typeof r.ms === "number"), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
