// Generated by generate.ts — hidden adversarial suite for min-heap.
// Run via `npx tsx __audit__/minHeap.hidden.ts` inside the scratch project.
import { MinHeap } from '../src/minHeap'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("extract min priority", (() => { const h = new MinHeap<string>(); h.insert("a",3); h.insert("b",1); h.insert("c",2); return h.extractMin()?.value })(), "b")
await check("peek does not remove", (() => { const h = new MinHeap<string>(); h.insert("x",1); h.peek(); return h.size() })(), 1)
await check("extract order", (() => { const h = new MinHeap<number>(); [3,1,4,1,5].forEach(n=>h.insert(n,n)); return [h.extractMin()?.priority,h.extractMin()?.priority] })(), [1,1])
await check("isEmpty true", new MinHeap().isEmpty(), true)
await check("isEmpty false after insert", (() => { const h = new MinHeap<number>(); h.insert(1,1); return h.isEmpty() })(), false)
await check("extract empty", new MinHeap().extractMin(), null)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
