// Generated by generate.ts — hidden adversarial suite for mod-inverse.
// Run via `npx tsx __audit__/modInverse.hidden.ts` inside the scratch project.
import { modInverse } from '../src/modInverse'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("inverse of 3 mod 11", modInverse(3,11), 4)
await check("inverse of 10 mod 17", modInverse(10,17), 12)
await check("no inverse when not coprime", modInverse(2,4), null)
await check("mod one inverse is zero", modInverse(7,1), 0)
await check("negative a normalized", modInverse(-8,17), 2)
await check("a multiple of m has no inverse", modInverse(6,3), null)
await check("product check is one", (() => { const inv = modInverse(3,11); return inv === null ? null : (3*inv) % 11 })(), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
