// Generated by generate.ts — hidden adversarial suite for mod-pow.
// Run via `npx tsx __audit__/modPow.hidden.ts` inside the scratch project.
import { modPow } from '../src/modPow'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic 2^10 mod 1000", modPow(2,10,1000), 24)
await check("exponent zero is one", modPow(3,0,7), 1)
await check("mod one collapses to zero", modPow(2,5,1), 0)
await check("reduces base larger than mod", modPow(7,256,13), 9)
await check("large exponent under 1e9+7", modPow(10,9,1000000007), 1000000000)
await check("base zero", modPow(0,5,13), 0)
await check("one to any power", modPow(1,1000000,99), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
