// Generated by generate.ts — hidden adversarial suite for next-power-of-two.
// Run via `npx tsx __audit__/nextPowerOfTwo.hidden.ts` inside the scratch project.
import { nextPowerOfTwo } from '../src/nextPowerOfTwo'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("five", nextPowerOfTwo(5), 8)
await check("exact", nextPowerOfTwo(16), 16)
await check("just over", nextPowerOfTwo(17), 32)
await check("zero", nextPowerOfTwo(0), 1)
await check("one", nextPowerOfTwo(1), 1)
await check("large", nextPowerOfTwo(1023), 1024)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
