// Generated by generate.ts — hidden adversarial suite for object-path.
// Run via `npx tsx __audit__/objectPath.hidden.ts` inside the scratch project.
import { getPath, setPath, hasPath, unsetPath } from '../src/objectPath'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("getPath simple", getPath({a:{b:1}}, "a.b"), 1)
await check("getPath deep", getPath({a:{b:{c:42}}}, "a.b.c"), 42)
await check("getPath missing default", getPath({}, "a.b", "default"), "default")
await check("getPath missing undefined", getPath({a:1}, "b"), undefined)
await check("getPath array index", getPath({a:[1,2,3]}, "a[1]"), 2)
await check("setPath simple", (() => { const o = {}; setPath(o,"a.b",42); return (o as any).a.b })(), 42)
await check("setPath creates nested", (() => { const o: any = {}; setPath(o,"x.y.z","v"); return o.x.y.z })(), "v")
await check("hasPath true", hasPath({a:{b:1}}, "a.b"), true)
await check("hasPath false", hasPath({a:1}, "a.b"), false)
await check("hasPath null value", hasPath({a:null}, "a"), true)
await check("unsetPath removes", (() => { const o: any = {a:{b:1,c:2}}; unsetPath(o,"a.b"); return o.a })(), {"c":2})
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
