// Generated by generate.ts — hidden adversarial suite for option-monad.
// Run via `npx tsx __audit__/optionMonad.hidden.ts` inside the scratch project.
import { Option } from '../src/optionMonad'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("some getOrElse", Option.some(5).getOrElse(0), 5)
await check("none getOrElse", Option.none<number>().getOrElse(0), 0)
await check("map some", Option.some(3).map(x=>x*2).getOrElse(0), 6)
await check("map none", Option.none<number>().map(x=>x*2).getOrElse(-1), -1)
await check("isSome", Option.some(1).isSome(), true)
await check("isNone", Option.none().isNone(), true)
await check("chained map", Option.some(2).map(x=>x+1).map(x=>x*10).getOrElse(0), 30)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
