// Generated by generate.ts — hidden adversarial suite for ordered-set.
// Run via `npx tsx __audit__/orderedSet.hidden.ts` inside the scratch project.
import { OrderedSet } from '../src/orderedSet'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("unique values", (() => { const s = new OrderedSet<number>(); [1,2,1,3,2].forEach(x=>s.add(x)); return s.values() })(), [1,2,3])
await check("has", (() => { const s = new OrderedSet<number>(); s.add(5); return s.has(5) })(), true)
await check("delete", (() => { const s = new OrderedSet<number>(); s.add(1); s.delete(1); return s.has(1) })(), false)
await check("size", (() => { const s = new OrderedSet<number>(); s.add(1); s.add(2); s.add(1); return s.size() })(), 2)
await check("insertion order kept", (() => { const s = new OrderedSet<string>(); ["c","a","b"].forEach(x=>s.add(x)); return s.values() })(), ["c","a","b"])
await check("delete missing", new OrderedSet<number>().delete(9), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
