// Generated by generate.ts — hidden adversarial suite for ordinal-word.
// Run via `npx tsx __audit__/ordinalWord.hidden.ts` inside the scratch project.
import { ordinalWord } from '../src/ordinalWord'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("one", ordinalWord(1), "first")
await check("five", ordinalWord(5), "fifth")
await check("ten", ordinalWord(10), "tenth")
await check("11th", ordinalWord(11), "11th")
await check("21st", ordinalWord(21), "21st")
await check("22nd", ordinalWord(22), "22nd")
await check("23rd", ordinalWord(23), "23rd")
await check("112th", ordinalWord(112), "112th")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
