// Generated by generate.ts — hidden adversarial suite for pad-columns.
// Run via `npx tsx __audit__/padColumns.hidden.ts` inside the scratch project.
import { padColumns } from '../src/padColumns'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("single row", padColumns([["a","bb","ccc"]]), ["a bb ccc"])
await check("aligns cols", padColumns([["a","bb"],["aaa","b"]]), ["a   bb","aaa b"])
await check("empty", padColumns([]), [])
await check("one col", padColumns([["hi"],["hello"]]), ["hi","hello"])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
