// Generated by generate.ts — hidden adversarial suite for parse-accept-header.
// Run via `npx tsx __audit__/parseAcceptHeader.hidden.ts` inside the scratch project.
import { parseAcceptHeader } from '../src/parseAcceptHeader'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("simple", parseAcceptHeader("text/html"), ["text/html"])
await check("by q-value", parseAcceptHeader("text/html;q=0.9,application/json"), ["application/json","text/html"])
await check("count", parseAcceptHeader("*/*;q=0.1,text/html;q=0.9,application/json").length, 3)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
