// Generated by generate.ts — hidden adversarial suite for parse-query-params.
// Run via `npx tsx __audit__/parseQueryParams.hidden.ts` inside the scratch project.
import { parseQueryParams } from '../src/parseQueryParams'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic", parseQueryParams("a=1&b=2"), {"a":"1","b":"2"})
await check("with ?", parseQueryParams("?x=hello"), {"x":"hello"})
await check("encoded", parseQueryParams("q=hello%20world"), {"q":"hello world"})
await check("empty", parseQueryParams(""), {})
await check("last wins", parseQueryParams("a=1&a=2"), {"a":"2"})
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
