// Generated by generate.ts — hidden adversarial suite for parse-iso-duration.
// Run via `npx tsx __audit__/parseIsoDuration.hidden.ts` inside the scratch project.
import { parseIsoDuration } from '../src/parseIsoDuration'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("one hour", parseIsoDuration("PT1H"), 3600000)
await check("90 min", parseIsoDuration("PT1H30M"), 5400000)
await check("1 day", parseIsoDuration("P1D"), 86400000)
await check("1 day 2 hours", parseIsoDuration("P1DT2H"), 93600000)
await check("30 seconds", parseIsoDuration("PT30S"), 30000)
await check("invalid", Number.isNaN(parseIsoDuration("notaduration")), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
