// Generated by generate.ts — hidden adversarial suite for parse-range-spec.
// Run via `npx tsx __audit__/parseRangeSpec.hidden.ts` inside the scratch project.
import { parseRangeSpec } from '../src/parseRangeSpec'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic range", parseRangeSpec("1-3"), [1,2,3])
await check("mixed", parseRangeSpec("1-3,5,7-8"), [1,2,3,5,7,8])
await check("single", parseRangeSpec("5"), [5])
await check("dedup overlap", parseRangeSpec("1-3,2-4"), [1,2,3,4])
await check("empty", parseRangeSpec(""), [])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
