// Generated by generate.ts — hidden adversarial suite for parse-number.
// Run via `npx tsx __audit__/parseNumber.hidden.ts` inside the scratch project.
import { safeParseInt, safeParseFloat, toFixed, inRange } from '../src/parseNumber'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("safeParseInt valid", safeParseInt("42"), 42)
await check("safeParseInt invalid", safeParseInt("abc"), 0)
await check("safeParseInt fallback", safeParseInt("x", 99), 99)
await check("safeParseInt hex", safeParseInt("ff", 0, 16), 255)
await check("safeParseFloat valid", safeParseFloat("3.14"), 3.14)
await check("safeParseFloat invalid", safeParseFloat("abc"), 0)
await check("toFixed rounds", toFixed(3.14159, 2), 3.14)
await check("toFixed returns number", typeof toFixed(1.5, 0) === "number", true)
await check("inRange in", inRange(5, 1, 10), true)
await check("inRange out", inRange(15, 1, 10), false)
await check("inRange exclusive", inRange(10, 1, 10, false), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
