// Generated by generate.ts — hidden adversarial suite for pearson-correlation-coeff.
// Run via `npx tsx __audit__/pearsonCorrelationCoeff.hidden.ts` inside the scratch project.
import { pearsonCorrelation } from '../src/pearsonCorrelationCoeff'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("perfect positive correlation", pearsonCorrelation([1,2,3],[2,4,6]), 1)
await check("perfect negative correlation", pearsonCorrelation([1,2,3],[6,4,2]), -1)
await check("constant y gives zero", pearsonCorrelation([1,2,3],[5,5,5]), 0)
await check("identical arrays correlate fully", pearsonCorrelation([3,1,4,1,5],[3,1,4,1,5]), 1)
await check("partial correlation value", pearsonCorrelation([1,2,3,4,5],[2,4,5,4,5]), 0.7745966692414834)
await check("scaled positive still one", pearsonCorrelation([0,10,20],[0,5,10]), 1)
await check("offset preserves correlation", pearsonCorrelation([1,2,3,4],[101,102,103,104]), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
