// Generated by generate.ts — hidden adversarial suite for percent.
// Run via `npx tsx __audit__/percent.hidden.ts` inside the scratch project.
import { percent, percentChange, percentOf } from '../src/percent'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("percent basic", percent(25, 100), 25)
await check("percent zero total", percent(5, 0), 0)
await check("percent half", percent(1, 2), 50)
await check("percentChange increase", percentChange(100, 150), 50)
await check("percentChange decrease", percentChange(200, 100), -50)
await check("percentChange no change", percentChange(100, 100), 0)
await check("percentOf basic", percentOf(25, 200), 50)
await check("percentOf zero", percentOf(0, 100), 0)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
