// Generated by generate.ts — hidden adversarial suite for pipeline.
// Run via `npx tsx __audit__/pipeline.hidden.ts` inside the scratch project.
import { Pipeline } from '../src/pipeline'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("of and unwrap", Pipeline.of(42).unwrap(), 42)
await check("map transforms", Pipeline.of(5).map(x=>x*2).unwrap(), 10)
await check("chain maps", Pipeline.of("hello").map(s=>s.toUpperCase()).map(s=>s+"!").unwrap(), "HELLO!")
await check("tap does not change", (()=>{let side=0;const v=Pipeline.of(42).tap(x=>{side=x}).unwrap();return [v,side]})(), [42,42])
await check("filter passes", Pipeline.of(5).filter(x=>x>0,0).unwrap(), 5)
await check("filter falls back", Pipeline.of(-1).filter(x=>x>0,0).unwrap(), 0)
await check("mapAsync", Pipeline.of(10).mapAsync(async x=>x+5).then(p=>p.unwrap()), 15)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
