// Generated by generate.ts — hidden adversarial suite for polygon-area-shoelace.
// Run via `npx tsx __audit__/polygonAreaShoelace.hidden.ts` inside the scratch project.
import { polygonAreaShoelace } from '../src/polygonAreaShoelace'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("unit square", polygonAreaShoelace([[0,0],[4,0],[4,4],[0,4]]), 16)
await check("right triangle", polygonAreaShoelace([[0,0],[4,0],[0,3]]), 6)
await check("clockwise gives absolute area", polygonAreaShoelace([[0,0],[0,4],[4,4],[4,0]]), 16)
await check("two points returns 0", polygonAreaShoelace([[0,0],[1,1]]), 0)
await check("empty returns 0", polygonAreaShoelace([]), 0)
await check("single point returns 0", polygonAreaShoelace([[3,3]]), 0)
await check("negative coords", polygonAreaShoelace([[-2,-2],[2,-2],[2,2],[-2,2]]), 16)
await check("pentagon-ish unit triangle", polygonAreaShoelace([[0,0],[2,0],[1,1]]), 1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
