// Generated by generate.ts — hidden adversarial suite for prim-mst-weight.
// Run via `npx tsx __audit__/primMstWeight.hidden.ts` inside the scratch project.
import { primMstWeight } from '../src/primMstWeight'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic", primMstWeight(4,[[0,1,1],[0,2,4],[1,2,2],[1,3,5],[2,3,3]]), 6)
await check("single", primMstWeight(1,[]), 0)
await check("two nodes", primMstWeight(2,[[0,1,7]]), 7)
await check("triangle", primMstWeight(3,[[0,1,1],[1,2,1],[0,2,10]]), 2)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
