// Generated by generate.ts — hidden adversarial suite for promise-utils.
// Run via `npx tsx __audit__/promiseUtils.hidden.ts` inside the scratch project.
import { withTimeout, pMap, pFilter } from '../src/promiseUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("withTimeout resolves", withTimeout(Promise.resolve(42), 1000), 42)
await check("withTimeout rejects on timeout", withTimeout(new Promise(()=>{}), 1, "T").catch(e=>e.message), "T")
await check("pMap basic", pMap([1,2,3], async x => x*2), [2,4,6])
await check("pMap preserves order", pMap([3,1,2], async x => x), [3,1,2])
await check("pMap empty", pMap([], async x => x), [])
await check("pMap concurrency 1", pMap([1,2,3], async x => x+10, 1), [11,12,13])
await check("pFilter basic", pFilter([1,2,3,4,5], async x => x%2===0), [2,4])
await check("pFilter all false", pFilter([1,3,5], async x => x%2===0), [])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
