// Generated by generate.ts — hidden adversarial suite for result-box.
// Run via `npx tsx __audit__/resultBox.hidden.ts` inside the scratch project.
import { ResultBox } from '../src/resultBox'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("ok unwrap", ResultBox.ok(5).unwrapOr(0), 5)
await check("err unwrap", ResultBox.err<string,number>("bad").unwrapOr(9), 9)
await check("map ok", ResultBox.ok<number,string>(3).map(x=>x*2).unwrapOr(0), 6)
await check("map err skips", ResultBox.err<string,number>("x").map(x=>x*2).unwrapOr(-1), -1)
await check("mapErr", ResultBox.err<string,number>("oops").mapErr(e=>e.length).unwrapOr(0), 0)
await check("isOk true", ResultBox.ok(1).isOk(), true)
await check("isOk false", ResultBox.err("e").isOk(), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
