// Generated by generate.ts — hidden adversarial suite for reverse-bits-32.
// Run via `npx tsx __audit__/reverseBits32.hidden.ts` inside the scratch project.
import { reverseBits32 } from '../src/reverseBits32'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("one to high bit", reverseBits32(1), 2147483648)
await check("zero", reverseBits32(0), 0)
await check("high bit to one", reverseBits32(2147483648), 1)
await check("all ones", reverseBits32(4294967295), 4294967295)
await check("involution", reverseBits32(reverseBits32(12345)), 12345)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
