// Generated by generate.ts — hidden adversarial suite for reverse-words.
// Run via `npx tsx __audit__/reverseWords.hidden.ts` inside the scratch project.
import { reverseWords } from '../src/reverseWords'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("padded", reverseWords("  hello   world  "), "world hello")
await check("sentence", reverseWords("the sky is blue"), "blue is sky the")
await check("empty", reverseWords(""), "")
await check("single", reverseWords("single"), "single")
await check("spaces only", reverseWords("   "), "")
await check("two words", reverseWords("a b"), "b a")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
