// Generated by generate.ts — hidden adversarial suite for segments-intersect-2d.
// Run via `npx tsx __audit__/segmentsIntersect.hidden.ts` inside the scratch project.
import { segmentsIntersect } from '../src/segmentsIntersect'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("proper X crossing", segmentsIntersect([0,0],[2,2],[0,2],[2,0]), true)
await check("parallel never meet", segmentsIntersect([0,0],[2,0],[0,1],[2,1]), false)
await check("touch at shared endpoint", segmentsIntersect([0,0],[1,1],[1,1],[2,0]), true)
await check("T-junction endpoint on segment", segmentsIntersect([0,0],[2,0],[1,0],[1,2]), true)
await check("collinear and disjoint", segmentsIntersect([0,0],[1,1],[2,2],[3,3]), false)
await check("collinear overlapping", segmentsIntersect([0,0],[2,0],[1,0],[3,0]), true)
await check("collinear gap no touch", segmentsIntersect([0,0],[1,0],[2,0],[3,0]), false)
await check("separated far apart", segmentsIntersect([0,0],[1,1],[5,5],[6,6]), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
