// Generated by generate.ts — hidden adversarial suite for semver.
// Run via `npx tsx __audit__/semver.hidden.ts` inside the scratch project.
import { parseSemver, compareSemver, isValidSemver } from '../src/semver'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parse basic", JSON.stringify(parseSemver("1.2.3")), "{\"major\":1,\"minor\":2,\"patch\":3}")
await check("parse with pre", parseSemver("1.0.0-alpha")?.pre, "alpha")
await check("parse with v prefix", parseSemver("v2.0.0")?.major, 2)
await check("parse invalid", parseSemver("1.2"), null)
await check("isValid true", isValidSemver("1.2.3"), true)
await check("isValid false", isValidSemver("abc"), false)
await check("compare equal", compareSemver("1.2.3","1.2.3"), 0)
await check("compare major", compareSemver("2.0.0","1.9.9"), 1)
await check("compare minor", compareSemver("1.1.0","1.2.0"), -1)
await check("compare patch", compareSemver("1.0.1","1.0.0"), 1)
await check("pre < release", compareSemver("1.0.0-alpha","1.0.0"), -1)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
