// Generated by generate.ts — hidden adversarial suite for set-ops.
// Run via `npx tsx __audit__/setOps.hidden.ts` inside the scratch project.
import { intersection, difference, union } from '../src/setOps'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("intersection basic", intersection([1,2,3],[2,3,4]), [2,3])
await check("intersection empty", intersection([1,2],[3,4]), [])
await check("intersection deduped", intersection([1,1,2],[1,2,2]), [1,2])
await check("difference basic", difference([1,2,3],[2,3]), [1])
await check("difference none removed", difference([1,2],[3,4]), [1,2])
await check("difference all removed", difference([1,2],[1,2,3]), [])
await check("union basic", union([1,2],[2,3]), [1,2,3])
await check("union deduped", union([1,1,2],[2,3,3]), [1,2,3])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
