// Generated by generate.ts — hidden adversarial suite for shuffle-seeded.
// Run via `npx tsx __audit__/shuffleSeeded.hidden.ts` inside the scratch project.
import { shuffleSeeded } from '../src/shuffleSeeded'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("length preserved", shuffleSeeded([1,2,3,4,5],42).length, 5)
await check("same elements", shuffleSeeded([1,2,3],42).sort((a,b)=>a-b), [1,2,3])
await check("deterministic", JSON.stringify(shuffleSeeded([1,2,3,4],7)) === JSON.stringify(shuffleSeeded([1,2,3,4],7)), true)
await check("different seeds", JSON.stringify(shuffleSeeded([1,2,3,4,5,6],1)) !== JSON.stringify(shuffleSeeded([1,2,3,4,5,6],2)), true)
await check("no mutate", (() => { const a=[1,2,3]; shuffleSeeded(a,5); return a })(), [1,2,3])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
