// Generated by generate.ts — hidden adversarial suite for sliding-window.
// Run via `npx tsx __audit__/slidingWindow.hidden.ts` inside the scratch project.
import { windows, rollingAverage, maxWindow } from '../src/slidingWindow'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("windows basic", windows([1,2,3,4,5], 3), [[1,2,3],[2,3,4],[3,4,5]])
await check("windows size 1", windows([1,2,3], 1), [[1],[2],[3]])
await check("windows full size", windows([1,2,3], 3), [[1,2,3]])
await check("windows empty on oversized", windows([1,2], 5), [])
await check("rollingAverage", rollingAverage([1,2,3,4,5], 3), [2,3,4])
await check("rollingAverage size 1", rollingAverage([1,2,3], 1), [1,2,3])
await check("maxWindow", maxWindow([3,1,4,1,5,9,2,6], 3), [4,4,5,9,9,9])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
