// Generated by generate.ts — hidden adversarial suite for snake-case.
// Run via `npx tsx __audit__/snakeCase.hidden.ts` inside the scratch project.
import { snakeCase } from '../src/snakeCase'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("camel to snake", snakeCase("helloWorld"), "hello_world")
await check("pascal to snake", snakeCase("HelloWorld"), "hello_world")
await check("kebab to snake", snakeCase("hello-world"), "hello_world")
await check("space to snake", snakeCase("hello world"), "hello_world")
await check("already snake", snakeCase("hello_world"), "hello_world")
await check("multiple caps", snakeCase("theQuickBrownFox"), "the_quick_brown_fox")
await check("empty", snakeCase(""), "")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
