// Generated by generate.ts — hidden adversarial suite for sorting.
// Run via `npx tsx __audit__/sorting.hidden.ts` inside the scratch project.
import { mergeSort, quickSort, insertionSort } from '../src/sorting'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("mergeSort basic", mergeSort([3,1,4,1,5,9,2,6]), [1,1,2,3,4,5,6,9])
await check("mergeSort empty", mergeSort([]), [])
await check("mergeSort sorted", mergeSort([1,2,3]), [1,2,3])
await check("mergeSort reverse", mergeSort([5,4,3,2,1]), [1,2,3,4,5])
await check("quickSort basic", quickSort([3,1,4,1,5,9,2,6]), [1,1,2,3,4,5,6,9])
await check("quickSort empty", quickSort([]), [])
await check("insertionSort basic", insertionSort([5,2,4,6,1,3]), [1,2,3,4,5,6])
await check("insertionSort single", insertionSort([1]), [1])
await check("does not mutate input", (() => { const a=[3,1,2]; mergeSort(a); return a })(), [3,1,2])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
