// Generated by generate.ts — hidden adversarial suite for standard-deviation-pop.
// Run via `npx tsx __audit__/standardDeviationPop.hidden.ts` inside the scratch project.
import { standardDeviation } from '../src/standardDeviationPop'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("empty array yields NaN", Number.isNaN(standardDeviation([])), true)
await check("single element is zero", standardDeviation([5]), 0)
await check("constant array is zero", standardDeviation([2,2,2]), 0)
await check("symmetric around zero", standardDeviation([-1,1]), 1)
await check("sqrt of variance two", standardDeviation([1,2,3,4,5]), Math.sqrt(2))
await check("larger spread sqrt 125", standardDeviation([10,20,30,40]), Math.sqrt(125))
await check("matches manual two element", standardDeviation([1,2]), 0.5)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
