// Generated by generate.ts — hidden adversarial suite for string-extras.
// Run via `npx tsx __audit__/stringExtras.hidden.ts` inside the scratch project.
import { pluralize, stripHtml, initials, words, nl2br } from '../src/stringExtras'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("pluralize 1", pluralize("cat", 1), "cat")
await check("pluralize 2", pluralize("cat", 2), "cats")
await check("pluralize custom", pluralize("child", 2, "children"), "children")
await check("pluralize -es", pluralize("box", 2), "boxes")
await check("stripHtml basic", stripHtml("<b>hello</b>"), "hello")
await check("stripHtml entities", stripHtml("<p>a &amp; b</p>"), "a & b")
await check("stripHtml nested", stripHtml("<div><p>text</p></div>"), "text")
await check("initials two words", initials("John Doe"), "JD")
await check("initials three words", initials("Mary Jane Watson"), "MJW")
await check("words basic", words("hello world"), ["hello","world"])
await check("words with punct", words("hello, world!"), ["hello","world"])
await check("nl2br basic", nl2br("line1\nline2"), "line1<br>line2")
await check("nl2br crlf", nl2br("a\r\nb"), "a<br>b")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
