// Generated by generate.ts — hidden adversarial suite for string-validators.
// Run via `npx tsx __audit__/stringValidators.hidden.ts` inside the scratch project.
import { isAlpha, isAlphanumeric, isNumeric, isHexColor, isIPv4, isPort } from '../src/stringValidators'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("isAlpha true", isAlpha("hello"), true)
await check("isAlpha false digit", isAlpha("hello1"), false)
await check("isAlpha empty", isAlpha(""), false)
await check("isAlphanumeric true", isAlphanumeric("hello123"), true)
await check("isAlphanumeric false space", isAlphanumeric("hello world"), false)
await check("isNumeric int", isNumeric("42"), true)
await check("isNumeric float", isNumeric("3.14"), true)
await check("isNumeric false", isNumeric("abc"), false)
await check("isNumeric empty", isNumeric(""), false)
await check("isHexColor 6 digit", isHexColor("#ff0000"), true)
await check("isHexColor 3 digit", isHexColor("#f00"), true)
await check("isHexColor invalid", isHexColor("ff0000"), false)
await check("isIPv4 valid", isIPv4("192.168.1.1"), true)
await check("isIPv4 invalid octet", isIPv4("192.168.1.256"), false)
await check("isIPv4 wrong parts", isIPv4("1.2.3"), false)
await check("isPort valid", isPort(8080), true)
await check("isPort zero", isPort(0), true)
await check("isPort overflow", isPort(65536), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
