// Generated by generate.ts — hidden adversarial suite for subset-sum-exists.
// Run via `npx tsx __audit__/subsetSumExists.hidden.ts` inside the scratch project.
import { subsetSumExists } from '../src/subsetSumExists'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("classic true", subsetSumExists([3,34,4,12,5,2],9), true)
await check("classic false", subsetSumExists([3,34,4,12,5,2],30), false)
await check("empty target zero", subsetSumExists([],0), true)
await check("empty positive target", subsetSumExists([],5), false)
await check("exact sum", subsetSumExists([1,2,3],6), true)
await check("over sum", subsetSumExists([1,2,3],7), false)
await check("single match", subsetSumExists([5],5), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
