// Generated by generate.ts — hidden adversarial suite for sum-by.
// Run via `npx tsx __audit__/sumBy.hidden.ts` inside the scratch project.
import { sumBy, minBy, maxBy, sortBy } from '../src/sumBy'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("sumBy numbers", sumBy([{v:1},{v:2},{v:3}], x=>x.v), 6)
await check("sumBy empty", sumBy([], (x:any)=>x), 0)
await check("minBy", minBy([{v:3},{v:1},{v:2}], x=>x.v), {"v":1})
await check("minBy empty", minBy([], (x:any)=>x), undefined)
await check("maxBy", maxBy([{v:3},{v:1},{v:2}], x=>x.v), {"v":3})
await check("sortBy number", sortBy([3,1,2], x=>x), [1,2,3])
await check("sortBy field", sortBy([{n:"b"},{n:"a"},{n:"c"}], x=>x.n), [{"n":"a"},{"n":"b"},{"n":"c"}])
await check("sortBy stable empty", sortBy([], (x:any)=>x), [])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
