// Generated by generate.ts — hidden adversarial suite for template-engine.
// Run via `npx tsx __audit__/templateEngine.hidden.ts` inside the scratch project.
import { renderTemplate } from '../src/templateEngine'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic substitution", renderTemplate("Hello, {{name}}!", {name:"World"}), "Hello, World!")
await check("multiple keys", renderTemplate("{{a}} + {{b}}", {a:"1",b:"2"}), "1 + 2")
await check("missing key gives empty", renderTemplate("{{x}}", {}), "")
await check("nested key", renderTemplate("{{user.name}}", {user:{name:"Alice"}}), "Alice")
await check("whitespace in braces", renderTemplate("{{ name }}", {name:"Bob"}), "Bob")
await check("no placeholders", renderTemplate("plain text", {}), "plain text")
await check("number value", renderTemplate("{{n}}", {n:42}), "42")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
