// Generated by generate.ts — hidden adversarial suite for trie-simple.
// Run via `npx tsx __audit__/trieSimple.hidden.ts` inside the scratch project.
import { Trie } from '../src/trieSimple'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("search inserted word", (() => { const t = new Trie(); t.insert("hello"); return t.search("hello") })(), true)
await check("search missing word", (() => { const t = new Trie(); t.insert("hello"); return t.search("hell") })(), false)
await check("startsWith true", (() => { const t = new Trie(); t.insert("hello"); return t.startsWith("hel") })(), true)
await check("startsWith false", (() => { const t = new Trie(); t.insert("hello"); return t.startsWith("world") })(), false)
await check("words with prefix", (() => { const t = new Trie(); ["apple","app","application"].forEach(w=>t.insert(w)); return t.words("app").sort() })(), ["app","apple","application"])
await check("words all", (() => { const t = new Trie(); ["hi","ho"].forEach(w=>t.insert(w)); return t.words().sort() })(), ["hi","ho"])
await check("empty trie", new Trie().search("x"), false)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
