// Generated by generate.ts — hidden adversarial suite for url-utils.
// Run via `npx tsx __audit__/urlUtils.hidden.ts` inside the scratch project.
import { parseURL, buildURL, getQueryParam, updateQueryParam } from '../src/urlUtils'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("parseURL basic", parseURL("https://example.com/path?q=1")?.pathname, "/path")
await check("parseURL params", parseURL("https://ex.com?a=1&b=2")?.params["b"], "2")
await check("parseURL invalid", parseURL("not-a-url"), null)
await check("buildURL adds param", buildURL("https://ex.com", {q:"hello"}).includes("q=hello"), true)
await check("getQueryParam found", getQueryParam("https://ex.com?key=val", "key"), "val")
await check("getQueryParam missing", getQueryParam("https://ex.com", "key"), null)
await check("updateQueryParam updates", getQueryParam(updateQueryParam("https://ex.com?k=old","k","new"), "k"), "new")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
