// Generated by generate.ts — hidden adversarial suite for uuid.
// Run via `npx tsx __audit__/uuid.hidden.ts` inside the scratch project.
import { uuidv4 } from '../src/uuid'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("format matches uuid v4", /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(uuidv4()), true)
await check("length is 36", uuidv4().length, 36)
await check("unique each call", uuidv4() !== uuidv4(), true)
await check("version digit is 4", uuidv4()[14], "4")
await check("variant digit is 8-b", "89ab".includes(uuidv4()[19]), true)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
