// Generated by generate.ts — hidden adversarial suite for variance-pop.
// Run via `npx tsx __audit__/variancePopulation.hidden.ts` inside the scratch project.
import { variancePop } from '../src/variancePopulation'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("empty array yields NaN", Number.isNaN(variancePop([])), true)
await check("single element has zero variance", variancePop([5]), 0)
await check("constant array has zero variance", variancePop([2,2,2]), 0)
await check("simple sequence", variancePop([1,2,3,4,5]), 2)
await check("two element pair", variancePop([1,2]), 0.25)
await check("symmetric around zero", variancePop([-1,1]), 1)
await check("larger spread", variancePop([10,20,30,40]), 125)
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
