// Generated by generate.ts — hidden adversarial suite for word-wrap.
// Run via `npx tsx __audit__/wordWrap.hidden.ts` inside the scratch project.
import { wordWrap } from '../src/wordWrap'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic wrap", wordWrap("the quick brown fox", 10), "the quick\nbrown fox")
await check("no wrap needed", wordWrap("hello world", 20), "hello world")
await check("single word", wordWrap("hello", 3), "hello")
await check("empty", wordWrap("", 10), "")
await check("over width wraps", wordWrap("hi there!", 8), "hi\nthere!")
await check("multiple lines", wordWrap("a b c d e", 3), "a b\nc d\ne")
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
