// Generated by generate.ts — hidden adversarial suite for z-function-array.
// Run via `npx tsx __audit__/zFunctionArray.hidden.ts` inside the scratch project.
import { zFunctionArray } from '../src/zFunctionArray'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("aabaab", zFunctionArray("aabaab"), [6,1,0,3,1,0])
await check("all a", zFunctionArray("aaaaa"), [5,4,3,2,1])
await check("empty", zFunctionArray(""), [])
await check("single", zFunctionArray("a"), [1])
await check("no repeat", zFunctionArray("abc"), [3,0,0])
await check("abab", zFunctionArray("abab"), [4,0,2,0])
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
