// Generated by generate.ts — hidden adversarial suite for zip.
// Run via `npx tsx __audit__/zip.hidden.ts` inside the scratch project.
import { zip, unzip } from '../src/zip'

let failures = 0
async function check(name: string, got: unknown, want: unknown) {
  got = await got  // resolve promises transparently
  const ok = JSON.stringify(got) === JSON.stringify(want)
  console.log(`  ${ok ? 'PASS' : 'FAIL'} — ${name}`)
  if (!ok) {
    console.log(`       got:  ${JSON.stringify(got)}`)
    console.log(`       want: ${JSON.stringify(want)}`)
    failures++
  }
}

;(async () => {
await check("basic zip", zip([1,2,3],["a","b","c"]), [[1,"a"],[2,"b"],[3,"c"]])
await check("zip shorter", zip([1,2,3],["a","b"]), [[1,"a"],[2,"b"]])
await check("zip empty", zip([],[1,2]), [])
await check("unzip basic", unzip([[1,"a"],[2,"b"],[3,"c"]]), [[1,2,3],["a","b","c"]])
await check("unzip empty", unzip([]), [[],[]])
await check("zip roundtrip", JSON.stringify(unzip(zip([1,2],["a","b"]))), JSON.stringify([[1,2],["a","b"]]))
console.log(failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
})()
